imports

In [2]:
%load_ext autoreload
%autoreload 2

import warnings
import pandas as pd
import numpy as np
import plotly.express as px
from gencost.crosswalk import Crosswalk
from gencost.waterfall import DataBySubplant

warnings.simplefilter(action="once")

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

create data source object

In [3]:
xwalk = Crosswalk()
# self to be able to copy / paste from waterfall.py for dev ease
self = DataBySubplant(xwalk)

historical data

In [412]:
hist = self.get_exa_by_generator()

/opt/anaconda3/envs/gencost/lib/python3.11/site-packages/etoolbox/utils/pudl_helpers.py:146: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[date_mask, date_col] = pd.to_datetime(
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:258: UserWarning: This crosswalk is not safe, it may have `pf_subplants with multiple primes. Use `safe_xwalk` instead.
  return self._xwalk.grand_crosswalk
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:199: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  np.repeat(df[old_cols].sum(axis=1)[:, np.newaxis], len(old_cols), 1) != 0.0,
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:204: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  df[old_cols].isna().sum(axis=1)[:, np.newaxis], len(old_cols), 1
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:213: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  df[to_allocate][:, np.newaxis],
/opt/anaconda3/envs/gencost/lib/python3.11/site-packages/etoolbox/utils/pudl_helpers.py:146: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[date_mask, date_col] = pd.to_datetime(

In [414]:
hist.query('plant_id_eia == 8',engine='python')

,plant_id_eia,generator_id,report_date,biofuel_mmbtu,coal_mmbtu,natural_gas_mmbtu,nuclear_mmbtu,other_mmbtu,other_gas_mmbtu,petroleum_mmbtu,...,age_in_current_year,age_of_observation,age_relative_to_prime_avg,pollution_control_costs_per_kw,respondent_id,respondent_id_purchaser,final_respondent_id,final_ba_code,wage_scale,age_of_observation_secular_adj
389,8,10,2006-01-01,NaN,4.678691e+07,NaN,NaN,NaN,NaN,NaN,...,49.166324,15.915127,-4.924752,NaN,2,<NA>,2,2,1.050357,13.40423
390,8,10,2007-01-01,NaN,4.161849e+07,NaN,NaN,NaN,NaN,NaN,...,49.166324,14.915811,-3.925436,NaN,2,<NA>,2,2,1.057435,14.461664
391,8,10,2008-01-01,NaN,4.364463e+07,NaN,NaN,NaN,NaN,NaN,...,49.166324,13.916496,-2.926121,NaN,2,<NA>,2,2,0.99812,15.459785
392,8,10,2009-01-01,NaN,3.856048e+07,NaN,NaN,NaN,NaN,41736.364147,...,49.166324,12.914442,-1.924067,NaN,2,<NA>,2,2,0.97293,16.432715
393,8,10,2010-01-01,NaN,4.672740e+07,NaN,NaN,NaN,NaN,38853.150624,...,49.166324,11.915127,-0.924752,NaN,2,<NA>,2,2,0.941299,17.374014
394,8,10,2011-01-01,NaN,3.272167e+07,NaN,NaN,NaN,NaN,94971.312151,...,49.166324,10.915811,0.074564,NaN,2,<NA>,2,2,0.973222,18.347236
395,8,10,2012-01-01,NaN,2.186992e+07,NaN,NaN,NaN,NaN,60951.750161,...,49.166324,9.916496,1.073879,NaN,2,<NA>,2,2,0.983656,19.330892
396,8,10,2013-01-01,NaN,2.620028e+07,NaN,NaN,NaN,NaN,41079.481263,...,49.166324,8.914442,2.075933,NaN,2,<NA>,2,2,0.951011,20.281903
397,8,10,2014-01-01,NaN,4.118150e+07,NaN,NaN,NaN,NaN,49907.704881,...,49.166324,7.915127,3.075248,NaN,2,<NA>,2,2,0.935684,21.217587
398,8,10,2015-01-01,NaN,3.749261e+07,NaN,NaN,NaN,NaN,92158.776051,...,49.166324,6.915811,4.074564,NaN,2,<NA>,2,2,0.973045,22.190632
399,8,10,2016-01-01,NaN,3.933887e+07,NaN,NaN,NaN,NaN,75523.396346,...,49.166324,5.916496,5.073879,NaN,2,<NA>,2,2,1.011758,23.20239
400,8,10,2017-01-01,NaN,3.354794e+07,NaN,NaN,NaN,NaN,81401.991175,...,49.166324,4.914442,6.075933,NaN,2,<NA>,2,2,1.003936,24.206326
401,8,10,2018-01-01,NaN,4.069621e+07,NaN,NaN,NaN,NaN,53305.166966,...,49.166324,3.915127,7.075248,NaN,2,<NA>,2,2,1.020267,25.226593
408,8,6,2006-01-01,NaN,7.414254e+06,NaN,NaN,NaN,NaN,NaN,...,70.669405,15.915127,16.578328,NaN,2,<NA>,2,2,1.050357,13.40423
409,8,6,2007-01-01,NaN,6.595222e+06,NaN,NaN,NaN,NaN,NaN,...,70.669405,14.915811,17.577644,NaN,2,<NA>,2,2,1.057435,14.461664
410,8,6,2008-01-01,NaN,5.906565e+06,NaN,NaN,NaN,NaN,NaN,...,70.669405,13.916496,18.576960,NaN,2,<NA>,2,2,0.99812,15.459785
411,8,6,2009-01-01,NaN,1.261108e+06,NaN,NaN,NaN,NaN,15318.435091,...,70.669405,12.914442,19.579013,NaN,2,<NA>,2,2,0.97293,16.432715
412,8,6,2010-01-01,NaN,2.878246e+06,NaN,NaN,NaN,NaN,26679.963736,...,70.669405,11.915127,20.578328,NaN,2,<NA>,2,2,0.941299,17.374014
413,8,6,2011-01-01,NaN,3.000759e+06,NaN,NaN,NaN,NaN,17307.452658,...,70.669405,10.915811,21.577644,NaN,2,<NA>,2,2,0.973222,18.347236
414,8,6,2012-01-01,NaN,7.048148e+05,NaN,NaN,NaN,NaN,4005.522811,...,70.669405,9.916496,22.576960,NaN,2,<NA>,2,2,0.983656,19.330892
415,8,6,2013-01-01,NaN,3.100775e+05,NaN,NaN,NaN,NaN,6853.597976,...,70.669405,8.914442,23.579013,NaN,2,<NA>,2,2,0.951011,20.281903
416,8,6,2014-01-01,NaN,5.318009e+05,NaN,NaN,NaN,NaN,10012.496325,...,70.669405,7.915127,24.578328,NaN,2,<NA>,2,2,0.935684,21.217587
424,8,7,2006-01-01,NaN,7.414254e+06,NaN,NaN,NaN,NaN,NaN,...,69.418207,15.915127,15.327131,NaN,2,<NA>,2,2,1.050357,13.40423
425,8,7,2007-01-01,NaN,6.595222e+06,NaN,NaN,NaN,NaN,NaN,...,69.418207,14.915811,16.326446,NaN,2,<NA>,2,2,1.057435,14.461664
426,8,7,2008-01-01,NaN,6.796618e+06,NaN,NaN,NaN,NaN,NaN,...,69.418207,13.916496,17.325762,NaN,2,<NA>,2,2,0.99812,15.459785
427,8,7,2009-01-01,NaN,1.151899e+06,NaN,NaN,NaN,NaN,13738.136504,...,69.418207,12.914442,18.327815,NaN,2,<NA>,2,2,0.97293,16.432715
428,8,7,2010-01-01,NaN,2.869114e+06,NaN,NaN,NaN,NaN,24110.963858,...,69.418207,11.915127,19.327131,NaN,2,<NA>,2,2,0.941299,17.374014
429,8,7,2011-01-01,NaN,3.128407e+06,NaN,NaN,NaN,NaN,13964.876949,...,69.418207,10.915811,20.326446,NaN,2,<NA>,2,2,0.973222,18.347236
430,8,7,2012-01-01,NaN,1.219469e+06,NaN,NaN,NaN,NaN,5972.579948,...,69.418207,9.916496,21.325762,NaN,2,<NA>,2,2,0.983656,19.330892
431,8,7,2013-01-01,NaN,3.315066e+05,NaN,NaN,NaN,NaN,2862.941441,...,69.418207,8.914442,22.327815,NaN,2,<NA>,2,2,0.951011,20.281903
432,8,7,2014-01-01,NaN,5.183682e+05,NaN,NaN,NaN,NaN,11000.124368,...,69.418207,7.915127,23.327131,NaN,2,<NA>,2,2,0.935684,21.217587
440,8,8,2006-01-01,NaN,1.112138e+07,NaN,NaN,NaN,NaN,NaN,...,65.585216,15.915127,11.494140,NaN,2,<NA>,2,2,1.050357,13.40423
441,8,8,2007-01-01,NaN,9.892833e+06,NaN,NaN,NaN,NaN,NaN,...,65.585216,14.915811,12.493455,NaN,2,<NA>,2,2,1.057435,14.461664
442,8,8,2008-01-01,NaN,1.117751e+07,NaN,NaN,NaN,NaN,NaN,...,65.585216,13.916496,13.492771,NaN,2,<NA>,2,2,0.99812,15.459785
443,8,8,2009-01-01,NaN,6.010798e+06,NaN,NaN,NaN,NaN,19319.781670,...,65.585216,12.914442,14.494824,NaN,2,<NA>,2,2,0.97293,16.432715
444,8,8,2010-01-01,NaN,7.663696e+06,NaN,NaN,NaN,NaN,7859.080005,...,65.585216,11.915127,15.494140,NaN,2,<NA>,2,2,0.941299,17.374014
445,8,8,2011-01-01,NaN,5.621957e+06,NaN,NaN,NaN,NaN,27321.621318,...,65.585216,10.915811,16.493455,NaN,2,<NA>,2,2,0.973222,18.347236
446,8,8,2012-01-01,NaN,3.471889e+06,NaN,NaN,NaN,NaN,6649.394729,...,65.585216,9.916496,17.492771,NaN,2,<NA>,2,2,0.983656,19.330892
447,8,8,2013-01-01,NaN,5.091562e+06,NaN,NaN,NaN,NaN,17106.758511,...,65.585216,8.914442,18.494824,NaN,2,<NA>,2,2,0.951011,20.281903
448,8,8,2014-01-01,NaN,5.490742e+06,NaN,NaN,NaN,NaN,18108.248314,...,65.585216,7.915127,19.494140,NaN,2,<NA>,2,2,0.935684,21.217587
449,8,8,2015-01-01,NaN,3.974481e+06,NaN,NaN,NaN,NaN,21762.620381,...,65.585216,6.915811,20.493455,NaN,2,<NA>,2,2,0.973045,22.190632
450,8,8,2016-01-01,NaN,6.927875e+06,NaN,NaN,NaN,NaN,23964.251274,...,65.585216,5.916496,21.492771,NaN,2,<NA>,2,2,1.011758,23.20239
451,8,8,2017-01-01,NaN,3.057559e+06,NaN,NaN,NaN,NaN,27088.494566,...,65.585216,4.914442,22.494824,NaN,2,<NA>,2,2,1.003936,24.206326
452,8,8,2018-01-01,NaN,5.213828e+06,NaN,NaN,NaN,NaN,13686.814593,...,65.585216,3.915127,23.494140,NaN,2,<NA>,2,2,1.020267,25.226593
459,8,9,2006-01-01,NaN,1.129339e+07,NaN,NaN,NaN,NaN,NaN,...,63.501711,15.915127,9.410635,NaN,2,<NA>,2,2,1.050357,13.40423
460,8,9,2007-01-01,NaN,1.004584e+07,NaN,NaN,NaN,NaN,NaN,...,63.501711,14.915811,10.409951,NaN,2,<NA>,2,2,1.057435,14.461664
461,8,9,2008-01-01,NaN,1.181335e+07,NaN,NaN,NaN,NaN,NaN,...,63.501711,13.916496,11.409266,NaN,2,<NA>,2,2,0.99812,15.459785
462,8,9,2009-01-01,NaN,5.614759e+06,NaN,NaN,NaN,NaN,8479.282589,...,63.501711,12.914442,12.411320,NaN,2,<NA>,2,2,0.97293,16.432715
463,8,9,2010-01-01,NaN,9.552149e+06,NaN,NaN,NaN,NaN,12359.841777,...,63.501711,11.915127,13.410635,NaN,2,<NA>,2,2,0.941299,17.374014
464,8,9,2011-01-01,NaN,6.054811e+06,NaN,NaN,NaN,NaN,12940.736923,...,63.501711,10.915811,14.409951,NaN,2,<NA>,2,2,0.973222,18.347236
465,8,9,2012-01-01,NaN,4.679725e+06,NaN,NaN,NaN,NaN,17456.752351,...,63.501711,9.916496,15.409266,NaN,2,<NA>,2,2,0.983656,19.330892
466,8,9,2013-01-01,NaN,3.291413e+06,NaN,NaN,NaN,NaN,7237.220809,...,63.501711,8.914442,16.411320,NaN,2,<NA>,2,2,0.951011,20.281903
467,8,9,2014-01-01,NaN,4.414582e+06,NaN,NaN,NaN,NaN,15299.426112,...,63.501711,7.915127,17.410635,NaN,2,<NA>,2,2,0.935684,21.217587
468,8,9,2015-01-01,NaN,3.923309e+06,NaN,NaN,NaN,NaN,14780.505019,...,63.501711,6.915811,18.409951,NaN,2,<NA>,2,2,0.973045,22.190632
469,8,9,2016-01-01,NaN,7.153931e+06,NaN,NaN,NaN,NaN,26210.352359,...,63.501711,5.916496,19.409266,NaN,2,<NA>,2,2,1.011758,23.20239
470,8,9,2017-01-01,NaN,7.396762e+06,NaN,NaN,NaN,NaN,15612.514259,...,63.501711,4.914442,20.411320,NaN,2,<NA>,2,2,1.003936,24.206326
471,8,9,2018-01-01,NaN,7.491092e+06,NaN,NaN,NaN,NaN,5833.018442,...,63.501711,3.915127,21.410635,NaN,2,<NA>,2,2,1.020267,25.226593

task 1: find instances when a generator reports in the middle of a range

In [194]:
# count n years

# figure out which years are missing

#make list of years belonging to each gen

# compare to list of years we need 


import datetime as dt


df = (hist
.assign(n_years_gen = lambda x: x.groupby(['plant_id_eia','generator_id'])['report_date'].transform('nunique'),
report_year =lambda x: x.report_date.dt.year)
.query('n_years_gen != 15')
.groupby(['plant_id_eia','generator_id'])['report_year'].agg(list).reset_index()
.assign(needed_years = lambda x: x.apply(lambda _: [*range(2006,2020,1)],axis=1),
missing_years = lambda x: (x['needed_years'].map(set) - x['report_year'].map(set)),
years_to_fill_in = lambda x: x['missing_years'].apply(list)))

task 2: find instances when generator changes fuel type

1) establish single fuel definition threshold
2) throw out multi-fuel generator observations
3) do fuel change check somehow - make list?

In [230]:
#list of cols we need for melt
fuel_consump_cols = ['biofuel_mmbtu',
       'coal_mmbtu', 'natural_gas_mmbtu', 'nuclear_mmbtu', 'other_mmbtu',
       'other_gas_mmbtu', 'petroleum_mmbtu', 'petroleum_coke_mmbtu',
       'renew_mmbtu'] 
#melt to facilitate group by and percent of net gen totals
test = (hist.melt(id_vars=['plant_id_eia','generator_id','report_date'],value_vars=fuel_consump_cols,var_name='fuel_mmbtu',value_name='fuel_consumption')
.assign(
percent_of_gen = lambda x: (x['fuel_consumption'] / x.groupby(['plant_id_eia','generator_id','report_date'])['fuel_consumption'].transform('sum')),
single_fuel = lambda x: np.where(x['percent_of_gen'] >= .9,1,0),
single_fuel_present = lambda x: x.groupby(['plant_id_eia','generator_id','report_date'])['single_fuel'].transform('sum'))
.query('single_fuel_present == 1 & percent_of_gen >= .9')
.assign(n_fuels = lambda x: x.groupby(['plant_id_eia','generator_id'])['fuel_mmbtu'].transform('nunique'))
.query('n_fuels > 1')
#.reset_index()
)

In [231]:
test

,plant_id_eia,generator_id,report_date,fuel_mmbtu,fuel_consumption,percent_of_gen,single_fuel,single_fuel_present,n_fuels
33659,7527,2,2012-01-01,biofuel_mmbtu,323518.0,0.998774,1,1,2
40048,10333,GEN1,2013-01-01,biofuel_mmbtu,450933.0,0.970638,1,1,2
40049,10333,GEN1,2014-01-01,biofuel_mmbtu,1518064.0,0.993868,1,1,2
40050,10333,GEN1,2015-01-01,biofuel_mmbtu,5733380.0,0.983817,1,1,2
40051,10333,GEN1,2016-01-01,biofuel_mmbtu,5104054.0,0.994192,1,1,2
...,...,...,...,...,...,...,...,...,...
545459,6043,8,2016-01-01,renew_mmbtu,695179.0,1.000000,1,1,2
545460,6043,8,2017-01-01,renew_mmbtu,199074.0,1.000000,1,1,2
545461,6043,8,2018-01-01,renew_mmbtu,468365.0,1.000000,1,1,2
545462,6043,8,2019-01-01,renew_mmbtu,249054.0,1.000000,1,1,2
545463,6043,8,2020-01-01,renew_mmbtu,260503.0,1.000000,1,1,2

three fuel instances

In [157]:
test.query('n_fuels == 3')['plant_id_eia'].unique()

<IntegerArray>
[3264, 3796, 7242]
Length: 3, dtype: Int64

In [166]:
test.query('n_fuels == 3 & plant_id_eia == 3264',engine='python')

,plant_id_eia,generator_id,report_date,fuel_mwh,net_generation,percent_of_gen,single_fuel,single_fuel_present,n_fuels
86577,3264,3,2006-01-01,coal_net_mwh,609356.901408,1.000000,1,1,3
86578,3264,3,2007-01-01,coal_net_mwh,738759.263239,1.000000,1,1,3
86579,3264,3,2008-01-01,coal_net_mwh,473466.009819,1.000000,1,1,3
86580,3264,3,2009-01-01,coal_net_mwh,293646.001498,0.990453,1,1,3
86581,3264,3,2010-01-01,coal_net_mwh,571956.150823,0.995342,1,1,3
86582,3264,3,2011-01-01,coal_net_mwh,385133.109790,0.994534,1,1,3
86583,3264,3,2012-01-01,coal_net_mwh,79153.068138,0.978164,1,1,3
86584,3264,3,2013-01-01,coal_net_mwh,30665.057444,0.997786,1,1,3
151238,3264,3,2015-01-01,natural_gas_net_mwh,90194.000000,0.980391,1,1,3
151239,3264,3,2016-01-01,natural_gas_net_mwh,221407.679000,0.997357,1,1,3
151240,3264,3,2017-01-01,natural_gas_net_mwh,40117.000000,1.000000,1,1,3
151241,3264,3,2018-01-01,natural_gas_net_mwh,54152.000000,1.000000,1,1,3
151242,3264,3,2019-01-01,natural_gas_net_mwh,5559.000000,1.000000,1,1,3
151243,3264,3,2020-01-01,natural_gas_net_mwh,3437.000000,1.000000,1,1,3
409845,3264,3,2014-01-01,petroleum_net_mwh,2217.785251,1.000000,1,1,3

In [156]:
test.query('n_fuels == 3 & plant_id_eia == 7242',engine='python')

,plant_id_eia,generator_id,report_date,fuel_mwh,net_generation,percent_of_gen,single_fuel,single_fuel_present,n_fuels
97030,7242,1CA,2007-01-01,coal_net_mwh,1.429163e+05,0.987823,1,1,3
97031,7242,1CA,2008-01-01,coal_net_mwh,1.436358e+06,0.980022,1,1,3
97032,7242,1CA,2009-01-01,coal_net_mwh,1.288468e+06,0.983933,1,1,3
97035,7242,1CA,2012-01-01,coal_net_mwh,1.161898e+06,0.988891,1,1,3
97036,7242,1CA,2013-01-01,coal_net_mwh,3.342555e+05,0.981831,1,1,3
97037,7242,1CA,2014-01-01,coal_net_mwh,6.680525e+05,0.917926,1,1,3
97044,7242,1CT,2006-01-01,coal_net_mwh,1.546263e+06,0.973204,1,1,3
97045,7242,1CT,2007-01-01,coal_net_mwh,1.420597e+06,0.979028,1,1,3
97051,7242,1CT,2013-01-01,coal_net_mwh,8.912436e+05,0.943200,1,1,3
161694,7242,1CA,2019-01-01,natural_gas_net_mwh,1.893284e+05,1.000000,1,1,3
161695,7242,1CA,2020-01-01,natural_gas_net_mwh,1.638546e+05,1.000000,1,1,3
161709,7242,1CT,2019-01-01,natural_gas_net_mwh,4.249892e+05,1.000000,1,1,3
161710,7242,1CT,2020-01-01,natural_gas_net_mwh,4.226886e+05,1.000000,1,1,3
420293,7242,1CA,2010-01-01,petroleum_net_mwh,3.243294e+04,1.000000,1,1,3
420294,7242,1CA,2011-01-01,petroleum_net_mwh,8.720142e+03,1.000000,1,1,3
420306,7242,1CT,2008-01-01,petroleum_net_mwh,3.195100e+04,1.000000,1,1,3
420307,7242,1CT,2009-01-01,petroleum_net_mwh,2.830400e+04,1.000000,1,1,3
420308,7242,1CT,2010-01-01,petroleum_net_mwh,3.796200e+04,1.000000,1,1,3
420309,7242,1CT,2011-01-01,petroleum_net_mwh,1.242800e+04,1.000000,1,1,3
420310,7242,1CT,2012-01-01,petroleum_net_mwh,1.996400e+04,1.000000,1,1,3

In [158]:
test.query('n_fuels == 3 & plant_id_eia == 3796',engine='python')

,plant_id_eia,generator_id,report_date,fuel_mwh,net_generation,percent_of_gen,single_fuel,single_fuel_present,n_fuels
90358,3796,3,2008-01-01,coal_net_mwh,315705.609876,1.000000,1,1,3
90359,3796,3,2009-01-01,coal_net_mwh,174220.286390,0.996273,1,1,3
90360,3796,3,2010-01-01,coal_net_mwh,229964.775925,0.996347,1,1,3
90361,3796,3,2011-01-01,coal_net_mwh,112236.735078,0.994240,1,1,3
90362,3796,3,2012-01-01,coal_net_mwh,60727.931244,0.989780,1,1,3
90363,3796,3,2013-01-01,coal_net_mwh,59908.877294,0.991147,1,1,3
90371,3796,4,2008-01-01,coal_net_mwh,876224.251124,1.000000,1,1,3
90372,3796,4,2009-01-01,coal_net_mwh,744548.834610,0.997052,1,1,3
90373,3796,4,2010-01-01,coal_net_mwh,750688.642075,0.996069,1,1,3
90374,3796,4,2011-01-01,coal_net_mwh,701831.194922,0.995408,1,1,3
90375,3796,4,2012-01-01,coal_net_mwh,286720.810756,0.986953,1,1,3
90376,3796,4,2013-01-01,coal_net_mwh,419049.399706,0.992888,1,1,3
155016,3796,3,2014-01-01,natural_gas_net_mwh,189560.105239,0.999937,1,1,3
155017,3796,3,2015-01-01,natural_gas_net_mwh,40501.000000,1.000000,1,1,3
155018,3796,3,2016-01-01,natural_gas_net_mwh,64042.000000,1.000000,1,1,3
155019,3796,3,2017-01-01,natural_gas_net_mwh,10387.000000,1.000000,1,1,3
155020,3796,3,2018-01-01,natural_gas_net_mwh,13139.416667,1.000000,1,1,3
155029,3796,4,2014-01-01,natural_gas_net_mwh,174592.936761,1.000000,1,1,3
155030,3796,4,2015-01-01,natural_gas_net_mwh,174078.000000,1.000000,1,1,3
155031,3796,4,2016-01-01,natural_gas_net_mwh,337018.000000,1.000000,1,1,3
155032,3796,4,2017-01-01,natural_gas_net_mwh,113348.000000,1.000000,1,1,3
155033,3796,4,2018-01-01,natural_gas_net_mwh,943.583333,1.000000,1,1,3
413616,3796,3,2006-01-01,petroleum_net_mwh,1094.445319,1.000000,1,1,3
413617,3796,3,2007-01-01,petroleum_net_mwh,762.338981,1.000000,1,1,3
413629,3796,4,2006-01-01,petroleum_net_mwh,2937.554681,1.000000,1,1,3
413630,3796,4,2007-01-01,petroleum_net_mwh,2046.162019,1.000000,1,1,3

In [161]:
test['plant_gen_id'] = str(test['plant_id_eia']) + "_" + test['generator_id']

test['plant_gen_id'].nunique()

44

In [168]:
test

,plant_id_eia,generator_id,report_date,fuel_mwh,net_generation,percent_of_gen,single_fuel,single_fuel_present,n_fuels
40048,10333,GEN1,2013-01-01,biofuel_net_mwh,23481.872,0.973030,1,1,2
40049,10333,GEN1,2014-01-01,biofuel_net_mwh,106943.383,0.993935,1,1,2
40050,10333,GEN1,2015-01-01,biofuel_net_mwh,200282.936,0.982179,1,1,2
40051,10333,GEN1,2016-01-01,biofuel_net_mwh,334718.961,0.994143,1,1,2
40187,10382,GEN1,2015-01-01,biofuel_net_mwh,20109.000,1.000000,1,1,2
...,...,...,...,...,...,...,...,...,...
428442,10633,ST1,2014-01-01,petroleum_net_mwh,12074.770,1.000000,1,1,2
430582,50966,1,2018-01-01,petroleum_net_mwh,37525.124,0.943032,1,1,2
430881,52026,GEN3,2010-01-01,petroleum_net_mwh,1959.722,0.984785,1,1,2
441570,55349,1,2009-01-01,petroleum_net_mwh,5932.500,0.977992,1,1,2
441585,55349,2,2009-01-01,petroleum_net_mwh,5932.500,0.977992,1,1,2

scenario 3: where there are zeros for key columns

my interpretation: when

In [167]:
hist

,plant_id_eia,generator_id,report_date,biofuel_mmbtu,coal_mmbtu,natural_gas_mmbtu,nuclear_mmbtu,other_mmbtu,other_gas_mmbtu,petroleum_mmbtu,...,ultrasupercritical_tech,age_in_report_year,age_in_current_year,age_of_observation,age_relative_to_prime_avg,pollution_control_costs_per_kw,respondent_id,respondent_id_purchaser,final_respondent_id,final_ba_code
51,3,1,2006-01-01,NaN,1.008871e+07,2.951150e+04,NaN,NaN,NaN,NaN,...,1.0,51.915127,67.830253,15.915127,13.739177,2.92732,2,<NA>,2,2
52,3,1,2007-01-01,NaN,9.807031e+06,NaN,NaN,NaN,NaN,NaN,...,1.0,52.914442,67.830253,14.915811,14.738493,2.92732,2,<NA>,2,2
53,3,1,2008-01-01,NaN,8.176078e+06,NaN,NaN,NaN,NaN,NaN,...,1.0,53.913758,67.830253,13.916496,15.737808,2.92732,2,<NA>,2,2
54,3,1,2009-01-01,NaN,2.274497e+06,7.626184e+03,NaN,NaN,NaN,NaN,...,1.0,54.915811,67.830253,12.914442,16.739862,2.92732,2,<NA>,2,2
55,3,1,2010-01-01,NaN,4.481317e+06,4.298272e+04,NaN,NaN,NaN,NaN,...,1.0,55.915127,67.830253,11.915127,17.739177,2.92732,2,<NA>,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
415169,60926,1C,2019-01-01,NaN,NaN,0.000000e+00,NaN,NaN,NaN,NaN,...,1.0,-0.328542,2.587269,2.915811,-15.181727,NaN,454,<NA>,454,ETR
415170,60926,1C,2020-01-01,NaN,NaN,0.000000e+00,NaN,NaN,NaN,NaN,...,1.0,0.670773,2.587269,1.916496,-14.182411,NaN,454,<NA>,454,ETR
415173,60927,1A,2020-01-01,NaN,NaN,1.202763e+07,NaN,NaN,NaN,NaN,...,1.0,-0.164271,1.752225,1.916496,-15.017456,NaN,454,<NA>,454,ETR
415176,60927,1B,2020-01-01,NaN,NaN,1.202763e+07,NaN,NaN,NaN,NaN,...,1.0,-0.164271,1.752225,1.916496,-15.017456,NaN,454,<NA>,454,ETR
415179,60927,1C,2020-01-01,NaN,NaN,0.000000e+00,NaN,NaN,NaN,NaN,...,1.0,-0.164271,1.752225,1.916496,-15.017456,NaN,454,<NA>,454,ETR

think about how to miss filling in missing years

In [183]:
df

,plant_id_eia,generator_id,report_year,needed_years,missing_years,years_to_fill_in
0,3,3,"[2006, 2007, 2008, 2009, 2010, 2011, 2012, 201...","[2006, 2007, 2008, 2009, 2010, 2011, 2012, 201...","{2016, 2017, 2018, 2019, 2015}","[2016, 2017, 2018, 2019, 2015]"
1,3,A1CT2,"[2009, 2010, 2011, 2012, 2013, 2014, 2015, 201...","[2006, 2007, 2008, 2009, 2010, 2011, 2012, 201...","{2008, 2006, 2007}","[2008, 2006, 2007]"
2,8,10,"[2006, 2007, 2008, 2009, 2010, 2011, 2012, 201...","[2006, 2007, 2008, 2009, 2010, 2011, 2012, 201...",{2019},[2019]
3,8,6,"[2006, 2007, 2008, 2009, 2010, 2011, 2012, 201...","[2006, 2007, 2008, 2009, 2010, 2011, 2012, 201...","{2016, 2017, 2018, 2019, 2015}","[2016, 2017, 2018, 2019, 2015]"
4,8,7,"[2006, 2007, 2008, 2009, 2010, 2011, 2012, 201...","[2006, 2007, 2008, 2009, 2010, 2011, 2012, 201...","{2016, 2017, 2018, 2019, 2015}","[2016, 2017, 2018, 2019, 2015]"
...,...,...,...,...,...,...
2153,60926,1B,"[2019, 2020]","[2006, 2007, 2008, 2009, 2010, 2011, 2012, 201...","{2016, 2017, 2018, 2006, 2007, 2008, 2009, 201...","[2016, 2017, 2018, 2006, 2007, 2008, 2009, 201..."
2154,60926,1C,"[2019, 2020]","[2006, 2007, 2008, 2009, 2010, 2011, 2012, 201...","{2016, 2017, 2018, 2006, 2007, 2008, 2009, 201...","[2016, 2017, 2018, 2006, 2007, 2008, 2009, 201..."
2155,60927,1A,[2020],"[2006, 2007, 2008, 2009, 2010, 2011, 2012, 201...","{2016, 2017, 2018, 2019, 2006, 2007, 2008, 200...","[2016, 2017, 2018, 2019, 2006, 2007, 2008, 200..."
2156,60927,1B,[2020],"[2006, 2007, 2008, 2009, 2010, 2011, 2012, 201...","{2016, 2017, 2018, 2019, 2006, 2007, 2008, 200...","[2016, 2017, 2018, 2019, 2006, 2007, 2008, 200..."
2157,60927,1C,[2020],"[2006, 2007, 2008, 2009, 2010, 2011, 2012, 201...","{2016, 2017, 2018, 2019, 2006, 2007, 2008, 200...","[2016, 2017, 2018, 2019, 2006, 2007, 2008, 200..."

In [195]:
split = pd.DataFrame([pd.Series(x) for x in df.years_to_fill_in])
split.columns = ['year_{}'.format(x+1) for x in split.columns]

df = pd.concat([df,split],axis=1)

/var/folders/lw/gjwq5pd52hb01x363x3vyw6c0000gp/T/ipykernel_66186/1588057529.py:1: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  split = pd.DataFrame([pd.Series(x) for x in df.years_to_fill_in])

In [233]:
missing_years_clean = df.melt(
                id_vars=["plant_id_eia", "generator_id"],
                value_vars=[
                    "year_1",
                    "year_2",
                    "year_3",
                    "year_4",
                    "year_5",
                    "year_6",
                    "year_7",
                    "year_8",
                    "year_9",
                    "year_10",
                    "year_11",
                    "year_12",
                    "year_13",
                    "year_14",
                ],
                value_name="year",
            ).query("year.notnull()").assign(year=lambda x: x["year"].astype("Int64"),
fuss = lambda x: 'missing_years')

In [215]:
(df.melt(id_vars=['plant_id_eia','generator_id'],value_vars=['year_1', 'year_2', 'year_3',
       'year_4', 'year_5', 'year_6', 'year_7', 'year_8', 'year_9', 'year_10',
       'year_11', 'year_12', 'year_13', 'year_14'],value_name='year').assign(year = lambda x: x['year'].astype('Int64')
       ).query('year.notnull()')
       .merge(self.xwalk[['plant_id_eia','generator_id','prime_mover','fuel_group']],on=['plant_id_eia','generator_id'],how='left',validate='m:m',indicator=True)
)

/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:258: UserWarning: This crosswalk is not safe, it may have `pf_subplants with multiple primes. Use `safe_xwalk` instead.
  return self._xwalk.grand_crosswalk

,plant_id_eia,generator_id,variable,year,prime_mover,fuel_group,_merge
0,3,3,year_1,2016,ST,coal,both
1,3,3,year_1,2016,ST,natural_gas,both
2,3,A1CT2,year_1,2008,CC,natural_gas,both
3,8,10,year_1,2019,ST,coal,both
4,8,6,year_1,2016,ST,coal,both
...,...,...,...,...,...,...,...
23201,57185,U005,year_14,2015,CC,natural_gas,both
23202,57185,U006,year_14,2015,CC,natural_gas,both
23203,60927,1A,year_14,2015,CC,natural_gas,both
23204,60927,1B,year_14,2015,CC,natural_gas,both
23205,60927,1C,year_14,2015,CC,natural_gas,both

In [218]:
self.get_gf923_by_generator(counterfactuals=True)

,report_date,plant_id_eia,generator_id,prime_mover_code,energy_source_code,energy_source_code_num,net_mwh,mmbtu,fuel_consumed_for_electricity_mmbtu,fuel_group
1222342,2001-01-01,2,1,HY,WAT,energy_source_code_1,18918.000000,195479.690000,195479.690000,renew
1222606,2001-01-01,3,1,ST,BIT,energy_source_code_1,6371.709286,61866.342266,61866.342266,coal
1222611,2001-01-01,3,1,ST,NG,energy_source_code_2,NaN,NaN,NaN,natural_gas
1222607,2001-01-01,3,2,ST,BIT,energy_source_code_1,6371.709286,61866.342266,61866.342266,coal
1222612,2001-01-01,3,2,ST,NG,energy_source_code_2,NaN,NaN,NaN,natural_gas
...,...,...,...,...,...,...,...,...,...,...
6808425,2022-12-01,65824,VSPRC,PV,SUN,energy_source_code_1,NaN,NaN,NaN,renew
6808437,2022-12-01,65831,LNSTR,BA,MWH,energy_source_code_1,NaN,NaN,NaN,other
6808461,2022-12-01,65836,TOYAH,BA,MWH,energy_source_code_1,NaN,NaN,NaN,other
6808485,2022-12-01,65838,HOEFS,BA,MWH,energy_source_code_1,NaN,NaN,NaN,other
6808497,2022-12-01,65859,GEN1,PV,SUN,energy_source_code_1,NaN,NaN,NaN,renew

In [219]:
self.get_gf923_by_generator()

,plant_id_eia,generator_id,report_date,SG_mmbtu,biofuel_mmbtu,coal_mmbtu,natural_gas_mmbtu,nuclear_mmbtu,other_mmbtu,other_gas_mmbtu,...,SG_net_mwh,biofuel_net_mwh,coal_net_mwh,natural_gas_net_mwh,nuclear_net_mwh,other_net_mwh,other_gas_net_mwh,petroleum_net_mwh,petroleum_coke_net_mwh,renew_net_mwh
0,1,1,2019-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,827.4,NaN,NaN
1,1,1,2020-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN
2,1,1,2021-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,818.7,NaN,NaN
3,1,1,2022-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN
4,1,2,2019-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,827.4,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
432947,65836,TOYAH,2021-01-01,NaN,NaN,NaN,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
432948,65836,TOYAH,2022-01-01,NaN,NaN,NaN,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
432949,65838,HOEFS,2021-01-01,NaN,NaN,NaN,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
432950,65838,HOEFS,2022-01-01,NaN,NaN,NaN,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
432951,65859,GEN1,2022-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0

In [222]:
self.get_exa_by_generator()

/opt/anaconda3/envs/gencost/lib/python3.11/site-packages/etoolbox/utils/pudl_helpers.py:146: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[date_mask, date_col] = pd.to_datetime(
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:258: UserWarning: This crosswalk is not safe, it may have `pf_subplants with multiple primes. Use `safe_xwalk` instead.
  return self._xwalk.grand_crosswalk
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:199: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  np.repeat(df[old_cols].sum(axis=1)[:, np.newaxis], len(old_cols), 1) != 0.0,
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:204: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  df[old_cols].isna().sum(axis=1)[:, np.newaxis], len(old_cols), 1
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:213: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  df[to_allocate][:, np.newaxis],

,plant_id_eia,generator_id,report_date,biofuel_mmbtu,coal_mmbtu,natural_gas_mmbtu,nuclear_mmbtu,other_mmbtu,other_gas_mmbtu,petroleum_mmbtu,...,gross_generation_mwh,cems_923_merge,biofuel_gross_mwh,coal_gross_mwh,natural_gas_gross_mwh,other_gross_mwh,other_gas_gross_mwh,petroleum_gross_mwh,petroleum_coke_gross_mwh,renew_gross_mwh
0,1,1,2019-01-01,NaN,NaN,NaN,NaN,NaN,NaN,8680.2,...,NaN,left_only,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1,2020-01-01,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,left_only,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,1,2021-01-01,NaN,NaN,NaN,NaN,NaN,NaN,10647.0,...,NaN,left_only,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,1,2022-01-01,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,left_only,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,2,2019-01-01,NaN,NaN,NaN,NaN,NaN,NaN,8680.2,...,NaN,left_only,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
432947,65836,TOYAH,2021-01-01,NaN,NaN,NaN,NaN,0.0,NaN,NaN,...,NaN,left_only,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
432948,65836,TOYAH,2022-01-01,NaN,NaN,NaN,NaN,0.0,NaN,NaN,...,NaN,left_only,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
432949,65838,HOEFS,2021-01-01,NaN,NaN,NaN,NaN,0.0,NaN,NaN,...,NaN,left_only,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
432950,65838,HOEFS,2022-01-01,NaN,NaN,NaN,NaN,0.0,NaN,NaN,...,NaN,left_only,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
432951,65859,GEN1,2022-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,left_only,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [220]:
self.get_cems_by_generator()

/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:258: UserWarning: This crosswalk is not safe, it may have `pf_subplants with multiple primes. Use `safe_xwalk` instead.
  return self._xwalk.grand_crosswalk

,plant_id_eia,generator_id,report_date,generator_starts,fuel_starts,gross_generation_mwh
51,3,1,2006-01-01,7.0,7.0,1123980.0
52,3,1,2007-01-01,13.0,13.0,1028301.0
53,3,1,2008-01-01,15.0,15.0,928095.0
54,3,1,2009-01-01,44.0,44.0,243753.0
55,3,1,2010-01-01,14.0,14.0,469201.0
...,...,...,...,...,...,...
415104,60926,1B,2020-01-01,36.0,37.0,2997852.5
415105,60926,1C,2020-01-01,36.0,37.0,0.0
415112,60927,1A,2020-01-01,51.0,54.0,1663118.5
415113,60927,1B,2020-01-01,51.0,54.0,1663118.5
415114,60927,1C,2020-01-01,51.0,54.0,0.0

In [232]:
self.find_missing_data()

/opt/anaconda3/envs/gencost/lib/python3.11/site-packages/etoolbox/utils/pudl_helpers.py:146: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[date_mask, date_col] = pd.to_datetime(
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:258: UserWarning: This crosswalk is not safe, it may have `pf_subplants with multiple primes. Use `safe_xwalk` instead.
  return self._xwalk.grand_crosswalk
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:199: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  np.repeat(df[old_cols].sum(axis=1)[:, np.newaxis], len(old_cols), 1) != 0.0,
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:204: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  df[old_cols].isna().sum(axis=1)[:, np.newaxis], len(old_cols), 1
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:213: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  df[to_allocate][:, np.newaxis],
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:2301: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  x["needed_years"].map(set) - x["report_year"].map(set)

,plant_id_eia,generator_id,report_date,mmbtu,fuel_consumption,percent_of_gen,single_fuel,single_fuel_present,n_fuels
33659,7527,2,2012-01-01,biofuel_mmbtu,323518.0,0.998774,1,1,2
40048,10333,GEN1,2013-01-01,biofuel_mmbtu,450933.0,0.970638,1,1,2
40049,10333,GEN1,2014-01-01,biofuel_mmbtu,1518064.0,0.993868,1,1,2
40050,10333,GEN1,2015-01-01,biofuel_mmbtu,5733380.0,0.983817,1,1,2
40051,10333,GEN1,2016-01-01,biofuel_mmbtu,5104054.0,0.994192,1,1,2
...,...,...,...,...,...,...,...,...,...
545459,6043,8,2016-01-01,renew_mmbtu,695179.0,1.000000,1,1,2
545460,6043,8,2017-01-01,renew_mmbtu,199074.0,1.000000,1,1,2
545461,6043,8,2018-01-01,renew_mmbtu,468365.0,1.000000,1,1,2
545462,6043,8,2019-01-01,renew_mmbtu,249054.0,1.000000,1,1,2
545463,6043,8,2020-01-01,renew_mmbtu,260503.0,1.000000,1,1,2

boneyard 

what we took off year exploded df missing years 

 .merge(
                self.xwalk[
                    ["plant_id_eia", "generator_id", "prime_mover", "fuel_group"]
                ],
                on=["plant_id_eia", "generator_id"],
                how="left",
                validate="m:m",
                indicator=True,
            )
        )

In [234]:
missing_years_clean

       plant_id_eia generator_id variable  year           fuss
0                 3            3   year_1  2016  missing_years
1                 3        A1CT2   year_1  2008  missing_years
2                 8           10   year_1  2019  missing_years
3                 8            6   year_1  2016  missing_years
4                 8            7   year_1  2016  missing_years
...             ...          ...      ...   ...            ...
30013         57185         U005  year_14  2015  missing_years
30014         57185         U006  year_14  2015  missing_years
30209         60927           1A  year_14  2015  missing_years
30210         60927           1B  year_14  2015  missing_years
30211         60927           1C  year_14  2015  missing_years

[12173 rows x 5 columns]

In [239]:
sorted = test.sort_values(by=['plant_id_eia','generator_id','report_date'],ascending=True)

In [241]:
sorted['fuel'] = sorted.groupby(['plant_id_eia','generator_id'])['fuel_mmbtu'].transform('last')

In [242]:
sorted.query('fuel !=')

,plant_id_eia,generator_id,report_date,fuel_mmbtu,fuel_consumption,percent_of_gen,single_fuel,single_fuel_present,n_fuels,fuel
64652,3,1,2006-01-01,coal_mmbtu,1.008871e+07,0.997083,1,1,2,natural_gas_mmbtu
64653,3,1,2007-01-01,coal_mmbtu,9.807031e+06,1.000000,1,1,2,natural_gas_mmbtu
64654,3,1,2008-01-01,coal_mmbtu,8.176078e+06,1.000000,1,1,2,natural_gas_mmbtu
64655,3,1,2009-01-01,coal_mmbtu,2.274497e+06,0.996658,1,1,2,natural_gas_mmbtu
64656,3,1,2010-01-01,coal_mmbtu,4.481317e+06,0.990500,1,1,2,natural_gas_mmbtu
...,...,...,...,...,...,...,...,...,...,...
186473,55505,BR2,2016-01-01,natural_gas_mmbtu,1.090730e+05,0.990902,1,1,2,natural_gas_mmbtu
186474,55505,BR2,2017-01-01,natural_gas_mmbtu,7.324400e+04,0.990386,1,1,2,natural_gas_mmbtu
186475,55505,BR2,2018-01-01,natural_gas_mmbtu,2.330545e+05,0.992475,1,1,2,natural_gas_mmbtu
186476,55505,BR2,2019-01-01,natural_gas_mmbtu,5.666600e+05,0.991677,1,1,2,natural_gas_mmbtu
186477,55505,BR2,2020-01-01,natural_gas_mmbtu,4.533095e+05,0.996002,1,1,2,natural_gas_mmbtu

In [411]:
df = self.find_missing_data()

/opt/anaconda3/envs/gencost/lib/python3.11/site-packages/etoolbox/utils/pudl_helpers.py:146: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[date_mask, date_col] = pd.to_datetime(
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:258: UserWarning: This crosswalk is not safe, it may have `pf_subplants with multiple primes. Use `safe_xwalk` instead.
  return self._xwalk.grand_crosswalk
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:199: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  np.repeat(df[old_cols].sum(axis=1)[:, np.newaxis], len(old_cols), 1) != 0.0,
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:204: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  df[old_cols].isna().sum(axis=1)[:, np.newaxis], len(old_cols), 1
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:213: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  df[to_allocate][:, np.newaxis],
/opt/anaconda3/envs/gencost/lib/python3.11/site-packages/etoolbox/utils/pudl_helpers.py:146: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[date_mask, date_col] = pd.to_datetime(
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:2364: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  split = pd.DataFrame([pd.Series(x) for x in missing_years.years_to_fill_in])

In [410]:
df

,plant_id_eia,generator_id,variable,year,fuss,report_date,prime_mover_code,fuel_group,prime_mover
0,3,3,year_1,2016,missing_years,NaT,<NA>,<NA>,<NA>
1,3,A1CT2,year_1,2008,missing_years,2019-01-01,CT,natural_gas,CC
2,8,10,year_1,2019,missing_years,2019-01-01,ST,coal,ST
3,8,10,year_1,2019,missing_years,2019-01-01,ST,petroleum,ST
4,8,6,year_1,2016,missing_years,NaT,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...
13617,57185,U005,year_14,2015,missing_years,NaT,<NA>,<NA>,<NA>
13618,57185,U006,year_14,2015,missing_years,NaT,<NA>,<NA>,<NA>
13619,60927,1A,year_14,2015,missing_years,NaT,<NA>,<NA>,<NA>
13620,60927,1B,year_14,2015,missing_years,NaT,<NA>,<NA>,<NA>
13621,60927,1C,year_14,2015,missing_years,NaT,<NA>,<NA>,<NA>

In [415]:
df_gf23 = self.get_gf923_by_generator(counterfactuals=True)

In [417]:
df_gf23.query('plant_id_eia == 8 & generator_id == "10"',engine='python')

,report_date,plant_id_eia,generator_id,prime_mover_code,energy_source_code,energy_source_code_num,net_mwh,mmbtu,fuel_consumed_for_electricity_mmbtu,fuel_group
1225634,2001-01-01,8,10,ST,BIT,energy_source_code_1,393568.717160,3.847835e+06,3.847835e+06,coal
1225639,2001-01-01,8,10,ST,WC,energy_source_code_2,NaN,NaN,NaN,coal
1225640,2001-02-01,8,10,ST,BIT,energy_source_code_1,326051.624197,3.139236e+06,3.139236e+06,coal
1225645,2001-02-01,8,10,ST,WC,energy_source_code_2,NaN,NaN,NaN,coal
1225646,2001-03-01,8,10,ST,BIT,energy_source_code_1,254601.388579,2.555122e+06,2.555122e+06,coal
...,...,...,...,...,...,...,...,...,...,...
1186530,2019-03-01,8,10,ST,DFO,energy_source_code_2,-2.785870,0.000000e+00,0.000000e+00,petroleum
1186533,2019-04-01,8,10,ST,BIT,energy_source_code_1,-510.315216,0.000000e+00,0.000000e+00,coal
1186536,2019-04-01,8,10,ST,DFO,energy_source_code_2,-0.684784,0.000000e+00,0.000000e+00,petroleum
1186539,2019-05-01,8,10,ST,BIT,energy_source_code_1,NaN,0.000000e+00,0.000000e+00,coal
1186542,2019-05-01,8,10,ST,DFO,energy_source_code_2,NaN,0.000000e+00,0.000000e+00,petroleum

In [418]:
cems = self.get_cems_by_generator()

/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:258: UserWarning: This crosswalk is not safe, it may have `pf_subplants with multiple primes. Use `safe_xwalk` instead.
  return self._xwalk.grand_crosswalk

In [421]:
cems.query('plant_id_eia == 8 & generator_id == "10"',engine='python')

,plant_id_eia,generator_id,report_date,generator_starts,fuel_starts,gross_generation_mwh
389,8,10,2006-01-01,13.0,9.0,5502690.0
390,8,10,2007-01-01,13.0,13.0,4476716.0
391,8,10,2008-01-01,33.0,33.0,4767016.0
392,8,10,2009-01-01,41.0,41.0,4212659.0
393,8,10,2010-01-01,5.0,5.0,5078736.0
394,8,10,2011-01-01,17.0,17.0,3588795.0
395,8,10,2012-01-01,14.0,14.0,2374948.0
396,8,10,2013-01-01,13.0,13.0,2861300.0
397,8,10,2014-01-01,16.0,16.0,4560601.0
398,8,10,2015-01-01,15.0,15.0,4178165.0
399,8,10,2016-01-01,20.0,20.0,4467945.0
400,8,10,2017-01-01,23.0,23.0,3816740.0
401,8,10,2018-01-01,15.0,15.0,4655680.0
402,8,10,2019-01-01,3.0,3.0,456210.0

In [422]:
df860 = self.get_860_by_x(subplant_id_col='generator_id')

/opt/anaconda3/envs/gencost/lib/python3.11/site-packages/etoolbox/utils/pudl_helpers.py:146: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[date_mask, date_col] = pd.to_datetime(

In [423]:
df860.query('plant_id_eia == 8 & generator_id == "10"',engine='python')

,utility_id_eia,balancing_authority_code_eia,state,plant_id_eia,generator_id,report_date,capacity_mw,prime_mover,associated_combined_heat_power,duct_burners,...,ultrasupercritical_tech,age_in_report_year,age_in_current_year,age_of_observation,age_relative_to_prime_avg,pollution_control_costs_per_kw,respondent_id,respondent_id_purchaser,final_respondent_id,final_ba_code
16,195,SOCO,AL,8,10,2001-01-01,788.8,ST,1,1,...,1,28.251882,49.166324,20.914442,-9.924067,NaN,2,<NA>,2,2
15875,195,SOCO,AL,8,10,2002-01-01,788.8,ST,1,1,...,1,29.251198,49.166324,19.915127,-8.924752,NaN,2,<NA>,2,2
32287,195,SOCO,AL,8,10,2003-01-01,788.8,ST,1,1,...,1,30.250513,49.166324,18.915811,-7.925436,NaN,2,<NA>,2,2
49043,195,SOCO,AL,8,10,2004-01-01,788.8,ST,1,1,...,1,31.249829,49.166324,17.916496,-6.926121,NaN,2,<NA>,2,2
65813,195,SOCO,AL,8,10,2005-01-01,788.8,ST,1,1,...,1,32.251882,49.166324,16.914442,-5.924067,NaN,2,<NA>,2,2
82620,195,SOCO,AL,8,10,2006-01-01,788.8,ST,1,1,...,1,33.251198,49.166324,15.915127,-4.924752,NaN,2,<NA>,2,2
99544,195,SOCO,AL,8,10,2007-01-01,788.8,ST,1,1,...,1,34.250513,49.166324,14.915811,-3.925436,NaN,2,<NA>,2,2
116885,195,SOCO,AL,8,10,2008-01-01,788.8,ST,1,1,...,1,35.249829,49.166324,13.916496,-2.926121,NaN,2,<NA>,2,2
134544,195,SOCO,AL,8,10,2009-01-01,788.8,ST,1,1,...,1,36.251882,49.166324,12.914442,-1.924067,NaN,2,<NA>,2,2
152420,195,SOCO,AL,8,10,2010-01-01,788.8,ST,1,1,...,1,37.251198,49.166324,11.915127,-0.924752,NaN,2,<NA>,2,2
170570,195,SOCO,AL,8,10,2011-01-01,788.8,ST,1,1,...,1,38.250513,49.166324,10.915811,0.074564,NaN,2,<NA>,2,2
189100,195,SOCO,AL,8,10,2012-01-01,788.8,ST,1,1,...,1,39.249829,49.166324,9.916496,1.073879,NaN,2,<NA>,2,2
208123,195,SOCO,AL,8,10,2013-01-01,788.8,ST,1,1,...,1,40.251882,49.166324,8.914442,2.075933,NaN,2,<NA>,2,2
227365,195,SOCO,AL,8,10,2014-01-01,788.8,ST,1,1,...,1,41.251198,49.166324,7.915127,3.075248,NaN,2,<NA>,2,2
247108,195,SOCO,AL,8,10,2015-01-01,788.8,ST,1,1,...,1,42.250513,49.166324,6.915811,4.074564,NaN,2,<NA>,2,2
267175,195,SOCO,AL,8,10,2016-01-01,788.8,ST,1,1,...,1,43.249829,49.166324,5.916496,5.073879,NaN,2,<NA>,2,2
287898,195,SOCO,AL,8,10,2017-01-01,788.8,ST,1,1,...,1,44.251882,49.166324,4.914442,6.075933,NaN,2,<NA>,2,2
309334,195,SOCO,AL,8,10,2018-01-01,788.8,ST,1,1,...,1,45.251198,49.166324,3.915127,7.075248,NaN,2,<NA>,2,2

In [408]:
test = (hist.groupby(['plant_id_eia','generator_id',pd.Grouper(key="report_date", freq="YS"),'prime_mover_code','fuel_group']).agg({'mmbtu':'sum','net_mwh':'sum'})
.reset_index()
.query('report_date <= "2020-01-01"')
.query('mmbtu > 0 & net_mwh > 0')
.sort_values(by=['plant_id_eia','generator_id','report_date'],ascending=True)
.assign(prime_fuel = lambda x: x['prime_mover_code'] + "_" + x['fuel_group'],
year= lambda x: (x['report_date'].dt.year))
#year = lambda x: str(x['report_year']))
.groupby(['plant_id_eia','generator_id','year'])['prime_fuel'].agg(list)
.reset_index()
.pivot(index=['plant_id_eia','generator_id'],
columns=['year'],values=['prime_fuel'])
.rename_axis(None, axis=1).reset_index(drop=True)
)

#aggfunc=lambda x:" ".join(str(v) for v in x))
#aggfunc='first')



#test.columns = map("_".join, test.columns)
#test = test.loc[:, test.sum(axis=0) != 0].reset_index()
#[['plant_id_eia','generator_id','report_date','prime_mover_code','fuel_group']])

TypeError: Must pass list-like as `names`.

In [407]:
test.query('plant_id_eia == 3',engine='python')

     plant_id_eia generator_id  year                 prime_fuel
24              3            1  2001                  [ST_coal]
25              3            1  2002                  [ST_coal]
26              3            1  2003  [ST_coal, ST_natural_gas]
27              3            1  2004  [ST_coal, ST_natural_gas]
28              3            1  2005  [ST_coal, ST_natural_gas]
..            ...          ...   ...                        ...
219             3         A2ST  2016           [CA_natural_gas]
220             3         A2ST  2017           [CA_natural_gas]
221             3         A2ST  2018           [CA_natural_gas]
222             3         A2ST  2019           [CA_natural_gas]
223             3         A2ST  2020           [CA_natural_gas]

[200 rows x 4 columns]

In [331]:
missing_years_clean

       plant_id_eia generator_id variable  year           fuss
0                 3            3   year_1  2016  missing_years
1                 3        A1CT2   year_1  2008  missing_years
2                 8           10   year_1  2019  missing_years
3                 8            6   year_1  2016  missing_years
4                 8            7   year_1  2016  missing_years
...             ...          ...      ...   ...            ...
30013         57185         U005  year_14  2015  missing_years
30014         57185         U006  year_14  2015  missing_years
30209         60927           1A  year_14  2015  missing_years
30210         60927           1B  year_14  2015  missing_years
30211         60927           1C  year_14  2015  missing_years

[12173 rows x 5 columns]

In [300]:
test.query('plant_id_eia == 3 & generator_id == "1"',engine='python')

,plant_id_eia,generator_id,report_date,prime_mover_code,fuel_group,mmbtu,net_mwh,n_fuels
77,3,1,2020-01-01,ST,natural_gas,2.861272e+04,1554.454351,1
72,3,1,2015-01-01,ST,natural_gas,5.947680e+04,51.994385,1
73,3,1,2016-01-01,ST,natural_gas,1.618925e+05,233.870694,1
74,3,1,2017-01-01,ST,natural_gas,1.966532e+05,1150.019335,1
70,3,1,2014-01-01,ST,coal,2.479372e+05,18975.754113,2
68,3,1,2013-01-01,ST,coal,3.448870e+05,30367.124070,2
75,3,1,2018-01-01,ST,natural_gas,3.908812e+05,2312.719002,1
76,3,1,2019-01-01,ST,natural_gas,4.135949e+05,1952.538969,1
66,3,1,2012-01-01,ST,coal,1.428320e+06,148021.028081,2
60,3,1,2009-01-01,ST,coal,2.274497e+06,216274.279645,2
64,3,1,2011-01-01,ST,coal,3.154614e+06,300067.984077,2
62,3,1,2010-01-01,ST,coal,4.481317e+06,428843.516663,2
59,3,1,2008-01-01,ST,coal,8.176078e+06,865288.470536,1
58,3,1,2007-01-01,ST,coal,9.807031e+06,954656.813326,1
56,3,1,2006-01-01,ST,coal,1.008871e+07,964082.899927,2

In [290]:
df = self.get_exa_by_generator()

/opt/anaconda3/envs/gencost/lib/python3.11/site-packages/etoolbox/utils/pudl_helpers.py:146: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[date_mask, date_col] = pd.to_datetime(
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:258: UserWarning: This crosswalk is not safe, it may have `pf_subplants with multiple primes. Use `safe_xwalk` instead.
  return self._xwalk.grand_crosswalk
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:199: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  np.repeat(df[old_cols].sum(axis=1)[:, np.newaxis], len(old_cols), 1) != 0.0,
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:204: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  df[old_cols].isna().sum(axis=1)[:, np.newaxis], len(old_cols), 1
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:213: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  df[to_allocate][:, np.newaxis],
/opt/anaconda3/envs/gencost/lib/python3.11/site-packages/etoolbox/utils/pudl_helpers.py:146: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[date_mask, date_col] = pd.to_datetime(

In [293]:
df.to_parquet("historic_data_gen_level_updated_0523.parquet")

In [291]:
df.columns

Index(['plant_id_eia', 'generator_id', 'report_date', 'biofuel_mmbtu',
       'coal_mmbtu', 'natural_gas_mmbtu', 'nuclear_mmbtu', 'other_mmbtu',
       'other_gas_mmbtu', 'petroleum_mmbtu', 'petroleum_coke_mmbtu',
       'renew_mmbtu', 'biofuel_net_mwh', 'coal_net_mwh', 'natural_gas_net_mwh',
       'nuclear_net_mwh', 'other_net_mwh', 'other_gas_net_mwh',
       'petroleum_net_mwh', 'petroleum_coke_net_mwh', 'renew_net_mwh',
       'generator_starts', 'fuel_starts', 'gross_generation_mwh',
       'biofuel_gross_mwh', 'coal_gross_mwh', 'natural_gas_gross_mwh',
       'other_gross_mwh', 'other_gas_gross_mwh', 'petroleum_gross_mwh',
       'petroleum_coke_gross_mwh', 'renew_gross_mwh', 'utility_id_eia',
       'balancing_authority_code_eia', 'state', 'capacity_mw', 'prime_mover',
       'associated_combined_heat_power', 'duct_burners',
       'bypass_heat_recovery', 'solid_fuel_gasification', 'carbon_capture',
       'fluidized_bed_tech', 'pulverized_coal_tech', 'stoker_tech',
       'other_combustion_tech', 'subcritical_tech', 'supercritical_tech',
       'ultrasupercritical_tech', 'age_in_report_year', 'age_in_current_year',
       'age_of_observation', 'age_relative_to_prime_avg',
       'pollution_control_costs_per_kw', 'respondent_id',
       'respondent_id_purchaser', 'final_respondent_id', 'final_ba_code',
       'wage_scale', 'age_of_observation_secular_adj'],
      dtype='object')

In [284]:
df860 = self.pudl_tabl.gens_eia860()
df860.columns.to_list()

['report_date',
 'plant_id_eia',
 'plant_id_pudl',
 'plant_name_eia',
 'utility_id_eia',
 'utility_id_pudl',
 'utility_name_eia',
 'generator_id',
 'associated_combined_heat_power',
 'bga_source',
 'bypass_heat_recovery',
 'capacity_mw',
 'carbon_capture',
 'city',
 'cofire_fuels',
 'county',
 'current_planned_generator_operating_date',
 'data_maturity',
 'deliver_power_transgrid',
 'distributed_generation',
 'duct_burners',
 'energy_source_1_transport_1',
 'energy_source_1_transport_2',
 'energy_source_1_transport_3',
 'energy_source_2_transport_1',
 'energy_source_2_transport_2',
 'energy_source_2_transport_3',
 'energy_source_code_1',
 'energy_source_code_2',
 'energy_source_code_3',
 'energy_source_code_4',
 'energy_source_code_5',
 'energy_source_code_6',
 'energy_storage_capacity_mwh',
 'ferc_qualifying_facility',
 'fluidized_bed_tech',
 'fuel_type_code_pudl',
 'fuel_type_count',
 'generator_operating_date',
 'generator_retirement_date',
 'latitude',
 'longitude',
 'minimum_load_mw',
 'multiple_fuels',
 'nameplate_power_factor',
 'net_capacity_mwdc',
 'operating_switch',
 'operational_status',
 'operational_status_code',
 'original_planned_generator_operating_date',
 'other_combustion_tech',
 'other_modifications_date',
 'other_planned_modifications',
 'owned_by_non_utility',
 'ownership_code',
 'planned_derate_date',
 'planned_energy_source_code_1',
 'planned_generator_retirement_date',
 'planned_modifications',
 'planned_net_summer_capacity_derate_mw',
 'planned_net_summer_capacity_uprate_mw',
 'planned_net_winter_capacity_derate_mw',
 'planned_net_winter_capacity_uprate_mw',
 'planned_new_capacity_mw',
 'planned_new_prime_mover_code',
 'planned_repower_date',
 'planned_uprate_date',
 'previously_canceled',
 'prime_mover_code',
 'pulverized_coal_tech',
 'reactive_power_output_mvar',
 'rto_iso_lmp_node_id',
 'rto_iso_location_wholesale_reporting_id',
 'solid_fuel_gasification',
 'startup_source_code_1',
 'startup_source_code_2',
 'startup_source_code_3',
 'startup_source_code_4',
 'state',
 'stoker_tech',
 'street_address',
 'subcritical_tech',
 'summer_capacity_estimate',
 'summer_capacity_mw',
 'summer_estimated_capability_mw',
 'supercritical_tech',
 'switch_oil_gas',
 'syncronized_transmission_grid',
 'technology_description',
 'time_cold_shutdown_full_load_code',
 'timezone',
 'topping_bottoming_code',
 'turbines_inverters_hydrokinetics',
 'turbines_num',
 'ultrasupercritical_tech',
 'unit_id_pudl',
 'uprate_derate_completed_date',
 'uprate_derate_during_year',
 'winter_capacity_estimate',
 'winter_capacity_mw',
 'winter_estimated_capability_mw',
 'zip_code']

In [425]:
df_gf23

,report_date,plant_id_eia,generator_id,prime_mover_code,energy_source_code,energy_source_code_num,net_mwh,mmbtu,fuel_consumed_for_electricity_mmbtu,fuel_group
1222342,2001-01-01,2,1,HY,WAT,energy_source_code_1,18918.000000,195479.690000,195479.690000,renew
1222606,2001-01-01,3,1,ST,BIT,energy_source_code_1,6371.709286,61866.342266,61866.342266,coal
1222611,2001-01-01,3,1,ST,NG,energy_source_code_2,NaN,NaN,NaN,natural_gas
1222607,2001-01-01,3,2,ST,BIT,energy_source_code_1,6371.709286,61866.342266,61866.342266,coal
1222612,2001-01-01,3,2,ST,NG,energy_source_code_2,NaN,NaN,NaN,natural_gas
...,...,...,...,...,...,...,...,...,...,...
6808425,2022-12-01,65824,VSPRC,PV,SUN,energy_source_code_1,NaN,NaN,NaN,renew
6808437,2022-12-01,65831,LNSTR,BA,MWH,energy_source_code_1,NaN,NaN,NaN,other
6808461,2022-12-01,65836,TOYAH,BA,MWH,energy_source_code_1,NaN,NaN,NaN,other
6808485,2022-12-01,65838,HOEFS,BA,MWH,energy_source_code_1,NaN,NaN,NaN,other
6808497,2022-12-01,65859,GEN1,PV,SUN,energy_source_code_1,NaN,NaN,NaN,renew

In [426]:
missing_years_clean

       plant_id_eia generator_id variable  year           fuss
0                 3            3   year_1  2016  missing_years
1                 3        A1CT2   year_1  2008  missing_years
2                 8           10   year_1  2019  missing_years
3                 8            6   year_1  2016  missing_years
4                 8            7   year_1  2016  missing_years
...             ...          ...      ...   ...            ...
30013         57185         U005  year_14  2015  missing_years
30014         57185         U006  year_14  2015  missing_years
30209         60927           1A  year_14  2015  missing_years
30210         60927           1B  year_14  2015  missing_years
30211         60927           1C  year_14  2015  missing_years

[12173 rows x 5 columns]

In [ ]:
test = (hist.groupby(['plant_id_eia','generator_id',pd.Grouper(key="report_date", freq="YS"),'prime_mover_code','fuel_group']).agg({'mmbtu':'sum','net_mwh':'sum'})
.reset_index()
.query('report_date <= "2020-01-01"')
.query('mmbtu > 0 & net_mwh > 0')
.sort_values(by=['plant_id_eia','generator_id','report_date'],ascending=True)
.assign(prime_fuel = lambda x: x['prime_mover_code'] + "_" + x['fuel_group'],
year= lambda x: (x['report_date'].dt.year))
#year = lambda x: str(x['report_year']))
.groupby(['plant_id_eia','generator_id','year'])['prime_fuel'].agg(list)
.reset_index()
.pivot(index=['plant_id_eia','generator_id'],
columns=['year'],values=['prime_fuel'])
.rename_axis(None, axis=1).reset_index(drop=True)
)

#aggfunc=lambda x:" ".join(str(v) for

figure out which fuel and prime to fill in for

In [430]:
(df_gf23.groupby(['plant_id_eia','generator_id',pd.Grouper(key="report_date", freq="YS"),'prime_mover_code','fuel_group']).agg({'mmbtu':'sum','net_mwh':'sum'})
.reset_index()
.query('report_date <= "2020-01-01"')
.query('mmbtu > 0 & net_mwh > 0')
.assign(prime_fuel = lambda x: x['prime_mover_code'] + "_" + x['fuel_group'])
.pivot(index=['plant_id_eia','generator_id','report_date'],
columns=['mmbtu'],values=['prime_fuel'])
)

/var/folders/lw/gjwq5pd52hb01x363x3vyw6c0000gp/T/ipykernel_66186/4289876875.py:6: PerformanceWarning: The following operation may generate 2677088634 cells in the resulting pandas object.
  .pivot(index=['plant_id_eia','generator_id','report_date'],

trying to stuff figure out

In [3]:
missing_data = self.find_missing_data()

/opt/anaconda3/envs/gencost/lib/python3.11/site-packages/etoolbox/utils/pudl_helpers.py:146: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[date_mask, date_col] = pd.to_datetime(
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:258: UserWarning: This crosswalk is not safe, it may have `pf_subplants with multiple primes. Use `safe_xwalk` instead.
  return self._xwalk.grand_crosswalk
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:199: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  np.repeat(df[old_cols].sum(axis=1)[:, np.newaxis], len(old_cols), 1) != 0.0,
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:204: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  df[old_cols].isna().sum(axis=1)[:, np.newaxis], len(old_cols), 1
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:213: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  df[to_allocate][:, np.newaxis],
/opt/anaconda3/envs/gencost/lib/python3.11/site-packages/etoolbox/utils/pudl_helpers.py:146: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[date_mask, date_col] = pd.to_datetime(
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:2364: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  split = pd.DataFrame([pd.Series(x) for x in missing_years.years_to_fill_in])

In [9]:
missing_data

,plant_id_eia,generator_id,variable,year,fuss,report_date,prime_mover_code,fuel_group,prime_mover
0,3,3,year_1,2016,missing_years,NaT,<NA>,<NA>,<NA>
1,3,A1CT2,year_1,2008,missing_years,2020-01-01,CT,natural_gas,CC
2,8,10,year_1,2019,missing_years,NaT,<NA>,<NA>,<NA>
3,8,6,year_1,2016,missing_years,NaT,<NA>,<NA>,<NA>
4,8,7,year_1,2016,missing_years,NaT,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...
13381,57185,U005,year_14,2015,missing_years,2020-01-01,CT,natural_gas,CC
13382,57185,U006,year_14,2015,missing_years,2020-01-01,CT,natural_gas,CC
13383,60927,1A,year_14,2015,missing_years,2020-01-01,CT,natural_gas,CC
13384,60927,1B,year_14,2015,missing_years,2020-01-01,CT,natural_gas,CC
13385,60927,1C,year_14,2015,missing_years,NaT,<NA>,<NA>,<NA>

In [14]:
df_gf23 = self.get_gf923_by_generator(counterfactuals=True)

In [30]:
check = (df_gf23.groupby(['plant_id_eia','generator_id',pd.Grouper(key="report_date", freq="YS"),'prime_mover_code','fuel_group']).agg({'mmbtu':'sum','net_mwh':'sum'})
.reset_index()
.query('report_date <= "2020-01-01"')
.query('mmbtu > 0 & net_mwh > 0')
.sort_values(by=['plant_id_eia','generator_id','report_date','mmbtu'],ascending=True)
.drop_duplicates(subset=['plant_id_eia','generator_id'],keep='last')
)

In [33]:
check

,plant_id_eia,generator_id,report_date,prime_mover_code,fuel_group,mmbtu,net_mwh
0,1,1,2019-01-01,IC,petroleum,8680.200000,827.400000
4,1,2,2019-01-01,IC,petroleum,8680.200000,827.400000
8,1,3,2019-01-01,IC,petroleum,4822.333333,459.666667
12,1,5,2019-01-01,IC,petroleum,6751.266667,643.533333
16,1,WT1,2019-01-01,WT,renew,4550.500000,511.000000
...,...,...,...,...,...,...,...
550455,64723,50835,2020-01-01,PV,renew,208621.000000,23796.000000
550491,64748,CR18A,2020-01-01,FC,natural_gas,3637.000000,2335.000000
550496,64749,CR18B,2020-01-01,FC,natural_gas,17252.000000,2677.000000
550505,64753,FDX10,2020-01-01,FC,natural_gas,60594.000000,8670.000000
550509,64756,EQX05,2020-01-01,FC,natural_gas,64582.000000,9195.000000

test after

In [42]:
missing_data = self.find_missing_data()

/opt/anaconda3/envs/gencost/lib/python3.11/site-packages/etoolbox/utils/pudl_helpers.py:146: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[date_mask, date_col] = pd.to_datetime(
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:258: UserWarning: This crosswalk is not safe, it may have `pf_subplants with multiple primes. Use `safe_xwalk` instead.
  return self._xwalk.grand_crosswalk
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:199: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  np.repeat(df[old_cols].sum(axis=1)[:, np.newaxis], len(old_cols), 1) != 0.0,
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:204: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  df[old_cols].isna().sum(axis=1)[:, np.newaxis], len(old_cols), 1
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:213: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  df[to_allocate][:, np.newaxis],
/opt/anaconda3/envs/gencost/lib/python3.11/site-packages/etoolbox/utils/pudl_helpers.py:146: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[date_mask, date_col] = pd.to_datetime(
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:2373: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  "year_1",

In [84]:
missing_yrs = self.find_missing_data()

/opt/anaconda3/envs/gencost/lib/python3.11/site-packages/etoolbox/utils/pudl_helpers.py:146: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[date_mask, date_col] = pd.to_datetime(
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:258: UserWarning: This crosswalk is not safe, it may have `pf_subplants with multiple primes. Use `safe_xwalk` instead.
  return self._xwalk.grand_crosswalk
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:199: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  np.repeat(df[old_cols].sum(axis=1)[:, np.newaxis], len(old_cols), 1) != 0.0,
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:204: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  df[old_cols].isna().sum(axis=1)[:, np.newaxis], len(old_cols), 1
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:213: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  df[to_allocate][:, np.newaxis],
/opt/anaconda3/envs/gencost/lib/python3.11/site-packages/etoolbox/utils/pudl_helpers.py:146: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[date_mask, date_col] = pd.to_datetime(
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:258: UserWarning: This crosswalk is not safe, it may have `pf_subplants with multiple primes. Use `safe_xwalk` instead.
  return self._xwalk.grand_crosswalk
/opt/anaconda3/envs/gencost/lib/python3.11/site-packages/etoolbox/utils/pudl_helpers.py:146: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[date_mask, date_col] = pd.to_datetime(
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:2366: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  split = pd.DataFrame([pd.Series(x) for x in missing_years.years_to_fill_in])

In [85]:
missing_yrs

,plant_id_eia,generator_id,year,fuss,prime_mover,fuel_group,final_ba_code,age_in_current_year
0,3,3,2016,missing_years,ST,natural_gas,2,NaN
1,3,3,2016,missing_years,ST,natural_gas,2,NaN
2,3,3,2016,missing_years,ST,natural_gas,2,NaN
3,3,3,2016,missing_years,ST,natural_gas,2,NaN
4,3,3,2016,missing_years,ST,natural_gas,2,NaN
...,...,...,...,...,...,...,...,...
2392,55505,BR2,2016,fuel_switch,GT,petroleum,529,19.586585
2393,55505,BR2,2017,fuel_switch,GT,petroleum,529,19.586585
2394,55505,BR2,2018,fuel_switch,GT,petroleum,529,19.586585
2395,55505,BR2,2019,fuel_switch,GT,petroleum,529,19.586585
2396,55505,BR2,2020,fuel_switch,GT,petroleum,529,19.586585

In [91]:
missing = self.find_missing_data()

/opt/anaconda3/envs/gencost/lib/python3.11/site-packages/etoolbox/utils/pudl_helpers.py:146: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[date_mask, date_col] = pd.to_datetime(
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:258: UserWarning: This crosswalk is not safe, it may have `pf_subplants with multiple primes. Use `safe_xwalk` instead.
  return self._xwalk.grand_crosswalk
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:199: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  np.repeat(df[old_cols].sum(axis=1)[:, np.newaxis], len(old_cols), 1) != 0.0,
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:204: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  df[old_cols].isna().sum(axis=1)[:, np.newaxis], len(old_cols), 1
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:213: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  df[to_allocate][:, np.newaxis],
/opt/anaconda3/envs/gencost/lib/python3.11/site-packages/etoolbox/utils/pudl_helpers.py:146: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[date_mask, date_col] = pd.to_datetime(
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:258: UserWarning: This crosswalk is not safe, it may have `pf_subplants with multiple primes. Use `safe_xwalk` instead.
  return self._xwalk.grand_crosswalk
/opt/anaconda3/envs/gencost/lib/python3.11/site-packages/etoolbox/utils/pudl_helpers.py:146: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[date_mask, date_col] = pd.to_datetime(
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:2375: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  "year_1",

In [81]:
single_fuel_swtich

,plant_id_eia,generator_id,year,fuss,prime_mover,fuel_group,final_ba_code,age_in_current_year
0,7527,2,2012,fuel_switch,CC,natural_gas,CAISO,26.168378
1,10333,GEN1,2013,fuel_switch,ST,coal,FPC,33.500342
2,10333,GEN1,2014,fuel_switch,ST,coal,FPC,33.500342
3,10333,GEN1,2015,fuel_switch,ST,coal,FPC,33.500342
4,10333,GEN1,2016,fuel_switch,ST,coal,FPC,33.500342
...,...,...,...,...,...,...,...,...
2392,55505,BR2,2016,fuel_switch,GT,petroleum,529,19.586585
2393,55505,BR2,2017,fuel_switch,GT,petroleum,529,19.586585
2394,55505,BR2,2018,fuel_switch,GT,petroleum,529,19.586585
2395,55505,BR2,2019,fuel_switch,GT,petroleum,529,19.586585
2396,55505,BR2,2020,fuel_switch,GT,petroleum,529,19.586585

In [45]:
xwalk = self.xwalk

/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:258: UserWarning: This crosswalk is not safe, it may have `pf_subplants with multiple primes. Use `safe_xwalk` instead.
  return self._xwalk.grand_crosswalk

In [60]:
test = single_fuel_swtich.merge(xwalk,on=['plant_id_eia','generator_id','fuel_group'],how='left',indicator=True)

In [51]:
test.query('prime_mover.isnull()')['fuel_group'].value_counts(normalize=True)

petroleum      0.797101
natural_gas    0.202899
Name: fuel_group, dtype: float64

In [63]:
test.query('prime_mover.isnull()')['fuel_group'].value_counts()

petroleum      55
natural_gas    14
Name: fuel_group, dtype: int64

In [62]:
test['plant_gen_id'] = str(test['plant_id_eia']) + "_" + test['generator_id']

test.query('prime_mover.isnull()')['plant_gen_id'].nunique()

3

In [65]:
test.query('prime_mover.isnull()')['plant_id_eia'].unique()

<IntegerArray>
[130, 3264, 3399, 6469]
Length: 4, dtype: Int64

In [66]:
test.query('prime_mover.isnull() & plant_id_eia == 130',engine='python')

,plant_id_eia,generator_id,year,fuel_group,fuss,emissions_unit_id_epa,subplant_id,pf_subplant_id,prime_mover,unit_id_pudl,capacity_xwalk,generator_operating_date,plant_id_epa,ppf,single_prime,_merge,plant_gen_id
192,130,2,2006,petroleum,fuel_switch,<NA>,<NA>,NaN,<NA>,<NA>,NaN,NaT,<NA>,NaN,NaN,left_only,0 7527\n1 10333\n2 10333\n3...
193,130,2,2007,petroleum,fuel_switch,<NA>,<NA>,NaN,<NA>,<NA>,NaN,NaT,<NA>,NaN,NaN,left_only,0 7527\n1 10333\n2 10333\n3...
194,130,2,2008,petroleum,fuel_switch,<NA>,<NA>,NaN,<NA>,<NA>,NaN,NaT,<NA>,NaN,NaN,left_only,0 7527\n1 10333\n2 10333\n3...
195,130,2,2009,petroleum,fuel_switch,<NA>,<NA>,NaN,<NA>,<NA>,NaN,NaT,<NA>,NaN,NaN,left_only,0 7527\n1 10333\n2 10333\n3...
196,130,2,2010,petroleum,fuel_switch,<NA>,<NA>,NaN,<NA>,<NA>,NaN,NaT,<NA>,NaN,NaN,left_only,0 7527\n1 10333\n2 10333\n3...
197,130,2,2011,petroleum,fuel_switch,<NA>,<NA>,NaN,<NA>,<NA>,NaN,NaT,<NA>,NaN,NaN,left_only,0 7527\n1 10333\n2 10333\n3...
198,130,2,2012,petroleum,fuel_switch,<NA>,<NA>,NaN,<NA>,<NA>,NaN,NaT,<NA>,NaN,NaN,left_only,0 7527\n1 10333\n2 10333\n3...
199,130,2,2013,petroleum,fuel_switch,<NA>,<NA>,NaN,<NA>,<NA>,NaN,NaT,<NA>,NaN,NaN,left_only,0 7527\n1 10333\n2 10333\n3...
200,130,2,2014,petroleum,fuel_switch,<NA>,<NA>,NaN,<NA>,<NA>,NaN,NaT,<NA>,NaN,NaN,left_only,0 7527\n1 10333\n2 10333\n3...
201,130,2,2015,petroleum,fuel_switch,<NA>,<NA>,NaN,<NA>,<NA>,NaN,NaT,<NA>,NaN,NaN,left_only,0 7527\n1 10333\n2 10333\n3...
202,130,2,2016,petroleum,fuel_switch,<NA>,<NA>,NaN,<NA>,<NA>,NaN,NaT,<NA>,NaN,NaN,left_only,0 7527\n1 10333\n2 10333\n3...
203,130,2,2018,petroleum,fuel_switch,<NA>,<NA>,NaN,<NA>,<NA>,NaN,NaT,<NA>,NaN,NaN,left_only,0 7527\n1 10333\n2 10333\n3...
204,130,2,2019,petroleum,fuel_switch,<NA>,<NA>,NaN,<NA>,<NA>,NaN,NaT,<NA>,NaN,NaN,left_only,0 7527\n1 10333\n2 10333\n3...

In [67]:
test.query('prime_mover.isnull() & plant_id_eia == 3264',engine='python')

,plant_id_eia,generator_id,year,fuel_group,fuss,emissions_unit_id_epa,subplant_id,pf_subplant_id,prime_mover,unit_id_pudl,capacity_xwalk,generator_operating_date,plant_id_epa,ppf,single_prime,_merge,plant_gen_id
1086,3264,3,2006,petroleum,fuel_switch,<NA>,<NA>,NaN,<NA>,<NA>,NaN,NaT,<NA>,NaN,NaN,left_only,0 7527\n1 10333\n2 10333\n3...
1087,3264,3,2007,petroleum,fuel_switch,<NA>,<NA>,NaN,<NA>,<NA>,NaN,NaT,<NA>,NaN,NaN,left_only,0 7527\n1 10333\n2 10333\n3...
1088,3264,3,2008,petroleum,fuel_switch,<NA>,<NA>,NaN,<NA>,<NA>,NaN,NaT,<NA>,NaN,NaN,left_only,0 7527\n1 10333\n2 10333\n3...
1089,3264,3,2009,petroleum,fuel_switch,<NA>,<NA>,NaN,<NA>,<NA>,NaN,NaT,<NA>,NaN,NaN,left_only,0 7527\n1 10333\n2 10333\n3...
1090,3264,3,2010,petroleum,fuel_switch,<NA>,<NA>,NaN,<NA>,<NA>,NaN,NaT,<NA>,NaN,NaN,left_only,0 7527\n1 10333\n2 10333\n3...
1091,3264,3,2011,petroleum,fuel_switch,<NA>,<NA>,NaN,<NA>,<NA>,NaN,NaT,<NA>,NaN,NaN,left_only,0 7527\n1 10333\n2 10333\n3...
1092,3264,3,2012,petroleum,fuel_switch,<NA>,<NA>,NaN,<NA>,<NA>,NaN,NaT,<NA>,NaN,NaN,left_only,0 7527\n1 10333\n2 10333\n3...
1093,3264,3,2013,petroleum,fuel_switch,<NA>,<NA>,NaN,<NA>,<NA>,NaN,NaT,<NA>,NaN,NaN,left_only,0 7527\n1 10333\n2 10333\n3...
2226,3264,3,2015,petroleum,fuel_switch,<NA>,<NA>,NaN,<NA>,<NA>,NaN,NaT,<NA>,NaN,NaN,left_only,0 7527\n1 10333\n2 10333\n3...
2227,3264,3,2016,petroleum,fuel_switch,<NA>,<NA>,NaN,<NA>,<NA>,NaN,NaT,<NA>,NaN,NaN,left_only,0 7527\n1 10333\n2 10333\n3...
2228,3264,3,2017,petroleum,fuel_switch,<NA>,<NA>,NaN,<NA>,<NA>,NaN,NaT,<NA>,NaN,NaN,left_only,0 7527\n1 10333\n2 10333\n3...
2229,3264,3,2018,petroleum,fuel_switch,<NA>,<NA>,NaN,<NA>,<NA>,NaN,NaT,<NA>,NaN,NaN,left_only,0 7527\n1 10333\n2 10333\n3...
2230,3264,3,2019,petroleum,fuel_switch,<NA>,<NA>,NaN,<NA>,<NA>,NaN,NaT,<NA>,NaN,NaN,left_only,0 7527\n1 10333\n2 10333\n3...
2231,3264,3,2020,petroleum,fuel_switch,<NA>,<NA>,NaN,<NA>,<NA>,NaN,NaT,<NA>,NaN,NaN,left_only,0 7527\n1 10333\n2 10333\n3...

In [69]:
test

,plant_id_eia,generator_id,year,fuel_group,fuss,emissions_unit_id_epa,subplant_id,pf_subplant_id,prime_mover,unit_id_pudl,capacity_xwalk,generator_operating_date,plant_id_epa,ppf,single_prime,_merge,plant_gen_id
0,7527,2,2012,natural_gas,fuel_switch,1,0,0.0,CC,1,17.5,1995-10-01,7527,7527_CC_natural_gas,False,both,0 7527\n1 10333\n2 10333\n3...
1,10333,GEN1,2013,coal,fuel_switch,1,0,0.0,ST,1,125.0,1988-06-01,10333,10333_ST_coal,True,both,0 7527\n1 10333\n2 10333\n3...
2,10333,GEN1,2014,coal,fuel_switch,1,0,0.0,ST,1,125.0,1988-06-01,10333,10333_ST_coal,True,both,0 7527\n1 10333\n2 10333\n3...
3,10333,GEN1,2015,coal,fuel_switch,1,0,0.0,ST,1,125.0,1988-06-01,10333,10333_ST_coal,True,both,0 7527\n1 10333\n2 10333\n3...
4,10333,GEN1,2016,coal,fuel_switch,1,0,0.0,ST,1,125.0,1988-06-01,10333,10333_ST_coal,True,both,0 7527\n1 10333\n2 10333\n3...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2392,55505,BR2,2016,petroleum,fuel_switch,BR2,1,0.0,GT,<NA>,77.1,2002-05-01,55505,55505_GT_petroleum,True,both,0 7527\n1 10333\n2 10333\n3...
2393,55505,BR2,2017,petroleum,fuel_switch,BR2,1,0.0,GT,<NA>,77.1,2002-05-01,55505,55505_GT_petroleum,True,both,0 7527\n1 10333\n2 10333\n3...
2394,55505,BR2,2018,petroleum,fuel_switch,BR2,1,0.0,GT,<NA>,77.1,2002-05-01,55505,55505_GT_petroleum,True,both,0 7527\n1 10333\n2 10333\n3...
2395,55505,BR2,2019,petroleum,fuel_switch,BR2,1,0.0,GT,<NA>,77.1,2002-05-01,55505,55505_GT_petroleum,True,both,0 7527\n1 10333\n2 10333\n3...
2396,55505,BR2,2020,petroleum,fuel_switch,BR2,1,0.0,GT,<NA>,77.1,2002-05-01,55505,55505_GT_petroleum,True,both,0 7527\n1 10333\n2 10333\n3...

In [68]:
test.query('prime_mover.isnull() & plant_id_eia == 3399',engine='python')

,plant_id_eia,generator_id,year,fuel_group,fuss,emissions_unit_id_epa,subplant_id,pf_subplant_id,prime_mover,unit_id_pudl,capacity_xwalk,generator_operating_date,plant_id_epa,ppf,single_prime,_merge,plant_gen_id
1118,3399,1,2006,petroleum,fuel_switch,<NA>,<NA>,NaN,<NA>,<NA>,NaN,NaT,<NA>,NaN,NaN,left_only,0 7527\n1 10333\n2 10333\n3...
1119,3399,1,2007,petroleum,fuel_switch,<NA>,<NA>,NaN,<NA>,<NA>,NaN,NaT,<NA>,NaN,NaN,left_only,0 7527\n1 10333\n2 10333\n3...
1120,3399,1,2008,petroleum,fuel_switch,<NA>,<NA>,NaN,<NA>,<NA>,NaN,NaT,<NA>,NaN,NaN,left_only,0 7527\n1 10333\n2 10333\n3...
1121,3399,1,2009,petroleum,fuel_switch,<NA>,<NA>,NaN,<NA>,<NA>,NaN,NaT,<NA>,NaN,NaN,left_only,0 7527\n1 10333\n2 10333\n3...
1122,3399,1,2010,petroleum,fuel_switch,<NA>,<NA>,NaN,<NA>,<NA>,NaN,NaT,<NA>,NaN,NaN,left_only,0 7527\n1 10333\n2 10333\n3...
1123,3399,1,2011,petroleum,fuel_switch,<NA>,<NA>,NaN,<NA>,<NA>,NaN,NaT,<NA>,NaN,NaN,left_only,0 7527\n1 10333\n2 10333\n3...
1124,3399,1,2012,petroleum,fuel_switch,<NA>,<NA>,NaN,<NA>,<NA>,NaN,NaT,<NA>,NaN,NaN,left_only,0 7527\n1 10333\n2 10333\n3...
1125,3399,1,2013,petroleum,fuel_switch,<NA>,<NA>,NaN,<NA>,<NA>,NaN,NaT,<NA>,NaN,NaN,left_only,0 7527\n1 10333\n2 10333\n3...
1126,3399,1,2014,petroleum,fuel_switch,<NA>,<NA>,NaN,<NA>,<NA>,NaN,NaT,<NA>,NaN,NaN,left_only,0 7527\n1 10333\n2 10333\n3...
1127,3399,1,2015,petroleum,fuel_switch,<NA>,<NA>,NaN,<NA>,<NA>,NaN,NaT,<NA>,NaN,NaN,left_only,0 7527\n1 10333\n2 10333\n3...
1128,3399,1,2016,petroleum,fuel_switch,<NA>,<NA>,NaN,<NA>,<NA>,NaN,NaT,<NA>,NaN,NaN,left_only,0 7527\n1 10333\n2 10333\n3...
1129,3399,1,2017,petroleum,fuel_switch,<NA>,<NA>,NaN,<NA>,<NA>,NaN,NaT,<NA>,NaN,NaN,left_only,0 7527\n1 10333\n2 10333\n3...
1130,3399,1,2018,petroleum,fuel_switch,<NA>,<NA>,NaN,<NA>,<NA>,NaN,NaT,<NA>,NaN,NaN,left_only,0 7527\n1 10333\n2 10333\n3...
1131,3399,1,2020,petroleum,fuel_switch,<NA>,<NA>,NaN,<NA>,<NA>,NaN,NaT,<NA>,NaN,NaN,left_only,0 7527\n1 10333\n2 10333\n3...
1132,3399,2,2006,petroleum,fuel_switch,<NA>,<NA>,NaN,<NA>,<NA>,NaN,NaT,<NA>,NaN,NaN,left_only,0 7527\n1 10333\n2 10333\n3...
1133,3399,2,2007,petroleum,fuel_switch,<NA>,<NA>,NaN,<NA>,<NA>,NaN,NaT,<NA>,NaN,NaN,left_only,0 7527\n1 10333\n2 10333\n3...
1134,3399,2,2008,petroleum,fuel_switch,<NA>,<NA>,NaN,<NA>,<NA>,NaN,NaT,<NA>,NaN,NaN,left_only,0 7527\n1 10333\n2 10333\n3...
1135,3399,2,2009,petroleum,fuel_switch,<NA>,<NA>,NaN,<NA>,<NA>,NaN,NaT,<NA>,NaN,NaN,left_only,0 7527\n1 10333\n2 10333\n3...
1136,3399,2,2010,petroleum,fuel_switch,<NA>,<NA>,NaN,<NA>,<NA>,NaN,NaT,<NA>,NaN,NaN,left_only,0 7527\n1 10333\n2 10333\n3...
1137,3399,2,2011,petroleum,fuel_switch,<NA>,<NA>,NaN,<NA>,<NA>,NaN,NaT,<NA>,NaN,NaN,left_only,0 7527\n1 10333\n2 10333\n3...
1138,3399,2,2012,petroleum,fuel_switch,<NA>,<NA>,NaN,<NA>,<NA>,NaN,NaT,<NA>,NaN,NaN,left_only,0 7527\n1 10333\n2 10333\n3...
1139,3399,2,2013,petroleum,fuel_switch,<NA>,<NA>,NaN,<NA>,<NA>,NaN,NaT,<NA>,NaN,NaN,left_only,0 7527\n1 10333\n2 10333\n3...
1140,3399,2,2014,petroleum,fuel_switch,<NA>,<NA>,NaN,<NA>,<NA>,NaN,NaT,<NA>,NaN,NaN,left_only,0 7527\n1 10333\n2 10333\n3...
1141,3399,2,2015,petroleum,fuel_switch,<NA>,<NA>,NaN,<NA>,<NA>,NaN,NaT,<NA>,NaN,NaN,left_only,0 7527\n1 10333\n2 10333\n3...
1142,3399,2,2016,petroleum,fuel_switch,<NA>,<NA>,NaN,<NA>,<NA>,NaN,NaT,<NA>,NaN,NaN,left_only,0 7527\n1 10333\n2 10333\n3...
1143,3399,2,2017,petroleum,fuel_switch,<NA>,<NA>,NaN,<NA>,<NA>,NaN,NaT,<NA>,NaN,NaN,left_only,0 7527\n1 10333\n2 10333\n3...
1144,3399,2,2018,petroleum,fuel_switch,<NA>,<NA>,NaN,<NA>,<NA>,NaN,NaT,<NA>,NaN,NaN,left_only,0 7527\n1 10333\n2 10333\n3...
1145,3399,2,2020,petroleum,fuel_switch,<NA>,<NA>,NaN,<NA>,<NA>,NaN,NaT,<NA>,NaN,NaN,left_only,0 7527\n1 10333\n2 10333\n3...

In [72]:
hist_data = self.get_exa_by_generator()

/opt/anaconda3/envs/gencost/lib/python3.11/site-packages/etoolbox/utils/pudl_helpers.py:146: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[date_mask, date_col] = pd.to_datetime(
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:258: UserWarning: This crosswalk is not safe, it may have `pf_subplants with multiple primes. Use `safe_xwalk` instead.
  return self._xwalk.grand_crosswalk
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:199: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  np.repeat(df[old_cols].sum(axis=1)[:, np.newaxis], len(old_cols), 1) != 0.0,
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:204: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  df[old_cols].isna().sum(axis=1)[:, np.newaxis], len(old_cols), 1
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:213: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  df[to_allocate][:, np.newaxis],
/opt/anaconda3/envs/gencost/lib/python3.11/site-packages/etoolbox/utils/pudl_helpers.py:146: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[date_mask, date_col] = pd.to_datetime(

In [73]:
df_860 = self.get_860_by_x(subplant_id_col='generator_id')

/opt/anaconda3/envs/gencost/lib/python3.11/site-packages/etoolbox/utils/pudl_helpers.py:146: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[date_mask, date_col] = pd.to_datetime(

In [90]:
df_860

,utility_id_eia,balancing_authority_code_eia,state,plant_id_eia,generator_id,report_date,capacity_mw,prime_mover,associated_combined_heat_power,duct_burners,...,ultrasupercritical_tech,age_in_report_year,age_in_current_year,age_of_observation,age_relative_to_prime_avg,pollution_control_costs_per_kw,respondent_id,respondent_id_purchaser,final_respondent_id,final_ba_code
0,195,SOCO,AL,2,1,2001-01-01,45.0,HY,1,1,...,1,37.505818,58.420260,20.914442,-22.507147,2.92732,2,<NA>,2,2
1,195,SOCO,AL,3,1,2001-01-01,153.1,ST,1,1,...,1,46.915811,67.830253,20.914442,8.739862,2.92732,2,<NA>,2,2
2,195,SOCO,AL,3,2,2001-01-01,153.1,ST,1,1,...,1,46.505133,67.419576,20.914442,8.329184,2.92732,2,<NA>,2,2
3,195,SOCO,AL,3,3,2001-01-01,272.0,ST,1,1,...,1,41.505818,62.420260,20.914442,3.329869,NaN,2,<NA>,2,2
4,195,SOCO,AL,3,4,2001-01-01,403.7,ST,1,1,...,1,31.085558,52.000000,20.914442,-7.090392,2.92732,2,<NA>,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
427134,61980,NaN,CA,65824,VSPRC,2022-01-01,1.1,PV,1,1,...,1,1.752225,1.667351,-0.084873,-1.315511,NaN,<NA>,<NA>,<NA>,NaN
427135,65076,ERCO,TX,65831,LNSTR,2022-01-01,9.9,BA,1,1,...,1,NaN,NaN,-0.084873,NaN,NaN,<NA>,<NA>,<NA>,ERCO
427136,65076,ERCO,TX,65836,TOYAH,2022-01-01,10.4,BA,1,1,...,1,0.251882,0.167009,-0.084873,-1.996059,NaN,<NA>,<NA>,<NA>,ERCO
427137,65076,ERCO,TX,65838,HOEFS,2022-01-01,2.0,BA,1,1,...,1,0.670773,0.585900,-0.084873,-1.577168,NaN,<NA>,<NA>,<NA>,ERCO
427138,61944,ISNE,ME,65859,GEN1,2022-01-01,5.0,PV,1,1,...,1,NaN,NaN,-0.084873,NaN,NaN,<NA>,<NA>,<NA>,ISNE

In [77]:
(single_fuel_swtich
.merge(df_860.assign(year = lambda x: x['report_date'].dt.year)[['plant_id_eia','generator_id','year','final_ba_code','age_in_current_year']],
on=['plant_id_eia','generator_id','year'],
how='left',
indicator=True)
)

,plant_id_eia,generator_id,year,fuss,prime_mover,fuel_group,final_ba_code,age_in_current_year,_merge
0,7527,2,2012,fuel_switch,CC,natural_gas,CAISO,26.168378,both
1,10333,GEN1,2013,fuel_switch,ST,coal,FPC,33.500342,both
2,10333,GEN1,2014,fuel_switch,ST,coal,FPC,33.500342,both
3,10333,GEN1,2015,fuel_switch,ST,coal,FPC,33.500342,both
4,10333,GEN1,2016,fuel_switch,ST,coal,FPC,33.500342,both
...,...,...,...,...,...,...,...,...,...
2392,55505,BR2,2016,fuel_switch,GT,petroleum,529,19.586585,both
2393,55505,BR2,2017,fuel_switch,GT,petroleum,529,19.586585,both
2394,55505,BR2,2018,fuel_switch,GT,petroleum,529,19.586585,both
2395,55505,BR2,2019,fuel_switch,GT,petroleum,529,19.586585,both
2396,55505,BR2,2020,fuel_switch,GT,petroleum,529,19.586585,both

In [74]:
df_860

,utility_id_eia,balancing_authority_code_eia,state,plant_id_eia,generator_id,report_date,capacity_mw,prime_mover,associated_combined_heat_power,duct_burners,...,ultrasupercritical_tech,age_in_report_year,age_in_current_year,age_of_observation,age_relative_to_prime_avg,pollution_control_costs_per_kw,respondent_id,respondent_id_purchaser,final_respondent_id,final_ba_code
0,195,SOCO,AL,2,1,2001-01-01,45.0,HY,1,1,...,1,37.505818,58.420260,20.914442,-22.507147,2.92732,2,<NA>,2,2
1,195,SOCO,AL,3,1,2001-01-01,153.1,ST,1,1,...,1,46.915811,67.830253,20.914442,8.739862,2.92732,2,<NA>,2,2
2,195,SOCO,AL,3,2,2001-01-01,153.1,ST,1,1,...,1,46.505133,67.419576,20.914442,8.329184,2.92732,2,<NA>,2,2
3,195,SOCO,AL,3,3,2001-01-01,272.0,ST,1,1,...,1,41.505818,62.420260,20.914442,3.329869,NaN,2,<NA>,2,2
4,195,SOCO,AL,3,4,2001-01-01,403.7,ST,1,1,...,1,31.085558,52.000000,20.914442,-7.090392,2.92732,2,<NA>,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
427134,61980,NaN,CA,65824,VSPRC,2022-01-01,1.1,PV,1,1,...,1,1.752225,1.667351,-0.084873,-1.315511,NaN,<NA>,<NA>,<NA>,NaN
427135,65076,ERCO,TX,65831,LNSTR,2022-01-01,9.9,BA,1,1,...,1,NaN,NaN,-0.084873,NaN,NaN,<NA>,<NA>,<NA>,ERCO
427136,65076,ERCO,TX,65836,TOYAH,2022-01-01,10.4,BA,1,1,...,1,0.251882,0.167009,-0.084873,-1.996059,NaN,<NA>,<NA>,<NA>,ERCO
427137,65076,ERCO,TX,65838,HOEFS,2022-01-01,2.0,BA,1,1,...,1,0.670773,0.585900,-0.084873,-1.577168,NaN,<NA>,<NA>,<NA>,ERCO
427138,61944,ISNE,ME,65859,GEN1,2022-01-01,5.0,PV,1,1,...,1,NaN,NaN,-0.084873,NaN,NaN,<NA>,<NA>,<NA>,ISNE

In [87]:
hist_data

,plant_id_eia,generator_id,report_date,biofuel_mmbtu,coal_mmbtu,natural_gas_mmbtu,nuclear_mmbtu,other_mmbtu,other_gas_mmbtu,petroleum_mmbtu,...,age_in_current_year,age_of_observation,age_relative_to_prime_avg,pollution_control_costs_per_kw,respondent_id,respondent_id_purchaser,final_respondent_id,final_ba_code,wage_scale,age_of_observation_secular_adj
51,3,1,2006-01-01,NaN,1.008871e+07,2.951150e+04,NaN,NaN,NaN,NaN,...,67.830253,15.915127,13.739177,2.92732,2,<NA>,2,2,1.050357,13.40423
52,3,1,2007-01-01,NaN,9.807031e+06,NaN,NaN,NaN,NaN,NaN,...,67.830253,14.915811,14.738493,2.92732,2,<NA>,2,2,1.057435,14.461664
53,3,1,2008-01-01,NaN,8.176078e+06,NaN,NaN,NaN,NaN,NaN,...,67.830253,13.916496,15.737808,2.92732,2,<NA>,2,2,0.99812,15.459785
54,3,1,2009-01-01,NaN,2.274497e+06,7.626184e+03,NaN,NaN,NaN,NaN,...,67.830253,12.914442,16.739862,2.92732,2,<NA>,2,2,0.97293,16.432715
55,3,1,2010-01-01,NaN,4.481317e+06,4.298272e+04,NaN,NaN,NaN,NaN,...,67.830253,11.915127,17.739177,2.92732,2,<NA>,2,2,0.941299,17.374014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
415169,60926,1C,2019-01-01,NaN,NaN,0.000000e+00,NaN,NaN,NaN,NaN,...,2.587269,2.915811,-15.181727,NaN,454,<NA>,454,ETR,0.923801,24.360724
415170,60926,1C,2020-01-01,NaN,NaN,0.000000e+00,NaN,NaN,NaN,NaN,...,2.587269,1.916496,-14.182411,NaN,454,<NA>,454,ETR,0.964819,25.325543
415173,60927,1A,2020-01-01,NaN,NaN,1.202763e+07,NaN,NaN,NaN,NaN,...,1.752225,1.916496,-15.017456,NaN,454,<NA>,454,ETR,0.964819,25.325543
415176,60927,1B,2020-01-01,NaN,NaN,1.202763e+07,NaN,NaN,NaN,NaN,...,1.752225,1.916496,-15.017456,NaN,454,<NA>,454,ETR,0.964819,25.325543
415179,60927,1C,2020-01-01,NaN,NaN,0.000000e+00,NaN,NaN,NaN,NaN,...,1.752225,1.916496,-15.017456,NaN,454,<NA>,454,ETR,0.964819,25.325543

In [88]:
missing_yrs

,plant_id_eia,generator_id,year,fuss,prime_mover,fuel_group,final_ba_code,age_in_current_year
0,3,3,2016,missing_years,ST,natural_gas,2,NaN
1,3,3,2016,missing_years,ST,natural_gas,2,NaN
2,3,3,2016,missing_years,ST,natural_gas,2,NaN
3,3,3,2016,missing_years,ST,natural_gas,2,NaN
4,3,3,2016,missing_years,ST,natural_gas,2,NaN
...,...,...,...,...,...,...,...,...
2392,55505,BR2,2016,fuel_switch,GT,petroleum,529,19.586585
2393,55505,BR2,2017,fuel_switch,GT,petroleum,529,19.586585
2394,55505,BR2,2018,fuel_switch,GT,petroleum,529,19.586585
2395,55505,BR2,2019,fuel_switch,GT,petroleum,529,19.586585
2396,55505,BR2,2020,fuel_switch,GT,petroleum,529,19.586585

filling in process

In [96]:
missing

,plant_id_eia,generator_id,year,fuss,prime_mover,fuel_group,final_ba_code,age_in_current_year
0,3,3,2016,missing_years,ST,natural_gas,2,NaN
14,3,A1CT2,2008,missing_years,CC,natural_gas,2,NaN
28,8,10,2019,missing_years,ST,coal,2,NaN
46,8,6,2016,missing_years,ST,coal,2,NaN
60,8,7,2016,missing_years,ST,coal,2,NaN
...,...,...,...,...,...,...,...,...
2392,55505,BR2,2016,fuel_switch,GT,petroleum,529,19.586585
2393,55505,BR2,2017,fuel_switch,GT,petroleum,529,19.586585
2394,55505,BR2,2018,fuel_switch,GT,petroleum,529,19.586585
2395,55505,BR2,2019,fuel_switch,GT,petroleum,529,19.586585
2396,55505,BR2,2020,fuel_switch,GT,petroleum,529,19.586585

In [97]:
hist_data

,plant_id_eia,generator_id,report_date,biofuel_mmbtu,coal_mmbtu,natural_gas_mmbtu,nuclear_mmbtu,other_mmbtu,other_gas_mmbtu,petroleum_mmbtu,...,age_in_current_year,age_of_observation,age_relative_to_prime_avg,pollution_control_costs_per_kw,respondent_id,respondent_id_purchaser,final_respondent_id,final_ba_code,wage_scale,age_of_observation_secular_adj
51,3,1,2006-01-01,NaN,1.008871e+07,2.951150e+04,NaN,NaN,NaN,NaN,...,67.830253,15.915127,13.739177,2.92732,2,<NA>,2,2,1.050357,13.40423
52,3,1,2007-01-01,NaN,9.807031e+06,NaN,NaN,NaN,NaN,NaN,...,67.830253,14.915811,14.738493,2.92732,2,<NA>,2,2,1.057435,14.461664
53,3,1,2008-01-01,NaN,8.176078e+06,NaN,NaN,NaN,NaN,NaN,...,67.830253,13.916496,15.737808,2.92732,2,<NA>,2,2,0.99812,15.459785
54,3,1,2009-01-01,NaN,2.274497e+06,7.626184e+03,NaN,NaN,NaN,NaN,...,67.830253,12.914442,16.739862,2.92732,2,<NA>,2,2,0.97293,16.432715
55,3,1,2010-01-01,NaN,4.481317e+06,4.298272e+04,NaN,NaN,NaN,NaN,...,67.830253,11.915127,17.739177,2.92732,2,<NA>,2,2,0.941299,17.374014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
415169,60926,1C,2019-01-01,NaN,NaN,0.000000e+00,NaN,NaN,NaN,NaN,...,2.587269,2.915811,-15.181727,NaN,454,<NA>,454,ETR,0.923801,24.360724
415170,60926,1C,2020-01-01,NaN,NaN,0.000000e+00,NaN,NaN,NaN,NaN,...,2.587269,1.916496,-14.182411,NaN,454,<NA>,454,ETR,0.964819,25.325543
415173,60927,1A,2020-01-01,NaN,NaN,1.202763e+07,NaN,NaN,NaN,NaN,...,1.752225,1.916496,-15.017456,NaN,454,<NA>,454,ETR,0.964819,25.325543
415176,60927,1B,2020-01-01,NaN,NaN,1.202763e+07,NaN,NaN,NaN,NaN,...,1.752225,1.916496,-15.017456,NaN,454,<NA>,454,ETR,0.964819,25.325543
415179,60927,1C,2020-01-01,NaN,NaN,0.000000e+00,NaN,NaN,NaN,NaN,...,1.752225,1.916496,-15.017456,NaN,454,<NA>,454,ETR,0.964819,25.325543

In [99]:
xwalk

,plant_id_eia,generator_id,emissions_unit_id_epa,subplant_id,pf_subplant_id,prime_mover,fuel_group,unit_id_pudl,capacity_xwalk,generator_operating_date,plant_id_epa,ppf,single_prime
0,1,WT2,WT2,0,0,WT,renew,<NA>,0.5,2011-10-01,1,1_WT_renew,True
1,1,WT1,WT1,1,0,WT,renew,<NA>,0.5,2011-10-01,1,1_WT_renew,True
2,1,5,5,2,1,IC,petroleum,<NA>,0.7,2000-12-01,1,1_IC_petroleum,True
3,1,3,3,3,1,IC,petroleum,<NA>,0.5,2010-12-01,1,1_IC_petroleum,True
4,1,2,2,4,1,IC,petroleum,<NA>,0.9,2000-12-01,1,1_IC_petroleum,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
43015,65815,MPRES,MPRES,0,0,PV,renew,<NA>,1.0,2021-12-01,65815,65815_PV_renew,True
43016,65817,CLEA1,CLEA1,0,0,PV,renew,<NA>,3.6,2020-09-01,65817,65817_PV_renew,True
43017,65824,VSPRC,VSPRC,0,0,PV,renew,<NA>,1.1,2020-04-01,65824,65824_PV_renew,True
43018,65836,TOYAH,TOYAH,0,0,BA,other,<NA>,10.4,2021-10-01,65836,65836_BA_other,True
43019,65838,HOEFS,HOEFS,0,0,BA,other,<NA>,2.0,2021-05-01,65838,65838_BA_other,True

In [150]:
bins = [0,10,20,30,40,50,60,70,100]

labels = [1,2,3,4,5,6,7,8]

missing_1 = missing.assign(age_in_current_year = lambda x: np.where(x['age_in_current_year'].isnull(),30,x['age_in_current_year']),
essentials = lambda x: x['year'].astype(str) + "_" + x['prime_mover'] + "_" + x['fuel_group'],
ba_plus_essentials = lambda x: x['essentials'] + "_" + x['final_ba_code'],
age_range = lambda x: pd.cut(x['age_in_current_year'],bins=bins,labels=labels),
ba_plus_age = lambda x: x['ba_plus_essentials'] + "_" + x['age_range'])

In [151]:
missing_1

,plant_id_eia,generator_id,year,fuss,prime_mover,fuel_group,final_ba_code,age_in_current_year,essentials,ba_plus_essentials,age_range
0,3,3,2016,missing_years,ST,natural_gas,2,30.000000,2016_ST_natural_gas,2016_ST_natural_gas_2,3
14,3,A1CT2,2008,missing_years,CC,natural_gas,2,30.000000,2008_CC_natural_gas,2008_CC_natural_gas_2,3
28,8,10,2019,missing_years,ST,coal,2,30.000000,2019_ST_coal,2019_ST_coal_2,3
46,8,6,2016,missing_years,ST,coal,2,30.000000,2016_ST_coal,2016_ST_coal_2,3
60,8,7,2016,missing_years,ST,coal,2,30.000000,2016_ST_coal,2016_ST_coal_2,3
...,...,...,...,...,...,...,...,...,...,...,...
2392,55505,BR2,2016,fuel_switch,GT,petroleum,529,19.586585,2016_GT_petroleum,2016_GT_petroleum_529,2
2393,55505,BR2,2017,fuel_switch,GT,petroleum,529,19.586585,2017_GT_petroleum,2017_GT_petroleum_529,2
2394,55505,BR2,2018,fuel_switch,GT,petroleum,529,19.586585,2018_GT_petroleum,2018_GT_petroleum_529,2
2395,55505,BR2,2019,fuel_switch,GT,petroleum,529,19.586585,2019_GT_petroleum,2019_GT_petroleum_529,2
2396,55505,BR2,2020,fuel_switch,GT,petroleum,529,19.586585,2020_GT_petroleum,2020_GT_petroleum_529,2

In [114]:

hist_data_1 = (hist_data.
merge(xwalk[['plant_id_eia','generator_id','prime_mover','fuel_group']],
on=['plant_id_eia','generator_id','prime_mover'],how='left')
.assign(year = lambda x: x['report_date'].dt.year,
essentials = lambda x: x['year'].astype(str)  + "_" + x['prime_mover'] + "_" + x['fuel_group'],
ba_plus_essentials = lambda x: x['essentials'] + "_" + x['final_ba_code']
age_range=)
)

In [117]:
missing_1['essentials_present'] = np.where(missing_1['essentials'].isin(hist_data_1['essentials']),1,0)
missing_1['ba_plus_present'] = np.where(missing_1['ba_plus_essentials'].isin(hist_data_1['ba_plus_essentials']),1,0)
missing_1['ag']
missing_1

,plant_id_eia,generator_id,year,fuss,prime_mover,fuel_group,final_ba_code,age_in_current_year,essentials,ba_plus_essentials,essentials_present,ba_plus_present
0,3,3,2016,missing_years,ST,natural_gas,2,NaN,2016_ST_natural_gas,2016_ST_natural_gas_2,1,1
14,3,A1CT2,2008,missing_years,CC,natural_gas,2,NaN,2008_CC_natural_gas,2008_CC_natural_gas_2,1,1
28,8,10,2019,missing_years,ST,coal,2,NaN,2019_ST_coal,2019_ST_coal_2,1,1
46,8,6,2016,missing_years,ST,coal,2,NaN,2016_ST_coal,2016_ST_coal_2,1,1
60,8,7,2016,missing_years,ST,coal,2,NaN,2016_ST_coal,2016_ST_coal_2,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...
2392,55505,BR2,2016,fuel_switch,GT,petroleum,529,19.586585,2016_GT_petroleum,2016_GT_petroleum_529,1,1
2393,55505,BR2,2017,fuel_switch,GT,petroleum,529,19.586585,2017_GT_petroleum,2017_GT_petroleum_529,1,1
2394,55505,BR2,2018,fuel_switch,GT,petroleum,529,19.586585,2018_GT_petroleum,2018_GT_petroleum_529,1,1
2395,55505,BR2,2019,fuel_switch,GT,petroleum,529,19.586585,2019_GT_petroleum,2019_GT_petroleum_529,1,1
2396,55505,BR2,2020,fuel_switch,GT,petroleum,529,19.586585,2020_GT_petroleum,2020_GT_petroleum_529,1,1

In [120]:
missing_1.query('ba_plus_present == 0',engine='python')

,plant_id_eia,generator_id,year,fuss,prime_mover,fuel_group,final_ba_code,age_in_current_year,essentials,ba_plus_essentials,essentials_present,ba_plus_present
110,9,1,2006,missing_years,GT,natural_gas,EPE,NaN,2006_GT_natural_gas,2006_GT_natural_gas_EPE,1,0
5241,988,1,2016,missing_years,ST,petroleum,AEP,NaN,2016_ST_petroleum,2016_ST_petroleum_AEP,1,0
6102,1105,1,2017,missing_years,IC,petroleum,MISO,NaN,2017_IC_petroleum,2017_IC_petroleum_MISO,1,0
6118,1105,2,2017,missing_years,IC,petroleum,MISO,NaN,2017_IC_petroleum,2017_IC_petroleum_MISO,1,0
6984,1363,7A,2006,missing_years,CC,natural_gas,LGEE,NaN,2006_CC_natural_gas,2006_CC_natural_gas_LGEE,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
139246,60340,1,2015,missing_years,ST,biofuel,57,NaN,2015_ST_biofuel,2015_ST_biofuel_57,1,0
2242,6043,8,2009,fuel_switch,CC,renew,FPL,16.501027,2009_CC_renew,2009_CC_renew_FPL,0,0
2243,6043,8,2009,fuel_switch,CC,renew,FPL,16.501027,2009_CC_renew,2009_CC_renew_FPL,0,0
2244,6043,8,2009,fuel_switch,CC,renew,FPL,16.501027,2009_CC_renew,2009_CC_renew_FPL,0,0
2245,6043,8,2009,fuel_switch,CC,renew,FPL,16.501027,2009_CC_renew,2009_CC_renew_FPL,0,0

,plant_id_eia,generator_id,report_date,biofuel_mmbtu,coal_mmbtu,natural_gas_mmbtu,nuclear_mmbtu,other_mmbtu,other_gas_mmbtu,petroleum_mmbtu,...,respondent_id,respondent_id_purchaser,final_respondent_id,final_ba_code,wage_scale,age_of_observation_secular_adj,fuel_group,year,essentials,ba_plus_essentials
0,3,1,2006-01-01,NaN,1.008871e+07,2.951150e+04,NaN,NaN,NaN,NaN,...,2,<NA>,2,2,1.050357,13.40423,coal,2006,2006_ST_coal,2006_ST_coal_2
1,3,1,2006-01-01,NaN,1.008871e+07,2.951150e+04,NaN,NaN,NaN,NaN,...,2,<NA>,2,2,1.050357,13.40423,natural_gas,2006,2006_ST_natural_gas,2006_ST_natural_gas_2
2,3,1,2007-01-01,NaN,9.807031e+06,NaN,NaN,NaN,NaN,NaN,...,2,<NA>,2,2,1.057435,14.461664,coal,2007,2007_ST_coal,2007_ST_coal_2
3,3,1,2007-01-01,NaN,9.807031e+06,NaN,NaN,NaN,NaN,NaN,...,2,<NA>,2,2,1.057435,14.461664,natural_gas,2007,2007_ST_natural_gas,2007_ST_natural_gas_2
4,3,1,2008-01-01,NaN,8.176078e+06,NaN,NaN,NaN,NaN,NaN,...,2,<NA>,2,2,0.99812,15.459785,coal,2008,2008_ST_coal,2008_ST_coal_2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133749,60926,1C,2019-01-01,NaN,NaN,0.000000e+00,NaN,NaN,NaN,NaN,...,454,<NA>,454,ETR,0.923801,24.360724,natural_gas,2019,2019_CC_natural_gas,2019_CC_natural_gas_ETR
133750,60926,1C,2020-01-01,NaN,NaN,0.000000e+00,NaN,NaN,NaN,NaN,...,454,<NA>,454,ETR,0.964819,25.325543,natural_gas,2020,2020_CC_natural_gas,2020_CC_natural_gas_ETR
133751,60927,1A,2020-01-01,NaN,NaN,1.202763e+07,NaN,NaN,NaN,NaN,...,454,<NA>,454,ETR,0.964819,25.325543,natural_gas,2020,2020_CC_natural_gas,2020_CC_natural_gas_ETR
133752,60927,1B,2020-01-01,NaN,NaN,1.202763e+07,NaN,NaN,NaN,NaN,...,454,<NA>,454,ETR,0.964819,25.325543,natural_gas,2020,2020_CC_natural_gas,2020_CC_natural_gas_ETR
133753,60927,1C,2020-01-01,NaN,NaN,0.000000e+00,NaN,NaN,NaN,NaN,...,454,<NA>,454,ETR,0.964819,25.325543,natural_gas,2020,2020_CC_natural_gas,2020_CC_natural_gas_ETR

In [145]:
missing_1.

,plant_id_eia,generator_id,year,fuss,prime_mover,fuel_group,final_ba_code,age_in_current_year,essentials,ba_plus_essentials,essentials_present,ba_plus_present
0,3,3,2016,missing_years,ST,natural_gas,2,NaN,2016_ST_natural_gas,2016_ST_natural_gas_2,1,1
14,3,A1CT2,2008,missing_years,CC,natural_gas,2,NaN,2008_CC_natural_gas,2008_CC_natural_gas_2,1,1
28,8,10,2019,missing_years,ST,coal,2,NaN,2019_ST_coal,2019_ST_coal_2,1,1
46,8,6,2016,missing_years,ST,coal,2,NaN,2016_ST_coal,2016_ST_coal_2,1,1
60,8,7,2016,missing_years,ST,coal,2,NaN,2016_ST_coal,2016_ST_coal_2,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...
2392,55505,BR2,2016,fuel_switch,GT,petroleum,529,19.586585,2016_GT_petroleum,2016_GT_petroleum_529,1,1
2393,55505,BR2,2017,fuel_switch,GT,petroleum,529,19.586585,2017_GT_petroleum,2017_GT_petroleum_529,1,1
2394,55505,BR2,2018,fuel_switch,GT,petroleum,529,19.586585,2018_GT_petroleum,2018_GT_petroleum_529,1,1
2395,55505,BR2,2019,fuel_switch,GT,petroleum,529,19.586585,2019_GT_petroleum,2019_GT_petroleum_529,1,1
2396,55505,BR2,2020,fuel_switch,GT,petroleum,529,19.586585,2020_GT_petroleum,2020_GT_petroleum_529,1,1

In [144]:
hist_data_1

,plant_id_eia,generator_id,report_date,biofuel_mmbtu,coal_mmbtu,natural_gas_mmbtu,nuclear_mmbtu,other_mmbtu,other_gas_mmbtu,petroleum_mmbtu,...,respondent_id,respondent_id_purchaser,final_respondent_id,final_ba_code,wage_scale,age_of_observation_secular_adj,fuel_group,year,essentials,ba_plus_essentials
0,3,1,2006-01-01,NaN,1.008871e+07,2.951150e+04,NaN,NaN,NaN,NaN,...,2,<NA>,2,2,1.050357,13.40423,coal,2006,2006_ST_coal,2006_ST_coal_2
1,3,1,2006-01-01,NaN,1.008871e+07,2.951150e+04,NaN,NaN,NaN,NaN,...,2,<NA>,2,2,1.050357,13.40423,natural_gas,2006,2006_ST_natural_gas,2006_ST_natural_gas_2
2,3,1,2007-01-01,NaN,9.807031e+06,NaN,NaN,NaN,NaN,NaN,...,2,<NA>,2,2,1.057435,14.461664,coal,2007,2007_ST_coal,2007_ST_coal_2
3,3,1,2007-01-01,NaN,9.807031e+06,NaN,NaN,NaN,NaN,NaN,...,2,<NA>,2,2,1.057435,14.461664,natural_gas,2007,2007_ST_natural_gas,2007_ST_natural_gas_2
4,3,1,2008-01-01,NaN,8.176078e+06,NaN,NaN,NaN,NaN,NaN,...,2,<NA>,2,2,0.99812,15.459785,coal,2008,2008_ST_coal,2008_ST_coal_2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133749,60926,1C,2019-01-01,NaN,NaN,0.000000e+00,NaN,NaN,NaN,NaN,...,454,<NA>,454,ETR,0.923801,24.360724,natural_gas,2019,2019_CC_natural_gas,2019_CC_natural_gas_ETR
133750,60926,1C,2020-01-01,NaN,NaN,0.000000e+00,NaN,NaN,NaN,NaN,...,454,<NA>,454,ETR,0.964819,25.325543,natural_gas,2020,2020_CC_natural_gas,2020_CC_natural_gas_ETR
133751,60927,1A,2020-01-01,NaN,NaN,1.202763e+07,NaN,NaN,NaN,NaN,...,454,<NA>,454,ETR,0.964819,25.325543,natural_gas,2020,2020_CC_natural_gas,2020_CC_natural_gas_ETR
133752,60927,1B,2020-01-01,NaN,NaN,1.202763e+07,NaN,NaN,NaN,NaN,...,454,<NA>,454,ETR,0.964819,25.325543,natural_gas,2020,2020_CC_natural_gas,2020_CC_natural_gas_ETR
133753,60927,1C,2020-01-01,NaN,NaN,0.000000e+00,NaN,NaN,NaN,NaN,...,454,<NA>,454,ETR,0.964819,25.325543,natural_gas,2020,2020_CC_natural_gas,2020_CC_natural_gas_ETR

In [138]:
missing_1.merge(hist_data_1,on=['essentials'],how='left',indicator=True)

,plant_id_eia_x,generator_id_x,year_x,fuss,prime_mover_x,fuel_group_x,final_ba_code_x,age_in_current_year_x,essentials,ba_plus_essentials_x,...,respondent_id,respondent_id_purchaser,final_respondent_id,final_ba_code_y,wage_scale,age_of_observation_secular_adj,fuel_group_y,year_y,ba_plus_essentials_y,_merge
0,3,3,2016,missing_years,ST,natural_gas,2,NaN,2016_ST_natural_gas,2016_ST_natural_gas_2,...,2,<NA>,2,2,1.011758,23.20239,natural_gas,2016.0,2016_ST_natural_gas_2,both
1,3,3,2016,missing_years,ST,natural_gas,2,NaN,2016_ST_natural_gas,2016_ST_natural_gas_2,...,2,<NA>,2,2,1.011758,23.20239,natural_gas,2016.0,2016_ST_natural_gas_2,both
2,3,3,2016,missing_years,ST,natural_gas,2,NaN,2016_ST_natural_gas,2016_ST_natural_gas_2,...,2,<NA>,2,2,1.011758,23.20239,natural_gas,2016.0,2016_ST_natural_gas_2,both
3,3,3,2016,missing_years,ST,natural_gas,2,NaN,2016_ST_natural_gas,2016_ST_natural_gas_2,...,2,<NA>,2,2,1.011758,23.20239,natural_gas,2016.0,2016_ST_natural_gas_2,both
4,3,3,2016,missing_years,ST,natural_gas,2,NaN,2016_ST_natural_gas,2016_ST_natural_gas_2,...,2,<NA>,2,2,1.011758,23.20239,natural_gas,2016.0,2016_ST_natural_gas_2,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17322880,55505,BR2,2020,fuel_switch,GT,petroleum,529,19.586585,2020_GT_petroleum,2020_GT_petroleum_529,...,49,<NA>,49,EPE,1.013692,27.335436,petroleum,2020.0,2020_GT_petroleum_EPE,both
17322881,55505,BR2,2020,fuel_switch,GT,petroleum,529,19.586585,2020_GT_petroleum,2020_GT_petroleum_529,...,49,<NA>,49,EPE,1.013692,27.335436,petroleum,2020.0,2020_GT_petroleum_EPE,both
17322882,55505,BR2,2020,fuel_switch,GT,petroleum,529,19.586585,2020_GT_petroleum,2020_GT_petroleum_529,...,49,<NA>,49,EPE,1.013692,27.335436,petroleum,2020.0,2020_GT_petroleum_EPE,both
17322883,55505,BR2,2020,fuel_switch,GT,petroleum,529,19.586585,2020_GT_petroleum,2020_GT_petroleum_529,...,17,<NA>,17,DUKE,0.922797,26.923455,petroleum,2020.0,2020_GT_petroleum_DUKE,both
17322884,55505,BR2,2020,fuel_switch,GT,petroleum,529,19.586585,2020_GT_petroleum,2020_GT_petroleum_529,...,17,<NA>,17,DUKE,0.922797,26.923455,petroleum,2020.0,2020_GT_petroleum_DUKE,both

In [141]:
hist_data_1.query('plant_id_eia ==3 & generator_id == "3"',engine='python')

,plant_id_eia,generator_id,report_date,biofuel_mmbtu,coal_mmbtu,natural_gas_mmbtu,nuclear_mmbtu,other_mmbtu,other_gas_mmbtu,petroleum_mmbtu,...,respondent_id,respondent_id_purchaser,final_respondent_id,final_ba_code,wage_scale,age_of_observation_secular_adj,fuel_group,year,essentials,ba_plus_essentials
60,3,3,2006-01-01,NaN,1.792376e+07,52430.611664,NaN,NaN,NaN,NaN,...,2,<NA>,2,2,1.050357,13.40423,coal,2006,2006_ST_coal,2006_ST_coal_2
61,3,3,2006-01-01,NaN,1.792376e+07,52430.611664,NaN,NaN,NaN,NaN,...,2,<NA>,2,2,1.050357,13.40423,natural_gas,2006,2006_ST_natural_gas,2006_ST_natural_gas_2
62,3,3,2007-01-01,NaN,1.742333e+07,NaN,NaN,NaN,NaN,NaN,...,2,<NA>,2,2,1.057435,14.461664,coal,2007,2007_ST_coal,2007_ST_coal_2
63,3,3,2007-01-01,NaN,1.742333e+07,NaN,NaN,NaN,NaN,NaN,...,2,<NA>,2,2,1.057435,14.461664,natural_gas,2007,2007_ST_natural_gas,2007_ST_natural_gas_2
64,3,3,2008-01-01,NaN,1.452576e+07,NaN,NaN,NaN,NaN,NaN,...,2,<NA>,2,2,0.99812,15.459785,coal,2008,2008_ST_coal,2008_ST_coal_2
65,3,3,2008-01-01,NaN,1.452576e+07,NaN,NaN,NaN,NaN,NaN,...,2,<NA>,2,2,0.99812,15.459785,natural_gas,2008,2008_ST_natural_gas,2008_ST_natural_gas_2
66,3,3,2009-01-01,NaN,1.290395e+07,162040.790908,NaN,NaN,NaN,NaN,...,2,<NA>,2,2,0.97293,16.432715,coal,2009,2009_ST_coal,2009_ST_coal_2
67,3,3,2009-01-01,NaN,1.290395e+07,162040.790908,NaN,NaN,NaN,NaN,...,2,<NA>,2,2,0.97293,16.432715,natural_gas,2009,2009_ST_natural_gas,2009_ST_natural_gas_2
68,3,3,2010-01-01,NaN,9.347638e+06,222547.907467,NaN,NaN,NaN,NaN,...,2,<NA>,2,2,0.941299,17.374014,coal,2010,2010_ST_coal,2010_ST_coal_2
69,3,3,2010-01-01,NaN,9.347638e+06,222547.907467,NaN,NaN,NaN,NaN,...,2,<NA>,2,2,0.941299,17.374014,natural_gas,2010,2010_ST_natural_gas,2010_ST_natural_gas_2
70,3,3,2011-01-01,NaN,7.362656e+06,152367.598227,NaN,NaN,NaN,NaN,...,2,<NA>,2,2,0.973222,18.347236,coal,2011,2011_ST_coal,2011_ST_coal_2
71,3,3,2011-01-01,NaN,7.362656e+06,152367.598227,NaN,NaN,NaN,NaN,...,2,<NA>,2,2,0.973222,18.347236,natural_gas,2011,2011_ST_natural_gas,2011_ST_natural_gas_2
72,3,3,2012-01-01,NaN,5.212445e+06,72263.977059,NaN,NaN,NaN,NaN,...,2,<NA>,2,2,0.983656,19.330892,coal,2012,2012_ST_coal,2012_ST_coal_2
73,3,3,2012-01-01,NaN,5.212445e+06,72263.977059,NaN,NaN,NaN,NaN,...,2,<NA>,2,2,0.983656,19.330892,natural_gas,2012,2012_ST_natural_gas,2012_ST_natural_gas_2
74,3,3,2013-01-01,NaN,4.319543e+06,260128.931855,NaN,NaN,NaN,NaN,...,2,<NA>,2,2,0.951011,20.281903,coal,2013,2013_ST_coal,2013_ST_coal_2
75,3,3,2013-01-01,NaN,4.319543e+06,260128.931855,NaN,NaN,NaN,NaN,...,2,<NA>,2,2,0.951011,20.281903,natural_gas,2013,2013_ST_natural_gas,2013_ST_natural_gas_2
76,3,3,2014-01-01,NaN,4.912620e+06,501259.678656,NaN,NaN,NaN,NaN,...,2,<NA>,2,2,0.935684,21.217587,coal,2014,2014_ST_coal,2014_ST_coal_2
77,3,3,2014-01-01,NaN,4.912620e+06,501259.678656,NaN,NaN,NaN,NaN,...,2,<NA>,2,2,0.935684,21.217587,natural_gas,2014,2014_ST_natural_gas,2014_ST_natural_gas_2

In [135]:

assign(age_in_current_year = lambda x: np.where(x['age_in_current_year'].isnull(),30,x['age_in_current_year']),
close_in_age = lambda x: np.where(abs(x['age_in_current_year'] - hist_data_1['age_in_current_year']) < 10,1,0)
)

ValueError: Length of values (134997) does not match length of index (14570)

In [29]:
missing_data_w_score = self.fill_in_ep_data()

/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:258: UserWarning: This crosswalk is not safe, it may have `pf_subplants with multiple primes. Use `safe_xwalk` instead.
  return self._xwalk.grand_crosswalk
/opt/anaconda3/envs/gencost/lib/python3.11/site-packages/etoolbox/utils/pudl_helpers.py:146: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[date_mask, date_col] = pd.to_datetime(
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:258: UserWarning: This crosswalk is not safe, it may have `pf_subplants with multiple primes. Use `safe_xwalk` instead.
  return self._xwalk.grand_crosswalk
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:199: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  np.repeat(df[old_cols].sum(axis=1)[:, np.newaxis], len(old_cols), 1) != 0.0,
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:204: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  df[old_cols].isna().sum(axis=1)[:, np.newaxis], len(old_cols), 1
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:213: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  df[to_allocate][:, np.newaxis],
/opt/anaconda3/envs/gencost/lib/python3.11/site-packages/etoolbox/utils/pudl_helpers.py:146: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[date_mask, date_col] = pd.to_datetime(
/opt/anaconda3/envs/gencost/lib/python3.11/site-packages/etoolbox/utils/pudl_helpers.py:146: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[date_mask, date_col] = pd.to_datetime(
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:258: UserWarning: This crosswalk is not safe, it may have `pf_subplants with multiple primes. Use `safe_xwalk` instead.
  return self._xwalk.grand_crosswalk
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:199: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  np.repeat(df[old_cols].sum(axis=1)[:, np.newaxis], len(old_cols), 1) != 0.0,
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:204: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  df[old_cols].isna().sum(axis=1)[:, np.newaxis], len(old_cols), 1
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:213: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  df[to_allocate][:, np.newaxis],
/opt/anaconda3/envs/gencost/lib/python3.11/site-packages/etoolbox/utils/pudl_helpers.py:146: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[date_mask, date_col] = pd.to_datetime(
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:258: UserWarning: This crosswalk is not safe, it may have `pf_subplants with multiple primes. Use `safe_xwalk` instead.
  return self._xwalk.grand_crosswalk
/opt/anaconda3/envs/gencost/lib/python3.11/site-packages/etoolbox/utils/pudl_helpers.py:146: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[date_mask, date_col] = pd.to_datetime(
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:2375: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  split = pd.DataFrame([pd.Series(x) for x in missing_years.years_to_fill_in])

TypeError: 'DataFrame' object is not callable

In [5]:
missing_data_w_score.dtypes

plant_id_eia                     Int64
generator_id                    object
year                             Int64
fuss                            object
prime_mover                     string
fuel_group                      object
final_ba_code                   object
age_in_current_year            float64
essentials                      string
ba_plus_essentials              string
age_range                     category
ba_plus_age                     string
essentials_present               int64
ba_plus_age_present              int64
ba_plus_essentials_present       int64
fill_in_score                    int64
dtype: object

In [174]:
missing_data_w_score['test'] = missing_data_w_score['essentials_present'] + missing_data_w_score['ba_plus_present']

In [6]:
missing_data_w_score

,plant_id_eia,generator_id,year,fuss,prime_mover,fuel_group,final_ba_code,age_in_current_year,essentials,ba_plus_essentials,age_range,ba_plus_age,essentials_present,ba_plus_age_present,ba_plus_essentials_present,fill_in_score
0,3,3,2016,missing_years,ST,natural_gas,2,NaN,2016_ST_natural_gas,2016_ST_natural_gas_2,NaN,2016_ST_natural_gas_2_nan,1,0,1,2
14,3,A1CT2,2008,missing_years,CC,natural_gas,2,NaN,2008_CC_natural_gas,2008_CC_natural_gas_2,NaN,2008_CC_natural_gas_2_nan,1,0,1,2
28,8,10,2019,missing_years,ST,coal,2,NaN,2019_ST_coal,2019_ST_coal_2,NaN,2019_ST_coal_2_nan,1,0,1,2
46,8,6,2016,missing_years,ST,coal,2,NaN,2016_ST_coal,2016_ST_coal_2,NaN,2016_ST_coal_2_nan,1,0,1,2
60,8,7,2016,missing_years,ST,coal,2,NaN,2016_ST_coal,2016_ST_coal_2,NaN,2016_ST_coal_2_nan,1,0,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2392,55505,BR2,2016,fuel_switch,GT,petroleum,529,19.586585,2016_GT_petroleum,2016_GT_petroleum_529,2,2016_GT_petroleum_529_2,1,1,1,3
2393,55505,BR2,2017,fuel_switch,GT,petroleum,529,19.586585,2017_GT_petroleum,2017_GT_petroleum_529,2,2017_GT_petroleum_529_2,1,1,1,3
2394,55505,BR2,2018,fuel_switch,GT,petroleum,529,19.586585,2018_GT_petroleum,2018_GT_petroleum_529,2,2018_GT_petroleum_529_2,1,1,1,3
2395,55505,BR2,2019,fuel_switch,GT,petroleum,529,19.586585,2019_GT_petroleum,2019_GT_petroleum_529,2,2019_GT_petroleum_529_2,1,1,1,3
2396,55505,BR2,2020,fuel_switch,GT,petroleum,529,19.586585,2020_GT_petroleum,2020_GT_petroleum_529,2,2020_GT_petroleum_529_2,1,1,1,3

In [10]:
missing_data_w_score.query('fill_in_score == 3',engine='python')

,plant_id_eia,generator_id,year,fuss,prime_mover,fuel_group,final_ba_code,age_in_current_year,essentials,ba_plus_essentials,age_range,ba_plus_age,essentials_present,ba_plus_age_present,ba_plus_essentials_present,fill_in_score
0,7527,2,2012,fuel_switch,CC,natural_gas,CAISO,26.168378,2012_CC_natural_gas,2012_CC_natural_gas_CAISO,3,2012_CC_natural_gas_CAISO_3,1,1,1,3
1,10333,GEN1,2013,fuel_switch,ST,coal,FPC,33.500342,2013_ST_coal,2013_ST_coal_FPC,4,2013_ST_coal_FPC_4,1,1,1,3
2,10333,GEN1,2014,fuel_switch,ST,coal,FPC,33.500342,2014_ST_coal,2014_ST_coal_FPC,4,2014_ST_coal_FPC_4,1,1,1,3
3,10333,GEN1,2015,fuel_switch,ST,coal,FPC,33.500342,2015_ST_coal,2015_ST_coal_FPC,4,2015_ST_coal_FPC_4,1,1,1,3
4,10333,GEN1,2016,fuel_switch,ST,coal,FPC,33.500342,2016_ST_coal,2016_ST_coal_FPC,4,2016_ST_coal_FPC_4,1,1,1,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2392,55505,BR2,2016,fuel_switch,GT,petroleum,529,19.586585,2016_GT_petroleum,2016_GT_petroleum_529,2,2016_GT_petroleum_529_2,1,1,1,3
2393,55505,BR2,2017,fuel_switch,GT,petroleum,529,19.586585,2017_GT_petroleum,2017_GT_petroleum_529,2,2017_GT_petroleum_529_2,1,1,1,3
2394,55505,BR2,2018,fuel_switch,GT,petroleum,529,19.586585,2018_GT_petroleum,2018_GT_petroleum_529,2,2018_GT_petroleum_529_2,1,1,1,3
2395,55505,BR2,2019,fuel_switch,GT,petroleum,529,19.586585,2019_GT_petroleum,2019_GT_petroleum_529,2,2019_GT_petroleum_529_2,1,1,1,3
2396,55505,BR2,2020,fuel_switch,GT,petroleum,529,19.586585,2020_GT_petroleum,2020_GT_petroleum_529,2,2020_GT_petroleum_529_2,1,1,1,3

In [16]:
#from gencost.waterfall import create_fill_in_ep_thresholds

xwalk = self.xwalk

hist_data = (
    self.get_exa_by_generator()
    .merge(
        xwalk[["plant_id_eia", "generator_id", "prime_mover", "fuel_group"]],
        on=["plant_id_eia", "generator_id", "prime_mover"],
        how="left",
    )
    .assign(year=lambda x: x["report_date"].dt.year)
    .pipe(self.create_fill_in_ep_thresholds)
)

/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:258: UserWarning: This crosswalk is not safe, it may have `pf_subplants with multiple primes. Use `safe_xwalk` instead.
  return self._xwalk.grand_crosswalk
/opt/anaconda3/envs/gencost/lib/python3.11/site-packages/etoolbox/utils/pudl_helpers.py:146: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[date_mask, date_col] = pd.to_datetime(
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:258: UserWarning: This crosswalk is not safe, it may have `pf_subplants with multiple primes. Use `safe_xwalk` instead.
  return self._xwalk.grand_crosswalk
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:199: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  np.repeat(df[old_cols].sum(axis=1)[:, np.newaxis], len(old_cols), 1) != 0.0,
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:204: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  df[old_cols].isna().sum(axis=1)[:, np.newaxis], len(old_cols), 1
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:213: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  df[to_allocate][:, np.newaxis],
/opt/anaconda3/envs/gencost/lib/python3.11/site-packages/etoolbox/utils/pudl_helpers.py:146: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[date_mask, date_col] = pd.to_datetime(

In [18]:
missing_data_w_score

,plant_id_eia,generator_id,year,fuss,prime_mover,fuel_group,final_ba_code,age_in_current_year,essentials,ba_plus_essentials,age_range,ba_plus_age,essentials_present,ba_plus_age_present,ba_plus_essentials_present,fill_in_score
0,3,3,2016,missing_years,ST,natural_gas,2,NaN,2016_ST_natural_gas,2016_ST_natural_gas_2,NaN,2016_ST_natural_gas_2_nan,1,0,1,2
14,3,A1CT2,2008,missing_years,CC,natural_gas,2,NaN,2008_CC_natural_gas,2008_CC_natural_gas_2,NaN,2008_CC_natural_gas_2_nan,1,0,1,2
28,8,10,2019,missing_years,ST,coal,2,NaN,2019_ST_coal,2019_ST_coal_2,NaN,2019_ST_coal_2_nan,1,0,1,2
46,8,6,2016,missing_years,ST,coal,2,NaN,2016_ST_coal,2016_ST_coal_2,NaN,2016_ST_coal_2_nan,1,0,1,2
60,8,7,2016,missing_years,ST,coal,2,NaN,2016_ST_coal,2016_ST_coal_2,NaN,2016_ST_coal_2_nan,1,0,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2392,55505,BR2,2016,fuel_switch,GT,petroleum,529,19.586585,2016_GT_petroleum,2016_GT_petroleum_529,2,2016_GT_petroleum_529_2,1,1,1,3
2393,55505,BR2,2017,fuel_switch,GT,petroleum,529,19.586585,2017_GT_petroleum,2017_GT_petroleum_529,2,2017_GT_petroleum_529_2,1,1,1,3
2394,55505,BR2,2018,fuel_switch,GT,petroleum,529,19.586585,2018_GT_petroleum,2018_GT_petroleum_529,2,2018_GT_petroleum_529_2,1,1,1,3
2395,55505,BR2,2019,fuel_switch,GT,petroleum,529,19.586585,2019_GT_petroleum,2019_GT_petroleum_529,2,2019_GT_petroleum_529_2,1,1,1,3
2396,55505,BR2,2020,fuel_switch,GT,petroleum,529,19.586585,2020_GT_petroleum,2020_GT_petroleum_529,2,2020_GT_petroleum_529_2,1,1,1,3

In [17]:
hist_data

,plant_id_eia,generator_id,report_date,biofuel_mmbtu,coal_mmbtu,natural_gas_mmbtu,nuclear_mmbtu,other_mmbtu,other_gas_mmbtu,petroleum_mmbtu,...,final_respondent_id,final_ba_code,wage_scale,age_of_observation_secular_adj,fuel_group,year,essentials,ba_plus_essentials,age_range,ba_plus_age
0,3,1,2006-01-01,NaN,1.008871e+07,2.951150e+04,NaN,NaN,NaN,NaN,...,2,2,1.050357,13.40423,coal,2006,2006_ST_coal,2006_ST_coal_2,7,2006_ST_coal_2_7
1,3,1,2006-01-01,NaN,1.008871e+07,2.951150e+04,NaN,NaN,NaN,NaN,...,2,2,1.050357,13.40423,natural_gas,2006,2006_ST_natural_gas,2006_ST_natural_gas_2,7,2006_ST_natural_gas_2_7
2,3,1,2007-01-01,NaN,9.807031e+06,NaN,NaN,NaN,NaN,NaN,...,2,2,1.057435,14.461664,coal,2007,2007_ST_coal,2007_ST_coal_2,7,2007_ST_coal_2_7
3,3,1,2007-01-01,NaN,9.807031e+06,NaN,NaN,NaN,NaN,NaN,...,2,2,1.057435,14.461664,natural_gas,2007,2007_ST_natural_gas,2007_ST_natural_gas_2,7,2007_ST_natural_gas_2_7
4,3,1,2008-01-01,NaN,8.176078e+06,NaN,NaN,NaN,NaN,NaN,...,2,2,0.99812,15.459785,coal,2008,2008_ST_coal,2008_ST_coal_2,7,2008_ST_coal_2_7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133749,60926,1C,2019-01-01,NaN,NaN,0.000000e+00,NaN,NaN,NaN,NaN,...,454,ETR,0.923801,24.360724,natural_gas,2019,2019_CC_natural_gas,2019_CC_natural_gas_ETR,1,2019_CC_natural_gas_ETR_1
133750,60926,1C,2020-01-01,NaN,NaN,0.000000e+00,NaN,NaN,NaN,NaN,...,454,ETR,0.964819,25.325543,natural_gas,2020,2020_CC_natural_gas,2020_CC_natural_gas_ETR,1,2020_CC_natural_gas_ETR_1
133751,60927,1A,2020-01-01,NaN,NaN,1.202763e+07,NaN,NaN,NaN,NaN,...,454,ETR,0.964819,25.325543,natural_gas,2020,2020_CC_natural_gas,2020_CC_natural_gas_ETR,1,2020_CC_natural_gas_ETR_1
133752,60927,1B,2020-01-01,NaN,NaN,1.202763e+07,NaN,NaN,NaN,NaN,...,454,ETR,0.964819,25.325543,natural_gas,2020,2020_CC_natural_gas,2020_CC_natural_gas_ETR,1,2020_CC_natural_gas_ETR_1
133753,60927,1C,2020-01-01,NaN,NaN,0.000000e+00,NaN,NaN,NaN,NaN,...,454,ETR,0.964819,25.325543,natural_gas,2020,2020_CC_natural_gas,2020_CC_natural_gas_ETR,1,2020_CC_natural_gas_ETR_1

In [20]:
missing_data_w_score.query('fill_in_score ==2')

,plant_id_eia,generator_id,year,fuss,prime_mover,fuel_group,final_ba_code,age_in_current_year,essentials,ba_plus_essentials,age_range,ba_plus_age,essentials_present,ba_plus_age_present,ba_plus_essentials_present,fill_in_score
0,3,3,2016,missing_years,ST,natural_gas,2,NaN,2016_ST_natural_gas,2016_ST_natural_gas_2,NaN,2016_ST_natural_gas_2_nan,1,0,1,2
14,3,A1CT2,2008,missing_years,CC,natural_gas,2,NaN,2008_CC_natural_gas,2008_CC_natural_gas_2,NaN,2008_CC_natural_gas_2_nan,1,0,1,2
28,8,10,2019,missing_years,ST,coal,2,NaN,2019_ST_coal,2019_ST_coal_2,NaN,2019_ST_coal_2_nan,1,0,1,2
46,8,6,2016,missing_years,ST,coal,2,NaN,2016_ST_coal,2016_ST_coal_2,NaN,2016_ST_coal_2_nan,1,0,1,2
60,8,7,2016,missing_years,ST,coal,2,NaN,2016_ST_coal,2016_ST_coal_2,NaN,2016_ST_coal_2_nan,1,0,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2346,55088,ST1,2011,fuel_switch,ST,other_gas,MISO,20.334018,2011_ST_other_gas,2011_ST_other_gas_MISO,3,2011_ST_other_gas_MISO_3,1,0,1,2
2347,55088,ST1,2011,fuel_switch,ST,other_gas,MISO,20.334018,2011_ST_other_gas,2011_ST_other_gas_MISO,3,2011_ST_other_gas_MISO_3,1,0,1,2
2348,55088,ST1,2011,fuel_switch,ST,other_gas,MISO,20.334018,2011_ST_other_gas,2011_ST_other_gas_MISO,3,2011_ST_other_gas_MISO_3,1,0,1,2
2349,55088,ST1,2011,fuel_switch,ST,other_gas,MISO,20.334018,2011_ST_other_gas,2011_ST_other_gas_MISO,3,2011_ST_other_gas_MISO_3,1,0,1,2
2350,55088,ST1,2011,fuel_switch,ST,other_gas,MISO,20.334018,2011_ST_other_gas,2011_ST_other_gas_MISO,3,2011_ST_other_gas_MISO_3,1,0,1,2

In [21]:
hist_data

,plant_id_eia,generator_id,report_date,biofuel_mmbtu,coal_mmbtu,natural_gas_mmbtu,nuclear_mmbtu,other_mmbtu,other_gas_mmbtu,petroleum_mmbtu,...,final_respondent_id,final_ba_code,wage_scale,age_of_observation_secular_adj,fuel_group,year,essentials,ba_plus_essentials,age_range,ba_plus_age
0,3,1,2006-01-01,NaN,1.008871e+07,2.951150e+04,NaN,NaN,NaN,NaN,...,2,2,1.050357,13.40423,coal,2006,2006_ST_coal,2006_ST_coal_2,7,2006_ST_coal_2_7
1,3,1,2006-01-01,NaN,1.008871e+07,2.951150e+04,NaN,NaN,NaN,NaN,...,2,2,1.050357,13.40423,natural_gas,2006,2006_ST_natural_gas,2006_ST_natural_gas_2,7,2006_ST_natural_gas_2_7
2,3,1,2007-01-01,NaN,9.807031e+06,NaN,NaN,NaN,NaN,NaN,...,2,2,1.057435,14.461664,coal,2007,2007_ST_coal,2007_ST_coal_2,7,2007_ST_coal_2_7
3,3,1,2007-01-01,NaN,9.807031e+06,NaN,NaN,NaN,NaN,NaN,...,2,2,1.057435,14.461664,natural_gas,2007,2007_ST_natural_gas,2007_ST_natural_gas_2,7,2007_ST_natural_gas_2_7
4,3,1,2008-01-01,NaN,8.176078e+06,NaN,NaN,NaN,NaN,NaN,...,2,2,0.99812,15.459785,coal,2008,2008_ST_coal,2008_ST_coal_2,7,2008_ST_coal_2_7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133749,60926,1C,2019-01-01,NaN,NaN,0.000000e+00,NaN,NaN,NaN,NaN,...,454,ETR,0.923801,24.360724,natural_gas,2019,2019_CC_natural_gas,2019_CC_natural_gas_ETR,1,2019_CC_natural_gas_ETR_1
133750,60926,1C,2020-01-01,NaN,NaN,0.000000e+00,NaN,NaN,NaN,NaN,...,454,ETR,0.964819,25.325543,natural_gas,2020,2020_CC_natural_gas,2020_CC_natural_gas_ETR,1,2020_CC_natural_gas_ETR_1
133751,60927,1A,2020-01-01,NaN,NaN,1.202763e+07,NaN,NaN,NaN,NaN,...,454,ETR,0.964819,25.325543,natural_gas,2020,2020_CC_natural_gas,2020_CC_natural_gas_ETR,1,2020_CC_natural_gas_ETR_1
133752,60927,1B,2020-01-01,NaN,NaN,1.202763e+07,NaN,NaN,NaN,NaN,...,454,ETR,0.964819,25.325543,natural_gas,2020,2020_CC_natural_gas,2020_CC_natural_gas_ETR,1,2020_CC_natural_gas_ETR_1
133753,60927,1C,2020-01-01,NaN,NaN,0.000000e+00,NaN,NaN,NaN,NaN,...,454,ETR,0.964819,25.325543,natural_gas,2020,2020_CC_natural_gas,2020_CC_natural_gas_ETR,1,2020_CC_natural_gas_ETR_1

In [27]:
hist_data.query('final_ba_code.isnull()')

,plant_id_eia,generator_id,report_date,biofuel_mmbtu,coal_mmbtu,natural_gas_mmbtu,nuclear_mmbtu,other_mmbtu,other_gas_mmbtu,petroleum_mmbtu,...,final_respondent_id,final_ba_code,wage_scale,age_of_observation_secular_adj,fuel_group,year,essentials,ba_plus_essentials,age_range,ba_plus_age
3640,310,2,2006-01-01,NaN,NaN,2.043756e+06,NaN,NaN,NaN,640.089648,...,<NA>,None,1.218299,15.045379,natural_gas,2006,2006_ST_natural_gas,<NA>,6,<NA>
3641,310,2,2006-01-01,NaN,NaN,2.043756e+06,NaN,NaN,NaN,640.089648,...,<NA>,None,1.218299,15.045379,petroleum,2006,2006_ST_petroleum,<NA>,6,<NA>
3642,310,2,2007-01-01,NaN,NaN,1.481319e+06,NaN,NaN,NaN,1149.303824,...,<NA>,None,1.205149,16.250528,natural_gas,2007,2007_ST_natural_gas,<NA>,6,<NA>
3643,310,2,2007-01-01,NaN,NaN,1.481319e+06,NaN,NaN,NaN,1149.303824,...,<NA>,None,1.205149,16.250528,petroleum,2007,2007_ST_petroleum,<NA>,6,<NA>
3644,310,2,2008-01-01,NaN,NaN,2.234114e+06,NaN,NaN,NaN,0.000000,...,<NA>,None,1.172143,17.422671,natural_gas,2008,2008_ST_natural_gas,<NA>,6,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133422,59073,5STB,2020-01-01,NaN,NaN,1.209106e+06,NaN,NaN,NaN,NaN,...,<NA>,NaN,1.151084,31.796804,natural_gas,2020,2020_ST_natural_gas,<NA>,1,<NA>
133423,59073,5STB,2020-01-01,NaN,NaN,1.209106e+06,NaN,NaN,NaN,NaN,...,<NA>,NaN,1.151084,31.796804,other,2020,2020_ST_other,<NA>,1,<NA>
133424,59073,5STB,2020-01-01,NaN,NaN,1.209106e+06,NaN,NaN,NaN,NaN,...,<NA>,NaN,1.151084,31.796804,natural_gas,2020,2020_ST_natural_gas,<NA>,1,<NA>
133425,59073,5STB,2020-01-01,NaN,NaN,1.209106e+06,NaN,NaN,NaN,NaN,...,<NA>,NaN,1.151084,31.796804,other,2020,2020_ST_other,<NA>,1,<NA>
133426,59073,5STB,2020-01-01,NaN,NaN,1.209106e+06,NaN,NaN,NaN,NaN,...,<NA>,NaN,1.151084,31.796804,natural_gas,2020,2020_ST_natural_gas,<NA>,1,<NA>

In [28]:
missing_data_w_score.query('final_ba_code.isnull()')

,plant_id_eia,generator_id,year,fuss,prime_mover,fuel_group,final_ba_code,age_in_current_year,essentials,ba_plus_essentials,age_range,ba_plus_age,essentials_present,ba_plus_age_present,ba_plus_essentials_present,fill_in_score
922,310,2,2016,missing_years,ST,petroleum,None,NaN,2016_ST_petroleum,<NA>,NaN,<NA>,1,0,1,2
932,310,3,2016,missing_years,ST,natural_gas,None,NaN,2016_ST_natural_gas,<NA>,NaN,<NA>,1,0,1,2
940,310,4,2016,missing_years,ST,natural_gas,None,NaN,2016_ST_natural_gas,<NA>,NaN,<NA>,1,0,1,2
1961,603,15,2016,missing_years,ST,petroleum,None,NaN,2016_ST_petroleum,<NA>,NaN,<NA>,1,0,1,2
1972,603,16,2016,missing_years,ST,petroleum,None,NaN,2016_ST_petroleum,<NA>,NaN,<NA>,1,0,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140623,2864,1,2015,missing_years,ST,coal,NaN,NaN,2015_ST_coal,<NA>,NaN,<NA>,1,0,1,2
140626,2864,2,2015,missing_years,ST,coal,NaN,NaN,2015_ST_coal,<NA>,NaN,<NA>,1,0,1,2
140667,7945,1,2015,missing_years,GT,natural_gas,None,NaN,2015_GT_natural_gas,<NA>,NaN,<NA>,1,0,1,2
140726,55858,UNT1,2015,missing_years,GT,natural_gas,None,NaN,2015_GT_natural_gas,<NA>,NaN,<NA>,1,0,1,2
140732,55858,UNT2,2015,missing_years,GT,natural_gas,None,NaN,2015_GT_natural_gas,<NA>,NaN,<NA>,1,0,1,2

In [22]:
(missing_data_w_score.query('fill_in_score ==2')
.merge(hist_data,on=['ba_plus_age'],how='left',indicator=True)
.query('_merge == "both"'))

,plant_id_eia_x,generator_id_x,year_x,fuss,prime_mover_x,fuel_group_x,final_ba_code_x,age_in_current_year_x,essentials_x,ba_plus_essentials_x,...,final_respondent_id,final_ba_code_y,wage_scale,age_of_observation_secular_adj,fuel_group_y,year_y,essentials_y,ba_plus_essentials_y,age_range_y,_merge
70,310,2,2016,missing_years,ST,petroleum,None,NaN,2016_ST_petroleum,<NA>,...,543,WALC,1.054843,14.07461,NaN,2006.0,<NA>,<NA>,6,both
71,310,2,2016,missing_years,ST,petroleum,None,NaN,2016_ST_petroleum,<NA>,...,543,WALC,1.081905,15.156515,NaN,2007.0,<NA>,<NA>,6,both
72,310,2,2016,missing_years,ST,petroleum,None,NaN,2016_ST_petroleum,<NA>,...,543,WALC,1.076,16.232515,NaN,2008.0,<NA>,<NA>,6,both
73,310,2,2016,missing_years,ST,petroleum,None,NaN,2016_ST_petroleum,<NA>,...,543,WALC,1.106098,17.338612,NaN,2009.0,<NA>,<NA>,6,both
74,310,2,2016,missing_years,ST,petroleum,None,NaN,2016_ST_petroleum,<NA>,...,543,WALC,1.069515,18.408127,NaN,2010.0,<NA>,<NA>,6,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
370303,55858,UNT2,2015,missing_years,GT,natural_gas,None,NaN,2015_GT_natural_gas,<NA>,...,<NA>,NaN,1.151084,31.796804,natural_gas,2020.0,2020_ST_natural_gas,<NA>,1,both
370304,55858,UNT2,2015,missing_years,GT,natural_gas,None,NaN,2015_GT_natural_gas,<NA>,...,<NA>,NaN,1.151084,31.796804,other,2020.0,2020_ST_other,<NA>,1,both
370305,55858,UNT2,2015,missing_years,GT,natural_gas,None,NaN,2015_GT_natural_gas,<NA>,...,<NA>,NaN,1.151084,31.796804,natural_gas,2020.0,2020_ST_natural_gas,<NA>,1,both
370306,55858,UNT2,2015,missing_years,GT,natural_gas,None,NaN,2015_GT_natural_gas,<NA>,...,<NA>,NaN,1.151084,31.796804,other,2020.0,2020_ST_other,<NA>,1,both
370307,55858,UNT2,2015,missing_years,GT,natural_gas,None,NaN,2015_GT_natural_gas,<NA>,...,<NA>,NaN,1.151084,31.796804,natural_gas,2020.0,2020_ST_natural_gas,<NA>,1,both

In [30]:
xwalk = self.xwalk

hist_data = (
    self.get_exa_by_generator()
    .merge(
        xwalk[["plant_id_eia", "generator_id", "prime_mover", "fuel_group"]],
        on=["plant_id_eia", "generator_id", "prime_mover"],
        how="left",
    )
    .assign(year=lambda x: x["report_date"].dt.year)
    .pipe(self.create_fill_in_ep_thresholds)
)

/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:258: UserWarning: This crosswalk is not safe, it may have `pf_subplants with multiple primes. Use `safe_xwalk` instead.
  return self._xwalk.grand_crosswalk
/opt/anaconda3/envs/gencost/lib/python3.11/site-packages/etoolbox/utils/pudl_helpers.py:146: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[date_mask, date_col] = pd.to_datetime(
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:258: UserWarning: This crosswalk is not safe, it may have `pf_subplants with multiple primes. Use `safe_xwalk` instead.
  return self._xwalk.grand_crosswalk
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:199: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  np.repeat(df[old_cols].sum(axis=1)[:, np.newaxis], len(old_cols), 1) != 0.0,
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:204: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  df[old_cols].isna().sum(axis=1)[:, np.newaxis], len(old_cols), 1
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:213: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  df[to_allocate][:, np.newaxis],
/opt/anaconda3/envs/gencost/lib/python3.11/site-packages/etoolbox/utils/pudl_helpers.py:146: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[date_mask, date_col] = pd.to_datetime(

In [ ]:
 .assign(
            ba_plus_age_present=lambda x: np.where(
                (x["final_ba_code"].isnull())
                | (x["final_ba_code"].isna() | x(["age_in_current_year"])),
                0,
                x["ba_plus_age_present"],
            ),
            ba_plus_essentials_present=lambda x: np.where(
                (x["final_ba_code"].isnull()) | (x["final_ba_code"].isna()),
                0,
                x["ba_plus_essentials_present"],
            ),
            fill_in_score=lambda x: x["essentials_present"]
            + x["ba_plus_essentials_present"]
            + x["ba_plus_age_present"],
        )
    )

In [ ]:
        ba_plus_age_present=lambda x: np.where(
                x["ba_plus_age"].isin(hist_data["ba_plus_age"]),
                1,
                0,
            ),
        )# make an exception of when there is no ba code or age
)

In [35]:
missing_data.assign(
            ba_plus_essentials_present=lambda x: np.where(
                x["ba_plus_essentials"].isin(hist_data["ba_plus_essentials"]),
                1,
               
            )

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

In [32]:
missing_data = (
        self.find_missing_data()
        .pipe(self.create_fill_in_ep_thresholds)
        .assign(
            essentials_present=lambda x: np.where(
                x["essentials"].isin(hist_data["essentials"]), 1, 0
            ),
            ba_plus_essentials_present=lambda x: np.where(
                x["ba_plus_essentials"].isin(hist_data["ba_plus_essentials"]),
                1,
                np.where(
                (x["final_ba_code"].isnull()) | (x["final_ba_code"].isna()),
                0,
                x["ba_plus_essentials_present"],
            ),0,
            )))

/opt/anaconda3/envs/gencost/lib/python3.11/site-packages/etoolbox/utils/pudl_helpers.py:146: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[date_mask, date_col] = pd.to_datetime(
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:258: UserWarning: This crosswalk is not safe, it may have `pf_subplants with multiple primes. Use `safe_xwalk` instead.
  return self._xwalk.grand_crosswalk
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:199: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  np.repeat(df[old_cols].sum(axis=1)[:, np.newaxis], len(old_cols), 1) != 0.0,
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:204: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  df[old_cols].isna().sum(axis=1)[:, np.newaxis], len(old_cols), 1
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:213: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  df[to_allocate][:, np.newaxis],
/opt/anaconda3/envs/gencost/lib/python3.11/site-packages/etoolbox/utils/pudl_helpers.py:146: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[date_mask, date_col] = pd.to_datetime(
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:258: UserWarning: This crosswalk is not safe, it may have `pf_subplants with multiple primes. Use `safe_xwalk` instead.
  return self._xwalk.grand_crosswalk
/opt/anaconda3/envs/gencost/lib/python3.11/site-packages/etoolbox/utils/pudl_helpers.py:146: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[date_mask, date_col] = pd.to_datetime(
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:2375: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  split = pd.DataFrame([pd.Series(x) for x in missing_years.years_to_fill_in])

In [37]:

missing_data = (
    self.find_missing_data()
    .pipe(self.create_fill_in_ep_thresholds)
    .assign(
        essentials_present=lambda x: np.where(
            x["essentials"].isin(hist_data["essentials"]), 1, 0
        ),
        ba_plus_essentials_present=lambda x: np.where(
            x["ba_plus_essentials"].isin(hist_data["ba_plus_essentials"]),
            1,
            0,
        ),
        ba_plus_age_present=lambda x: np.where(
            x["ba_plus_age"].isin(hist_data["ba_plus_age"]),
            1,
            0,
        ),
    )  # make score 0's when na's in ba code or age
    .assign(
        ba_plus_age_present=lambda x: np.where(
            (x["final_ba_code"].isnull())
            | (x["final_ba_code"].isna())
            | (x["age_in_current_year"].isna()) | (x["age_in_current_year"].isnull()),
            0,
            x["ba_plus_age_present"],
        ),
        ba_plus_essentials_present=lambda x: np.where(
            (x["final_ba_code"].isnull()) | (x["final_ba_code"].isna()),
            0,
            x["ba_plus_essentials_present"],
        ),
        fill_in_score=lambda x: x["essentials_present"]
        + x["ba_plus_essentials_present"]
        + x["ba_plus_age_present"],
    )
)

/opt/anaconda3/envs/gencost/lib/python3.11/site-packages/etoolbox/utils/pudl_helpers.py:146: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[date_mask, date_col] = pd.to_datetime(
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:258: UserWarning: This crosswalk is not safe, it may have `pf_subplants with multiple primes. Use `safe_xwalk` instead.
  return self._xwalk.grand_crosswalk
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:199: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  np.repeat(df[old_cols].sum(axis=1)[:, np.newaxis], len(old_cols), 1) != 0.0,
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:204: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  df[old_cols].isna().sum(axis=1)[:, np.newaxis], len(old_cols), 1
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:213: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  df[to_allocate][:, np.newaxis],
/opt/anaconda3/envs/gencost/lib/python3.11/site-packages/etoolbox/utils/pudl_helpers.py:146: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[date_mask, date_col] = pd.to_datetime(
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:258: UserWarning: This crosswalk is not safe, it may have `pf_subplants with multiple primes. Use `safe_xwalk` instead.
  return self._xwalk.grand_crosswalk
/opt/anaconda3/envs/gencost/lib/python3.11/site-packages/etoolbox/utils/pudl_helpers.py:146: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[date_mask, date_col] = pd.to_datetime(
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:2375: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  split = pd.DataFrame([pd.Series(x) for x in missing_years.years_to_fill_in])

In [50]:
missing_data.query('fill_in_score == 2')

,plant_id_eia,generator_id,year,fuss,prime_mover,fuel_group,final_ba_code,age_in_current_year,essentials,ba_plus_essentials,age_range,ba_plus_age,essentials_present,ba_plus_essentials_present,ba_plus_age_present,fill_in_score
0,3,3,2016,missing_years,ST,natural_gas,2,NaN,2016_ST_natural_gas,2016_ST_natural_gas_2,NaN,2016_ST_natural_gas_2_nan,1,1,0,2
14,3,A1CT2,2008,missing_years,CC,natural_gas,2,NaN,2008_CC_natural_gas,2008_CC_natural_gas_2,NaN,2008_CC_natural_gas_2_nan,1,1,0,2
28,8,10,2019,missing_years,ST,coal,2,NaN,2019_ST_coal,2019_ST_coal_2,NaN,2019_ST_coal_2_nan,1,1,0,2
46,8,6,2016,missing_years,ST,coal,2,NaN,2016_ST_coal,2016_ST_coal_2,NaN,2016_ST_coal_2_nan,1,1,0,2
60,8,7,2016,missing_years,ST,coal,2,NaN,2016_ST_coal,2016_ST_coal_2,NaN,2016_ST_coal_2_nan,1,1,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2346,55088,ST1,2011,fuel_switch,ST,other_gas,MISO,20.334018,2011_ST_other_gas,2011_ST_other_gas_MISO,3,2011_ST_other_gas_MISO_3,1,1,0,2
2347,55088,ST1,2011,fuel_switch,ST,other_gas,MISO,20.334018,2011_ST_other_gas,2011_ST_other_gas_MISO,3,2011_ST_other_gas_MISO_3,1,1,0,2
2348,55088,ST1,2011,fuel_switch,ST,other_gas,MISO,20.334018,2011_ST_other_gas,2011_ST_other_gas_MISO,3,2011_ST_other_gas_MISO_3,1,1,0,2
2349,55088,ST1,2011,fuel_switch,ST,other_gas,MISO,20.334018,2011_ST_other_gas,2011_ST_other_gas_MISO,3,2011_ST_other_gas_MISO_3,1,1,0,2
2350,55088,ST1,2011,fuel_switch,ST,other_gas,MISO,20.334018,2011_ST_other_gas,2011_ST_other_gas_MISO,3,2011_ST_other_gas_MISO_3,1,1,0,2

In [51]:
missing_data = self.fill_in_ep_data()

/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:258: UserWarning: This crosswalk is not safe, it may have `pf_subplants with multiple primes. Use `safe_xwalk` instead.
  return self._xwalk.grand_crosswalk
/opt/anaconda3/envs/gencost/lib/python3.11/site-packages/etoolbox/utils/pudl_helpers.py:146: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[date_mask, date_col] = pd.to_datetime(
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:258: UserWarning: This crosswalk is not safe, it may have `pf_subplants with multiple primes. Use `safe_xwalk` instead.
  return self._xwalk.grand_crosswalk
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:199: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  np.repeat(df[old_cols].sum(axis=1)[:, np.newaxis], len(old_cols), 1) != 0.0,
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:204: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  df[old_cols].isna().sum(axis=1)[:, np.newaxis], len(old_cols), 1
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:213: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  df[to_allocate][:, np.newaxis],
/opt/anaconda3/envs/gencost/lib/python3.11/site-packages/etoolbox/utils/pudl_helpers.py:146: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[date_mask, date_col] = pd.to_datetime(
/opt/anaconda3/envs/gencost/lib/python3.11/site-packages/etoolbox/utils/pudl_helpers.py:146: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[date_mask, date_col] = pd.to_datetime(
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:258: UserWarning: This crosswalk is not safe, it may have `pf_subplants with multiple primes. Use `safe_xwalk` instead.
  return self._xwalk.grand_crosswalk
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:199: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  np.repeat(df[old_cols].sum(axis=1)[:, np.newaxis], len(old_cols), 1) != 0.0,
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:204: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  df[old_cols].isna().sum(axis=1)[:, np.newaxis], len(old_cols), 1
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:213: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  df[to_allocate][:, np.newaxis],
/opt/anaconda3/envs/gencost/lib/python3.11/site-packages/etoolbox/utils/pudl_helpers.py:146: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[date_mask, date_col] = pd.to_datetime(
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:258: UserWarning: This crosswalk is not safe, it may have `pf_subplants with multiple primes. Use `safe_xwalk` instead.
  return self._xwalk.grand_crosswalk
/opt/anaconda3/envs/gencost/lib/python3.11/site-packages/etoolbox/utils/pudl_helpers.py:146: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[date_mask, date_col] = pd.to_datetime(
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:2375: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  split = pd.DataFrame([pd.Series(x) for x in missing_years.years_to_fill_in])

In [52]:
missing_data

,plant_id_eia,generator_id,year,fuss,prime_mover,fuel_group,final_ba_code,age_in_current_year,essentials,ba_plus_essentials,age_range,ba_plus_age,essentials_present,ba_plus_essentials_present,ba_plus_age_present,fill_in_score
0,3,3,2016,missing_years,ST,natural_gas,2,NaN,2016_ST_natural_gas,2016_ST_natural_gas_2,NaN,2016_ST_natural_gas_2_nan,1,1,0,2
14,3,A1CT2,2008,missing_years,CC,natural_gas,2,NaN,2008_CC_natural_gas,2008_CC_natural_gas_2,NaN,2008_CC_natural_gas_2_nan,1,1,0,2
28,8,10,2019,missing_years,ST,coal,2,NaN,2019_ST_coal,2019_ST_coal_2,NaN,2019_ST_coal_2_nan,1,1,0,2
46,8,6,2016,missing_years,ST,coal,2,NaN,2016_ST_coal,2016_ST_coal_2,NaN,2016_ST_coal_2_nan,1,1,0,2
60,8,7,2016,missing_years,ST,coal,2,NaN,2016_ST_coal,2016_ST_coal_2,NaN,2016_ST_coal_2_nan,1,1,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2392,55505,BR2,2016,fuel_switch,GT,petroleum,529,19.586585,2016_GT_petroleum,2016_GT_petroleum_529,2,2016_GT_petroleum_529_2,1,1,1,3
2393,55505,BR2,2017,fuel_switch,GT,petroleum,529,19.586585,2017_GT_petroleum,2017_GT_petroleum_529,2,2017_GT_petroleum_529_2,1,1,1,3
2394,55505,BR2,2018,fuel_switch,GT,petroleum,529,19.586585,2018_GT_petroleum,2018_GT_petroleum_529,2,2018_GT_petroleum_529_2,1,1,1,3
2395,55505,BR2,2019,fuel_switch,GT,petroleum,529,19.586585,2019_GT_petroleum,2019_GT_petroleum_529,2,2019_GT_petroleum_529_2,1,1,1,3
2396,55505,BR2,2020,fuel_switch,GT,petroleum,529,19.586585,2020_GT_petroleum,2020_GT_petroleum_529,2,2020_GT_petroleum_529_2,1,1,1,3

In [53]:
hist_data

,plant_id_eia,generator_id,report_date,biofuel_mmbtu,coal_mmbtu,natural_gas_mmbtu,nuclear_mmbtu,other_mmbtu,other_gas_mmbtu,petroleum_mmbtu,...,final_respondent_id,final_ba_code,wage_scale,age_of_observation_secular_adj,fuel_group,year,essentials,ba_plus_essentials,age_range,ba_plus_age
0,3,1,2006-01-01,NaN,1.008871e+07,2.951150e+04,NaN,NaN,NaN,NaN,...,2,2,1.050357,13.40423,coal,2006,2006_ST_coal,2006_ST_coal_2,7,2006_ST_coal_2_7
1,3,1,2006-01-01,NaN,1.008871e+07,2.951150e+04,NaN,NaN,NaN,NaN,...,2,2,1.050357,13.40423,natural_gas,2006,2006_ST_natural_gas,2006_ST_natural_gas_2,7,2006_ST_natural_gas_2_7
2,3,1,2007-01-01,NaN,9.807031e+06,NaN,NaN,NaN,NaN,NaN,...,2,2,1.057435,14.461664,coal,2007,2007_ST_coal,2007_ST_coal_2,7,2007_ST_coal_2_7
3,3,1,2007-01-01,NaN,9.807031e+06,NaN,NaN,NaN,NaN,NaN,...,2,2,1.057435,14.461664,natural_gas,2007,2007_ST_natural_gas,2007_ST_natural_gas_2,7,2007_ST_natural_gas_2_7
4,3,1,2008-01-01,NaN,8.176078e+06,NaN,NaN,NaN,NaN,NaN,...,2,2,0.99812,15.459785,coal,2008,2008_ST_coal,2008_ST_coal_2,7,2008_ST_coal_2_7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133749,60926,1C,2019-01-01,NaN,NaN,0.000000e+00,NaN,NaN,NaN,NaN,...,454,ETR,0.923801,24.360724,natural_gas,2019,2019_CC_natural_gas,2019_CC_natural_gas_ETR,1,2019_CC_natural_gas_ETR_1
133750,60926,1C,2020-01-01,NaN,NaN,0.000000e+00,NaN,NaN,NaN,NaN,...,454,ETR,0.964819,25.325543,natural_gas,2020,2020_CC_natural_gas,2020_CC_natural_gas_ETR,1,2020_CC_natural_gas_ETR_1
133751,60927,1A,2020-01-01,NaN,NaN,1.202763e+07,NaN,NaN,NaN,NaN,...,454,ETR,0.964819,25.325543,natural_gas,2020,2020_CC_natural_gas,2020_CC_natural_gas_ETR,1,2020_CC_natural_gas_ETR_1
133752,60927,1B,2020-01-01,NaN,NaN,1.202763e+07,NaN,NaN,NaN,NaN,...,454,ETR,0.964819,25.325543,natural_gas,2020,2020_CC_natural_gas,2020_CC_natural_gas_ETR,1,2020_CC_natural_gas_ETR_1
133753,60927,1C,2020-01-01,NaN,NaN,0.000000e+00,NaN,NaN,NaN,NaN,...,454,ETR,0.964819,25.325543,natural_gas,2020,2020_CC_natural_gas,2020_CC_natural_gas_ETR,1,2020_CC_natural_gas_ETR_1

In [75]:
missing_data

,plant_id_eia,generator_id,year,fuss,prime_mover,fuel_group,final_ba_code,age_in_current_year,essentials,ba_plus_essentials,age_range,ba_plus_age,essentials_present,ba_plus_essentials_present,ba_plus_age_present,fill_in_score
0,3,3,2016,missing_years,ST,natural_gas,2,NaN,2016_ST_natural_gas,2016_ST_natural_gas_2,NaN,2016_ST_natural_gas_2_nan,1,1,0,2
14,3,A1CT2,2008,missing_years,CC,natural_gas,2,NaN,2008_CC_natural_gas,2008_CC_natural_gas_2,NaN,2008_CC_natural_gas_2_nan,1,1,0,2
28,8,10,2019,missing_years,ST,coal,2,NaN,2019_ST_coal,2019_ST_coal_2,NaN,2019_ST_coal_2_nan,1,1,0,2
46,8,6,2016,missing_years,ST,coal,2,NaN,2016_ST_coal,2016_ST_coal_2,NaN,2016_ST_coal_2_nan,1,1,0,2
60,8,7,2016,missing_years,ST,coal,2,NaN,2016_ST_coal,2016_ST_coal_2,NaN,2016_ST_coal_2_nan,1,1,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2392,55505,BR2,2016,fuel_switch,GT,petroleum,529,19.586585,2016_GT_petroleum,2016_GT_petroleum_529,2,2016_GT_petroleum_529_2,1,1,1,3
2393,55505,BR2,2017,fuel_switch,GT,petroleum,529,19.586585,2017_GT_petroleum,2017_GT_petroleum_529,2,2017_GT_petroleum_529_2,1,1,1,3
2394,55505,BR2,2018,fuel_switch,GT,petroleum,529,19.586585,2018_GT_petroleum,2018_GT_petroleum_529,2,2018_GT_petroleum_529_2,1,1,1,3
2395,55505,BR2,2019,fuel_switch,GT,petroleum,529,19.586585,2019_GT_petroleum,2019_GT_petroleum_529,2,2019_GT_petroleum_529_2,1,1,1,3
2396,55505,BR2,2020,fuel_switch,GT,petroleum,529,19.586585,2020_GT_petroleum,2020_GT_petroleum_529,2,2020_GT_petroleum_529_2,1,1,1,3

In [57]:
pd.set_option('display.max_columns',None)

In [59]:
(missing_data.query('fill_in_score ==2')
.merge(hist_data,on=['ba_plus_age'],how='left',indicator=True)
.query('_merge == "both"'))

Empty DataFrame
Columns: [plant_id_eia_x, generator_id_x, year_x, fuss, prime_mover_x, fuel_group_x, final_ba_code_x, age_in_current_year_x, essentials_x, ba_plus_essentials_x, age_range_x, ba_plus_age, essentials_present, ba_plus_essentials_present, ba_plus_age_present, fill_in_score, plant_id_eia_y, generator_id_y, report_date, biofuel_mmbtu, coal_mmbtu, natural_gas_mmbtu, nuclear_mmbtu, other_mmbtu, other_gas_mmbtu, petroleum_mmbtu, petroleum_coke_mmbtu, renew_mmbtu, biofuel_net_mwh, coal_net_mwh, natural_gas_net_mwh, nuclear_net_mwh, other_net_mwh, other_gas_net_mwh, petroleum_net_mwh, petroleum_coke_net_mwh, renew_net_mwh, generator_starts, fuel_starts, gross_generation_mwh, biofuel_gross_mwh, coal_gross_mwh, natural_gas_gross_mwh, other_gross_mwh, other_gas_gross_mwh, petroleum_gross_mwh, petroleum_coke_gross_mwh, renew_gross_mwh, utility_id_eia, balancing_authority_code_eia, state, capacity_mw, prime_mover_y, associated_combined_heat_power, duct_burners, bypass_heat_recovery, solid_fuel_gasification, carbon_capture, fluidized_bed_tech, pulverized_coal_tech, stoker_tech, other_combustion_tech, subcritical_tech, supercritical_tech, ultrasupercritical_tech, age_in_report_year, age_in_current_year_y, age_of_observation, age_relative_to_prime_avg, pollution_control_costs_per_kw, respondent_id, respondent_id_purchaser, final_respondent_id, final_ba_code_y, wage_scale, age_of_observation_secular_adj, fuel_group_y, year_y, essentials_y, ba_plus_essentials_y, age_range_y, _merge]
Index: []

In [76]:
(missing_data.query('fill_in_score ==2')
.merge(hist_data.drop(columns=['plant_id_eia','generator_id','year','prime_mover','fuel_group','final_ba_code','age_in_current_year','age_range','ba_plus_age','essentials']),on=['ba_plus_essentials'],how='left',indicator=True)
.query('_merge == "both"')
.drop_duplicates(subset=['plant_id_eia','generator_id','year']))

,plant_id_eia,generator_id,year,fuss,prime_mover,fuel_group,final_ba_code,age_in_current_year,essentials,ba_plus_essentials,age_range,ba_plus_age,essentials_present,ba_plus_essentials_present,ba_plus_age_present,fill_in_score,report_date,biofuel_mmbtu,coal_mmbtu,natural_gas_mmbtu,nuclear_mmbtu,other_mmbtu,other_gas_mmbtu,petroleum_mmbtu,petroleum_coke_mmbtu,renew_mmbtu,biofuel_net_mwh,coal_net_mwh,natural_gas_net_mwh,nuclear_net_mwh,other_net_mwh,other_gas_net_mwh,petroleum_net_mwh,petroleum_coke_net_mwh,renew_net_mwh,generator_starts,fuel_starts,gross_generation_mwh,biofuel_gross_mwh,coal_gross_mwh,natural_gas_gross_mwh,other_gross_mwh,other_gas_gross_mwh,petroleum_gross_mwh,petroleum_coke_gross_mwh,renew_gross_mwh,utility_id_eia,balancing_authority_code_eia,state,capacity_mw,associated_combined_heat_power,duct_burners,bypass_heat_recovery,solid_fuel_gasification,carbon_capture,fluidized_bed_tech,pulverized_coal_tech,stoker_tech,other_combustion_tech,subcritical_tech,supercritical_tech,ultrasupercritical_tech,age_in_report_year,age_of_observation,age_relative_to_prime_avg,pollution_control_costs_per_kw,respondent_id,respondent_id_purchaser,final_respondent_id,wage_scale,age_of_observation_secular_adj,_merge
0,3,3,2016,missing_years,ST,natural_gas,2,NaN,2016_ST_natural_gas,2016_ST_natural_gas_2,NaN,2016_ST_natural_gas_2_nan,1,1,0,2,2016-01-01,NaN,NaN,1.618925e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.338707e+02,NaN,NaN,NaN,NaN,NaN,NaN,10.0,10.0,1.189000e+04,NaN,NaN,1.189000e+04,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,153.1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,61.913758,5.916496,23.737808,2.927320,2,<NA>,2,1.011758,23.20239,both
13,3,A1CT2,2008,missing_years,CC,natural_gas,2,NaN,2008_CC_natural_gas,2008_CC_natural_gas_2,NaN,2008_CC_natural_gas_2_nan,1,1,0,2,2008-01-01,NaN,NaN,6.091393e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.582251e+05,NaN,NaN,NaN,NaN,NaN,NaN,886.0,886.0,4.820953e+06,NaN,NaN,4.820953e+06,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,170.1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,7.668720,13.916496,-7.184464,2.927320,2,<NA>,2,0.99812,15.459785,both
28,8,10,2019,missing_years,ST,coal,2,NaN,2019_ST_coal,2019_ST_coal_2,NaN,2019_ST_coal_2_nan,1,1,0,2,2019-01-01,NaN,NaN,4.135949e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.952539e+03,NaN,NaN,NaN,NaN,NaN,NaN,6.0,5.0,2.945400e+04,NaN,NaN,2.945400e+04,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,153.1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,64.914442,2.915811,26.738493,2.927320,2,<NA>,2,1.078991,26.305583,both
45,8,6,2016,missing_years,ST,coal,2,NaN,2016_ST_coal,2016_ST_coal_2,NaN,2016_ST_coal_2_nan,1,1,0,2,2016-01-01,NaN,NaN,1.618925e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.338707e+02,NaN,NaN,NaN,NaN,NaN,NaN,10.0,10.0,1.189000e+04,NaN,NaN,1.189000e+04,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,153.1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,61.913758,5.916496,23.737808,2.927320,2,<NA>,2,1.011758,23.20239,both
65,8,7,2016,missing_years,ST,coal,2,NaN,2016_ST_coal,2016_ST_coal_2,NaN,2016_ST_coal_2_nan,1,1,0,2,2016-01-01,NaN,NaN,1.618925e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.338707e+02,NaN,NaN,NaN,NaN,NaN,NaN,10.0,10.0,1.189000e+04,NaN,NaN,1.189000e+04,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,153.1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,61.913758,5.916496,23.737808,2.927320,2,<NA>,2,1.011758,23.20239,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
919359,57185,U006,2015,missing_years,CC,natural_gas,NYIS,NaN,2015_CC_natural_gas,2015_CC_natural_gas_NYIS,NaN,2015_CC_natural_gas_NYIS_nan,1,1,0,2,2015-01-01,NaN,NaN,1.110898e+07,NaN,NaN,NaN,136227.0,NaN,NaN,NaN,NaN,1.047181e+06,NaN,NaN,NaN,12720.854000,NaN,NaN,28.0,46.0,3.168856e+06,NaN,NaN,3.130468e+06,NaN,NaN,38388.250486,NaN,NaN,10023,NYIS,NY,170.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,11.085558,6.915811,-3.767627,23.769776,<NA>,<NA>,<NA>,1.130673,25.777802,both
919447,60927,1A,2015,missing_years,CC,natural_gas,ETR,NaN,2015_CC_natural_gas,2015_CC_natural_gas_ETR,NaN,2015_CC_natural_gas_ETR_nan,1,1,0,2,2015-01-01,NaN,NaN,1.385674e+07,NaN,NaN,NaN,136051.0,NaN,NaN,NaN,NaN,1.207323e+06,NaN,NaN,NaN,12782.790137,NaN,NaN,120.0,120.0,4.124005e+06,NaN,NaN,4.083908e+06,NaN,NaN,40097.419004,NaN,NaN,11241,MISO,LA,194.7,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.084873,6.915811,-14.768311,66.299728,454,<NA>,454,0.935734,20.665257,both
919489,60927,1B,2015,missing_years,CC,natural_gas,ETR,NaN,2015_CC_natural_gas,2015_CC_natural_gas_ETR,NaN,2015_CC_natural_gas_ETR_nan,1,1,0,2,2015-01-01,NaN,NaN,1.385674e+07,NaN,NaN,NaN,136051.0,NaN,NaN,NaN,NaN,1.207323e+06,NaN,NaN,NaN,12782.790137,NaN,NaN,120.0,120.0,4.124005e+06,NaN,NaN,4.083908e+06,NaN,NaN,40097.419004,NaN,NaN,11241,MISO,LA,194.7,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.084873,6.915811,-14.768311,66.299728,454,<NA>,454,0.935734,20.665257,both
919531,60927,1C,2015,missing_years,CC,natural_gas,ETR,NaN,2015_CC_natural_gas,2015_CC_natural_gas_ETR,NaN,2015_CC_natural_gas_ETR_nan,1,1,0,2,2015-01-01,NaN,NaN,1.385674e+07,NaN,NaN,NaN,136051.0,NaN,NaN,NaN,NaN,1.207323e+06,NaN,NaN,NaN,12782.790137,NaN,NaN,120.0,120.0,4.124005e+06,NaN,NaN,4.083908e+06,NaN,NaN,40097.419004,NaN,NaN,11241,MISO,LA,194.7,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.084873,6.915811,-14.768311,66.299728,454,<NA>,454,0.935734,20.665257,both
919573,55088,ST1,2011,fuel_switch,ST,other_gas,MISO,20.334018,2011_ST_other_gas,2011_ST_other_gas_MISO,3,2011_ST_other_gas_MISO_3,1,1,0,2,2011-01-01,NaN,2.526381e+06,4.936591e+05,NaN,0.0,NaN,NaN,NaN,NaN,NaN,29.7543,6.238881e+00,NaN,0.0,NaN,NaN,NaN,NaN,0.0,1492.0,0.000000e+00,NaN,0.0,0.000000e+00,0.0,NaN,NaN,NaN,NaN,3599,MISO,IN,15.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,85.998631,10.915811,47.822682,NaN,<NA>,<NA>,<NA>,0.954081,17.195681,both

In [67]:
(missing_data.query('fill_in_score ==3')
.merge(hist_data.drop(columns=['plant_id_eia','generator_id','year','prime_mover','fuel_group','final_ba_code','age_in_current_year','age_range','essentials','ba_plus_essentials']),on=['ba_plus_age'],how='left',indicator=True)
.query('_merge == "both"')
.drop_duplicates(subset=['plant_id_eia','generator_id','year']))

,plant_id_eia,generator_id,year,fuss,prime_mover,fuel_group,final_ba_code,age_in_current_year,essentials,ba_plus_essentials,age_range,ba_plus_age,essentials_present,ba_plus_essentials_present,ba_plus_age_present,fill_in_score,report_date,biofuel_mmbtu,coal_mmbtu,natural_gas_mmbtu,nuclear_mmbtu,other_mmbtu,other_gas_mmbtu,petroleum_mmbtu,petroleum_coke_mmbtu,renew_mmbtu,biofuel_net_mwh,coal_net_mwh,natural_gas_net_mwh,nuclear_net_mwh,other_net_mwh,other_gas_net_mwh,petroleum_net_mwh,petroleum_coke_net_mwh,renew_net_mwh,generator_starts,fuel_starts,gross_generation_mwh,biofuel_gross_mwh,coal_gross_mwh,natural_gas_gross_mwh,other_gross_mwh,other_gas_gross_mwh,petroleum_gross_mwh,petroleum_coke_gross_mwh,renew_gross_mwh,utility_id_eia,balancing_authority_code_eia,state,capacity_mw,associated_combined_heat_power,duct_burners,bypass_heat_recovery,solid_fuel_gasification,carbon_capture,fluidized_bed_tech,pulverized_coal_tech,stoker_tech,other_combustion_tech,subcritical_tech,supercritical_tech,ultrasupercritical_tech,age_in_report_year,age_of_observation,age_relative_to_prime_avg,pollution_control_costs_per_kw,respondent_id,respondent_id_purchaser,final_respondent_id,wage_scale,age_of_observation_secular_adj,_merge
0,7527,2,2012,fuel_switch,CC,natural_gas,CAISO,26.168378,2012_CC_natural_gas,2012_CC_natural_gas_CAISO,3,2012_CC_natural_gas_CAISO_3,1,1,1,3,2012-01-01,NaN,NaN,3.715400e+06,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,265316.163925,NaN,NaN,NaN,0.000000,NaN,NaN,34.0,32.0,1205096.0,NaN,NaN,1.205096e+06,NaN,NaN,0.000000,NaN,NaN,9216,IID,CA,89.9,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,18.584531,9.916496,3.731347,5.205650,648,<NA>,648,1.23754,22.301356,both
18,10333,GEN1,2013,fuel_switch,ST,coal,FPC,33.500342,2013_ST_coal,2013_ST_coal_FPC,4,2013_ST_coal_FPC_4,1,1,1,3,2013-01-01,NaN,3.913836e+07,NaN,NaN,NaN,NaN,120324.961137,NaN,NaN,NaN,3.892536e+06,NaN,NaN,NaN,NaN,10918.037449,NaN,NaN,9.0,13.0,4128033.0,NaN,4.115381e+06,NaN,NaN,NaN,12652.116668,NaN,NaN,6455,FPC,FL,739.2,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,28.251882,8.914442,-9.924067,67.961165,55,<NA>,55,0.940483,19.278976,both
21,10333,GEN1,2014,fuel_switch,ST,coal,FPC,33.500342,2014_ST_coal,2014_ST_coal_FPC,4,2014_ST_coal_FPC_4,1,1,1,3,2014-01-01,NaN,4.412765e+07,NaN,NaN,NaN,NaN,113056.925179,NaN,NaN,NaN,4.350971e+06,NaN,NaN,NaN,NaN,11840.169822,NaN,NaN,14.0,9.0,4870790.0,NaN,4.858343e+06,NaN,NaN,NaN,12447.283071,NaN,NaN,6455,FPC,FL,739.2,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,29.251198,7.915127,-8.924752,67.961165,55,<NA>,55,0.960971,20.239947,both
24,10333,GEN1,2015,fuel_switch,ST,coal,FPC,33.500342,2015_ST_coal,2015_ST_coal_FPC,4,2015_ST_coal_FPC_4,1,1,1,3,2015-01-01,NaN,3.304029e+07,NaN,NaN,NaN,NaN,106924.117914,NaN,NaN,NaN,3.219024e+06,NaN,NaN,NaN,NaN,7774.117138,NaN,NaN,4.0,6.0,3551209.0,NaN,3.539754e+06,NaN,NaN,NaN,11455.257331,NaN,NaN,6455,FPC,FL,739.2,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,30.250513,6.915811,-7.925436,67.961165,55,<NA>,55,0.97828,21.218227,both
27,10333,GEN1,2016,fuel_switch,ST,coal,FPC,33.500342,2016_ST_coal,2016_ST_coal_FPC,4,2016_ST_coal_FPC_4,1,1,1,3,2016-01-01,NaN,3.895418e+07,NaN,NaN,NaN,NaN,120981.265059,NaN,NaN,NaN,3.779808e+06,NaN,NaN,NaN,NaN,15260.807330,NaN,NaN,4.0,4.0,4172327.0,NaN,4.159409e+06,NaN,NaN,NaN,12918.011673,NaN,NaN,6455,FPC,FL,739.2,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,31.249829,5.916496,-6.926121,67.961165,55,<NA>,55,1.013763,22.231991,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100680,55505,BR2,2016,fuel_switch,GT,petroleum,529,19.586585,2016_GT_petroleum,2016_GT_petroleum_529,2,2016_GT_petroleum_529_2,1,1,1,3,2016-01-01,NaN,NaN,5.933650e+04,NaN,NaN,NaN,3232.250000,NaN,NaN,NaN,NaN,5984.599500,NaN,NaN,NaN,325.900500,NaN,NaN,25.0,28.0,11218.0,NaN,NaN,1.063849e+04,NaN,NaN,579.512624,NaN,NaN,30151,PNM,NM,46.5,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,12.837782,5.916496,-9.174447,7.703081,529,<NA>,529,0.853366,20.101608,both
100688,55505,BR2,2017,fuel_switch,GT,petroleum,529,19.586585,2017_GT_petroleum,2017_GT_petroleum_529,2,2017_GT_petroleum_529_2,1,1,1,3,2017-01-01,NaN,NaN,8.222200e+04,NaN,NaN,NaN,4101.750000,NaN,NaN,NaN,NaN,8143.038250,NaN,NaN,NaN,406.211750,NaN,NaN,25.0,25.0,10013.0,NaN,NaN,9.537223e+03,NaN,NaN,475.776629,NaN,NaN,30151,PNM,NM,46.5,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,13.839836,4.914442,-8.172394,7.703081,529,<NA>,529,0.818969,20.920577,both
100696,55505,BR2,2018,fuel_switch,GT,petroleum,529,19.586585,2018_GT_petroleum,2018_GT_petroleum_529,2,2018_GT_petroleum_529_2,1,1,1,3,2018-01-01,NaN,NaN,1.675468e+05,NaN,NaN,NaN,3670.750000,NaN,NaN,NaN,NaN,16227.069000,NaN,NaN,NaN,355.431000,NaN,NaN,20.0,22.0,11929.0,NaN,NaN,1.167325e+04,NaN,NaN,255.747086,NaN,NaN,30151,PNM,NM,46.5,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,14.839151,3.915127,-7.173078,7.703081,529,<NA>,529,0.80152,21.722098,both
100704,55505,BR2,2019,fuel_switch,GT,petroleum,529,19.586585,2019_GT_petroleum,2019_GT_petroleum_529,2,2019_GT_petroleum_529_2,1,1,1,3,2019-01-01,NaN,NaN,6.940182e+05,NaN,NaN,NaN,881873.500000,NaN,NaN,NaN,NaN,30143.649250,NaN,NaN,NaN,38302.850750,NaN,NaN,102.0,103.0,118542.0,NaN,NaN,5.220556e+04,NaN,NaN,66336.439947,NaN,NaN,30151,PNM,NM,46.5,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,15.838467,2.915811,-6.173763,7.703081,529,<NA>,529,0.80274,22.524838,both
100712,55505,BR2,2020,fuel_switch,GT,petroleum,529,19.586585,2020_GT_petroleum,2020_GT_petroleum_529,2,2020_GT_petroleum_529_2,1,1,1,3,2020-01-01,NaN,NaN,3.225120e+05,NaN,NaN,NaN,1322.000000,NaN,NaN,NaN,NaN,31349.058500,NaN,NaN,NaN,128.441500,NaN,NaN,46.0,46.0,35193.0,NaN,NaN,3.504933e+04,NaN,NaN,143.669738,NaN,NaN,30151,PNM,NM,46.5,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,16.837782,1.916496,-5.174447,7.703081,529,<NA>,529,0.812883,23.337721,both

In [69]:
(missing_data.query('fill_in_score ==1')
.merge(hist_data.drop(columns=['plant_id_eia','generator_id','year','prime_mover','fuel_group','final_ba_code','age_in_current_year','age_range','ba_plus_age','ba_plus_essentials']),on=['essentials'],how='left',indicator=True)
.query('_merge == "both"')
.drop_duplicates(subset=['plant_id_eia','generator_id','year']))

,plant_id_eia,generator_id,year,fuss,prime_mover,fuel_group,final_ba_code,age_in_current_year,essentials,ba_plus_essentials,age_range,ba_plus_age,essentials_present,ba_plus_essentials_present,ba_plus_age_present,fill_in_score,report_date,biofuel_mmbtu,coal_mmbtu,natural_gas_mmbtu,nuclear_mmbtu,other_mmbtu,other_gas_mmbtu,petroleum_mmbtu,petroleum_coke_mmbtu,renew_mmbtu,biofuel_net_mwh,coal_net_mwh,natural_gas_net_mwh,nuclear_net_mwh,other_net_mwh,other_gas_net_mwh,petroleum_net_mwh,petroleum_coke_net_mwh,renew_net_mwh,generator_starts,fuel_starts,gross_generation_mwh,biofuel_gross_mwh,coal_gross_mwh,natural_gas_gross_mwh,other_gross_mwh,other_gas_gross_mwh,petroleum_gross_mwh,petroleum_coke_gross_mwh,renew_gross_mwh,utility_id_eia,balancing_authority_code_eia,state,capacity_mw,associated_combined_heat_power,duct_burners,bypass_heat_recovery,solid_fuel_gasification,carbon_capture,fluidized_bed_tech,pulverized_coal_tech,stoker_tech,other_combustion_tech,subcritical_tech,supercritical_tech,ultrasupercritical_tech,age_in_report_year,age_of_observation,age_relative_to_prime_avg,pollution_control_costs_per_kw,respondent_id,respondent_id_purchaser,final_respondent_id,wage_scale,age_of_observation_secular_adj,_merge
0,9,1,2006,missing_years,GT,natural_gas,EPE,NaN,2006_GT_natural_gas,2006_GT_natural_gas_EPE,NaN,2006_GT_natural_gas_EPE_nan,1,0,0,1,2006-01-01,NaN,NaN,261284.189244,NaN,NaN,NaN,3703.0,NaN,NaN,NaN,NaN,27853.222222,NaN,NaN,NaN,240.222222,NaN,NaN,85.0,88.0,25411.0,NaN,NaN,25055.900068,NaN,NaN,355.099932,NaN,NaN,195,SOCO,AL,80.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,9.670089,15.915127,-12.342141,107.300831,2,<NA>,2,1.050357,13.40423,both
1184,310,2,2016,missing_years,ST,petroleum,None,NaN,2016_ST_petroleum,<NA>,NaN,<NA>,1,0,0,1,2016-01-01,NaN,373995.386529,771038.177507,NaN,NaN,NaN,0.0,NaN,NaN,NaN,75819.390226,17604.609865,NaN,NaN,NaN,0.000000,NaN,NaN,9.0,9.0,109697.0,NaN,35829.667535,73867.332465,NaN,NaN,0.000000,NaN,NaN,195,SOCO,AL,272.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,55.668720,5.916496,17.492771,0.582288,2,<NA>,2,1.011758,23.20239,both
1990,310,3,2016,missing_years,ST,natural_gas,None,NaN,2016_ST_natural_gas,<NA>,NaN,<NA>,1,0,0,1,2016-01-01,NaN,NaN,161892.503123,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,233.870694,NaN,NaN,NaN,NaN,NaN,NaN,10.0,10.0,11890.0,NaN,NaN,11890.000000,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,153.1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,61.913758,5.916496,23.737808,2.927320,2,<NA>,2,1.011758,23.20239,both
2840,310,4,2016,missing_years,ST,natural_gas,None,NaN,2016_ST_natural_gas,<NA>,NaN,<NA>,1,0,0,1,2016-01-01,NaN,NaN,161892.503123,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,233.870694,NaN,NaN,NaN,NaN,NaN,NaN,10.0,10.0,11890.0,NaN,NaN,11890.000000,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,153.1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,61.913758,5.916496,23.737808,2.927320,2,<NA>,2,1.011758,23.20239,both
3690,603,15,2016,missing_years,ST,petroleum,None,NaN,2016_ST_petroleum,<NA>,NaN,<NA>,1,0,0,1,2016-01-01,NaN,373995.386529,771038.177507,NaN,NaN,NaN,0.0,NaN,NaN,NaN,75819.390226,17604.609865,NaN,NaN,NaN,0.000000,NaN,NaN,9.0,9.0,109697.0,NaN,35829.667535,73867.332465,NaN,NaN,0.000000,NaN,NaN,195,SOCO,AL,272.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,55.668720,5.916496,17.492771,0.582288,2,<NA>,2,1.011758,23.20239,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
778776,2864,1,2015,missing_years,ST,coal,NaN,NaN,2015_ST_coal,<NA>,NaN,<NA>,1,0,0,1,2015-01-01,NaN,NaN,59476.795354,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.994385,NaN,NaN,NaN,NaN,NaN,NaN,6.0,6.0,4936.0,NaN,NaN,4936.000000,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,153.1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,60.914442,6.915811,22.738493,2.927320,2,<NA>,2,0.973045,22.190632,both
779796,2864,2,2015,missing_years,ST,coal,NaN,NaN,2015_ST_coal,<NA>,NaN,<NA>,1,0,0,1,2015-01-01,NaN,NaN,59476.795354,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.994385,NaN,NaN,NaN,NaN,NaN,NaN,6.0,6.0,4936.0,NaN,NaN,4936.000000,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,153.1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,60.914442,6.915811,22.738493,2.927320,2,<NA>,2,0.973045,22.190632,both
780816,7945,1,2015,missing_years,GT,natural_gas,None,NaN,2015_GT_natural_gas,<NA>,NaN,<NA>,1,0,0,1,2015-01-01,NaN,NaN,441224.000000,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,24907.000000,NaN,NaN,NaN,0.000000,NaN,NaN,81.0,90.0,25574.0,NaN,NaN,25574.000000,NaN,NaN,0.000000,NaN,NaN,5701,EPE,TX,80.5,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,34.502396,6.915811,12.490166,7.271187,49,<NA>,49,1.022259,22.123731,both
782432,55858,UNT1,2015,missing_years,GT,natural_gas,None,NaN,2015_GT_natural_gas,<NA>,NaN,<NA>,1,0,0,1,2015-01-01,NaN,NaN,441224.000000,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,24907.000000,NaN,NaN,NaN,0.000000,NaN,NaN,81.0,90.0,25574.0,NaN,NaN,25574.000000,NaN,NaN,0.000000,NaN,NaN,5701,EPE,TX,80.5,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,34.502396,6.915811,12.490166,7.271187,49,<NA>,49,1.022259,22.123731,both
784048,55858,UNT2,2015,missing_years,GT,natural_gas,None,NaN,2015_GT_natural_gas,<NA>,NaN,<NA>,1,0,0,1,2015-01-01,NaN,NaN,441224.000000,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,24907.000000,NaN,NaN,NaN,0.000000,NaN,NaN,81.0,90.0,25574.0,NaN,NaN,25574.000000,NaN,NaN,0.000000,NaN,NaN,5701,EPE,TX,80.5,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,34.502396,6.915811,12.490166,7.271187,49,<NA>,49,1.022259,22.123731,both

In [79]:
zero = missing_data.query('fill_in_score == 0')

In [84]:
zero.shape[0]

39

In [86]:
hist_data

,plant_id_eia,generator_id,report_date,biofuel_mmbtu,coal_mmbtu,natural_gas_mmbtu,nuclear_mmbtu,other_mmbtu,other_gas_mmbtu,petroleum_mmbtu,petroleum_coke_mmbtu,renew_mmbtu,biofuel_net_mwh,coal_net_mwh,natural_gas_net_mwh,nuclear_net_mwh,other_net_mwh,other_gas_net_mwh,petroleum_net_mwh,petroleum_coke_net_mwh,renew_net_mwh,generator_starts,fuel_starts,gross_generation_mwh,biofuel_gross_mwh,coal_gross_mwh,natural_gas_gross_mwh,other_gross_mwh,other_gas_gross_mwh,petroleum_gross_mwh,petroleum_coke_gross_mwh,renew_gross_mwh,utility_id_eia,balancing_authority_code_eia,state,capacity_mw,prime_mover,associated_combined_heat_power,duct_burners,bypass_heat_recovery,solid_fuel_gasification,carbon_capture,fluidized_bed_tech,pulverized_coal_tech,stoker_tech,other_combustion_tech,subcritical_tech,supercritical_tech,ultrasupercritical_tech,age_in_report_year,age_in_current_year,age_of_observation,age_relative_to_prime_avg,pollution_control_costs_per_kw,respondent_id,respondent_id_purchaser,final_respondent_id,final_ba_code,wage_scale,age_of_observation_secular_adj,fuel_group,year,essentials,ba_plus_essentials,age_range,ba_plus_age
0,3,1,2006-01-01,NaN,1.008871e+07,2.951150e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,964082.899927,4.120480e+03,NaN,NaN,NaN,NaN,NaN,NaN,7.0,7.0,1123980.0,NaN,1.120702e+06,3.278278e+03,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,153.1,ST,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,51.915127,67.830253,15.915127,13.739177,2.92732,2,<NA>,2,2,1.050357,13.40423,coal,2006,2006_ST_coal,2006_ST_coal_2,7,2006_ST_coal_2_7
1,3,1,2006-01-01,NaN,1.008871e+07,2.951150e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,964082.899927,4.120480e+03,NaN,NaN,NaN,NaN,NaN,NaN,7.0,7.0,1123980.0,NaN,1.120702e+06,3.278278e+03,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,153.1,ST,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,51.915127,67.830253,15.915127,13.739177,2.92732,2,<NA>,2,2,1.050357,13.40423,natural_gas,2006,2006_ST_natural_gas,2006_ST_natural_gas_2,7,2006_ST_natural_gas_2_7
2,3,1,2007-01-01,NaN,9.807031e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,954656.813326,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,13.0,1028301.0,NaN,1.028301e+06,NaN,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,153.1,ST,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,52.914442,67.830253,14.915811,14.738493,2.92732,2,<NA>,2,2,1.057435,14.461664,coal,2007,2007_ST_coal,2007_ST_coal_2,7,2007_ST_coal_2_7
3,3,1,2007-01-01,NaN,9.807031e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,954656.813326,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,13.0,1028301.0,NaN,1.028301e+06,NaN,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,153.1,ST,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,52.914442,67.830253,14.915811,14.738493,2.92732,2,<NA>,2,2,1.057435,14.461664,natural_gas,2007,2007_ST_natural_gas,2007_ST_natural_gas_2,7,2007_ST_natural_gas_2_7
4,3,1,2008-01-01,NaN,8.176078e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,865288.470536,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.0,15.0,928095.0,NaN,9.280950e+05,NaN,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,153.1,ST,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,53.913758,67.830253,13.916496,15.737808,2.92732,2,<NA>,2,2,0.99812,15.459785,coal,2008,2008_ST_coal,2008_ST_coal_2,7,2008_ST_coal_2_7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
133749,60926,1C,2019-01-01,NaN,NaN,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.449205e+06,NaN,NaN,NaN,NaN,NaN,NaN,35.0,35.0,0.0,NaN,NaN,0.000000e+00,NaN,NaN,NaN,NaN,NaN,11241,MISO,LA,500.0,CC,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,-0.328542,2.587269,2.915811,-15.181727,NaN,454,<NA>,454,ETR,0.923801,24.360724,natural_gas,2019,2019_CC_natural_gas,2019_CC_natural_gas_ETR,1,2019_CC_natural_gas_ETR_1
133750,60926,1C,2020-01-01,NaN,NaN,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.443787e+06,NaN,NaN,NaN,NaN,NaN,NaN,36.0,37.0,0.0,NaN,NaN,0.000000e+00,NaN,NaN,NaN,NaN,NaN,11241,MISO,LA,500.0,CC,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.670773,2.587269,1.916496,-14.182411,NaN,454,<NA>,454,ETR,0.964819,25.325543,natural_gas,2020,2020_CC_natural_gas,2020_CC_natural_gas_ETR,1,2020_CC_natural_gas_ETR_1
133751,60927,1A,2020-01-01,NaN,NaN,1.202763e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.100680e+06,NaN,NaN,NaN,NaN,NaN,NaN,51.0,54.0,1663118.5,NaN,NaN,1.663118e+06,NaN,NaN,NaN,NaN,NaN,11241,MISO,LA,250.0,CC,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,-0.164271,1.752225,1.916496,-15.017456,NaN,454,<NA>,454,ETR,0.964819,25.325543,natural_gas,2020,2020_CC_natural_gas,2020_CC_natural_gas_ETR,1,2020_CC_natural_gas_ETR_1
133752,60927,1B,2020-01-01,NaN,NaN,1.202763e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.017310e+06,NaN,NaN,NaN,NaN,NaN,NaN,51.0,54.0,1663118.5,NaN,NaN,1.663118e+06,NaN,NaN,NaN,NaN,NaN,11241,MISO,LA,250.0,CC,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,-0.164271,1.752225,1.916496,-15.017456,NaN,454,<NA>,454,ETR,0.964819,25.325543,natural_gas,2020,2020_CC_natural_gas,2020_CC_natural_gas_ETR,1,2020_CC_natural_gas_ETR_1
133753,60927,1C,2020-01-01,NaN,NaN,0.000000e+00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.321791e+06,NaN,NaN,NaN,NaN,NaN,NaN,51.0,54.0,0.0,NaN,NaN,0.000000e+00,NaN,NaN,NaN,NaN,NaN,11241,MISO,LA,500.0,CC,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,-0.164271,1.752225,1.916496,-15.017456,NaN,454,<NA>,454,ETR,0.964819,25.325543,natural_gas,2020,2020_CC_natural_gas,2020_CC_natural_gas_ETR,1,2020_CC_natural_gas_ETR_1

In [73]:
test = self.fill_in_ep_data()

/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:258: UserWarning: This crosswalk is not safe, it may have `pf_subplants with multiple primes. Use `safe_xwalk` instead.
  return self._xwalk.grand_crosswalk
/opt/anaconda3/envs/gencost/lib/python3.11/site-packages/etoolbox/utils/pudl_helpers.py:146: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[date_mask, date_col] = pd.to_datetime(
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:258: UserWarning: This crosswalk is not safe, it may have `pf_subplants with multiple primes. Use `safe_xwalk` instead.
  return self._xwalk.grand_crosswalk
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:199: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  np.repeat(df[old_cols].sum(axis=1)[:, np.newaxis], len(old_cols), 1) != 0.0,
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:204: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  df[old_cols].isna().sum(axis=1)[:, np.newaxis], len(old_cols), 1
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:213: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  df[to_allocate][:, np.newaxis],
/opt/anaconda3/envs/gencost/lib/python3.11/site-packages/etoolbox/utils/pudl_helpers.py:146: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[date_mask, date_col] = pd.to_datetime(
/opt/anaconda3/envs/gencost/lib/python3.11/site-packages/etoolbox/utils/pudl_helpers.py:146: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[date_mask, date_col] = pd.to_datetime(
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:258: UserWarning: This crosswalk is not safe, it may have `pf_subplants with multiple primes. Use `safe_xwalk` instead.
  return self._xwalk.grand_crosswalk
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:199: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  np.repeat(df[old_cols].sum(axis=1)[:, np.newaxis], len(old_cols), 1) != 0.0,
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:204: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  df[old_cols].isna().sum(axis=1)[:, np.newaxis], len(old_cols), 1
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:213: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  df[to_allocate][:, np.newaxis],
/opt/anaconda3/envs/gencost/lib/python3.11/site-packages/etoolbox/utils/pudl_helpers.py:146: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[date_mask, date_col] = pd.to_datetime(
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:258: UserWarning: This crosswalk is not safe, it may have `pf_subplants with multiple primes. Use `safe_xwalk` instead.
  return self._xwalk.grand_crosswalk
/opt/anaconda3/envs/gencost/lib/python3.11/site-packages/etoolbox/utils/pudl_helpers.py:146: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[date_mask, date_col] = pd.to_datetime(
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:2375: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  split = pd.DataFrame([pd.Series(x) for x in missing_years.years_to_fill_in])

In [74]:
test

,plant_id_eia,generator_id,year,fuss,prime_mover,fuel_group,final_ba_code,age_in_current_year,essentials,ba_plus_essentials,age_range,ba_plus_age,essentials_present,ba_plus_essentials_present,ba_plus_age_present,fill_in_score
0,3,3,2016,missing_years,ST,natural_gas,2,NaN,2016_ST_natural_gas,2016_ST_natural_gas_2,NaN,2016_ST_natural_gas_2_nan,1,1,0,2
14,3,A1CT2,2008,missing_years,CC,natural_gas,2,NaN,2008_CC_natural_gas,2008_CC_natural_gas_2,NaN,2008_CC_natural_gas_2_nan,1,1,0,2
28,8,10,2019,missing_years,ST,coal,2,NaN,2019_ST_coal,2019_ST_coal_2,NaN,2019_ST_coal_2_nan,1,1,0,2
46,8,6,2016,missing_years,ST,coal,2,NaN,2016_ST_coal,2016_ST_coal_2,NaN,2016_ST_coal_2_nan,1,1,0,2
60,8,7,2016,missing_years,ST,coal,2,NaN,2016_ST_coal,2016_ST_coal_2,NaN,2016_ST_coal_2_nan,1,1,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2392,55505,BR2,2016,fuel_switch,GT,petroleum,529,19.586585,2016_GT_petroleum,2016_GT_petroleum_529,2,2016_GT_petroleum_529_2,1,1,1,3
2393,55505,BR2,2017,fuel_switch,GT,petroleum,529,19.586585,2017_GT_petroleum,2017_GT_petroleum_529,2,2017_GT_petroleum_529_2,1,1,1,3
2394,55505,BR2,2018,fuel_switch,GT,petroleum,529,19.586585,2018_GT_petroleum,2018_GT_petroleum_529,2,2018_GT_petroleum_529_2,1,1,1,3
2395,55505,BR2,2019,fuel_switch,GT,petroleum,529,19.586585,2019_GT_petroleum,2019_GT_petroleum_529,2,2019_GT_petroleum_529_2,1,1,1,3
2396,55505,BR2,2020,fuel_switch,GT,petroleum,529,19.586585,2020_GT_petroleum,2020_GT_petroleum_529,2,2020_GT_petroleum_529_2,1,1,1,3

In [87]:
df = self.get_gf923_by_generator(counterfactuals=True)

In [91]:
df.query('net_mwh == 0 & mmbtu == 0 & report_date >= "2006-"')

,report_date,plant_id_eia,generator_id,prime_mover_code,energy_source_code,energy_source_code_num,net_mwh,mmbtu,fuel_consumed_for_electricity_mmbtu,fuel_group
1226367,2001-01-01,9,1,GT,DFO,energy_source_code_2,0.0,0.0,0.0,petroleum
1247942,2001-01-01,47,GT1,GT,NG,energy_source_code_1,0.0,0.0,0.0,natural_gas
1247943,2001-01-01,47,GT2,GT,NG,energy_source_code_1,0.0,0.0,0.0,natural_gas
1247944,2001-01-01,47,GT3,GT,NG,energy_source_code_1,0.0,0.0,0.0,natural_gas
1247945,2001-01-01,47,GT4,GT,NG,energy_source_code_1,0.0,0.0,0.0,natural_gas
...,...,...,...,...,...,...,...,...,...,...
6807129,2021-12-01,65650,15447,BA,MWH,energy_source_code_1,0.0,0.0,0.0,other
6807153,2021-12-01,65652,NBRIA,PV,SUN,energy_source_code_1,0.0,0.0,0.0,renew
6807225,2021-12-01,65659,PV1,PV,SUN,energy_source_code_1,0.0,0.0,0.0,renew
6807261,2021-12-01,65667,EWS1,PV,SUN,energy_source_code_1,0.0,0.0,0.0,renew
6807753,2021-12-01,65740,21536,PV,SUN,energy_source_code_1,0.0,0.0,0.0,renew

In [100]:
k

        plant_id_eia generator_id report_date  net_mwh  mmbtu
1                  1            1  2020-01-01      0.0    0.0
5                  1            2  2020-01-01      0.0    0.0
9                  1            3  2020-01-01      0.0    0.0
13                 1            5  2020-01-01      0.0    0.0
191                3         A1ST  2006-01-01      0.0    0.0
...              ...          ...         ...      ...    ...
431169         64816         GEN1  2020-01-01      0.0    0.0
431172         64816         GEN2  2020-01-01      0.0    0.0
431175         64816         GEN3  2020-01-01      0.0    0.0
431212         64836        CATAL  2020-01-01      0.0    0.0
431215         64837        MARIN  2020-01-01      0.0    0.0

[17052 rows x 5 columns]

In [103]:
df_860 = self.get_860_by_x(subplant_id_col='generator_id')

/opt/anaconda3/envs/gencost/lib/python3.11/site-packages/etoolbox/utils/pudl_helpers.py:146: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[date_mask, date_col] = pd.to_datetime(

In [104]:
df_860

,utility_id_eia,balancing_authority_code_eia,state,plant_id_eia,generator_id,report_date,capacity_mw,prime_mover,associated_combined_heat_power,duct_burners,bypass_heat_recovery,solid_fuel_gasification,carbon_capture,fluidized_bed_tech,pulverized_coal_tech,stoker_tech,other_combustion_tech,subcritical_tech,supercritical_tech,ultrasupercritical_tech,age_in_report_year,age_in_current_year,age_of_observation,age_relative_to_prime_avg,pollution_control_costs_per_kw,respondent_id,respondent_id_purchaser,final_respondent_id,final_ba_code
0,195,SOCO,AL,2,1,2001-01-01,45.0,HY,1,1,1,1,1,1,1,1,1,1,1,1,37.505818,58.420260,20.914442,-22.507147,2.92732,2,<NA>,2,2
1,195,SOCO,AL,3,1,2001-01-01,153.1,ST,1,1,1,1,1,1,1,1,1,1,1,1,46.915811,67.830253,20.914442,8.739862,2.92732,2,<NA>,2,2
2,195,SOCO,AL,3,2,2001-01-01,153.1,ST,1,1,1,1,1,1,1,1,1,1,1,1,46.505133,67.419576,20.914442,8.329184,2.92732,2,<NA>,2,2
3,195,SOCO,AL,3,3,2001-01-01,272.0,ST,1,1,1,1,1,1,1,1,1,1,1,1,41.505818,62.420260,20.914442,3.329869,NaN,2,<NA>,2,2
4,195,SOCO,AL,3,4,2001-01-01,403.7,ST,1,1,1,1,1,1,1,1,1,1,1,1,31.085558,52.000000,20.914442,-7.090392,2.92732,2,<NA>,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
427134,61980,NaN,CA,65824,VSPRC,2022-01-01,1.1,PV,1,1,1,1,1,1,1,1,1,1,1,1,1.752225,1.667351,-0.084873,-1.315511,NaN,<NA>,<NA>,<NA>,NaN
427135,65076,ERCO,TX,65831,LNSTR,2022-01-01,9.9,BA,1,1,1,1,1,1,1,1,1,1,1,1,NaN,NaN,-0.084873,NaN,NaN,<NA>,<NA>,<NA>,ERCO
427136,65076,ERCO,TX,65836,TOYAH,2022-01-01,10.4,BA,1,1,1,1,1,1,1,1,1,1,1,1,0.251882,0.167009,-0.084873,-1.996059,NaN,<NA>,<NA>,<NA>,ERCO
427137,65076,ERCO,TX,65838,HOEFS,2022-01-01,2.0,BA,1,1,1,1,1,1,1,1,1,1,1,1,0.670773,0.585900,-0.084873,-1.577168,NaN,<NA>,<NA>,<NA>,ERCO
427138,61944,ISNE,ME,65859,GEN1,2022-01-01,5.0,PV,1,1,1,1,1,1,1,1,1,1,1,1,NaN,NaN,-0.084873,NaN,NaN,<NA>,<NA>,<NA>,ISNE

In [158]:
missing_data['year'].dt.strftime('%Y-%m-%d')

AttributeError: Can only use .dt accessor with datetimelike values

In [161]:
m['year'].dt.strftime('%Y-%m-%d')

AttributeError: Can only use .dt accessor with datetimelike values

In [159]:
pd.to_datetime(missing_data['year'],format='%Y-%m-%d')

#.dt.strftime('%Y%m%d')

0      1970-01-01 00:00:00.000002016
14     1970-01-01 00:00:00.000002008
28     1970-01-01 00:00:00.000002019
46     1970-01-01 00:00:00.000002016
60     1970-01-01 00:00:00.000002016
                    ...
2392   1970-01-01 00:00:00.000002016
2393   1970-01-01 00:00:00.000002017
2394   1970-01-01 00:00:00.000002018
2395   1970-01-01 00:00:00.000002019
2396   1970-01-01 00:00:00.000002020
Name: year, Length: 14570, dtype: datetime64[ns]

In [152]:
missing_data

,plant_id_eia,generator_id,year,fuss,prime_mover,fuel_group,final_ba_code,age_in_current_year,essentials,ba_plus_essentials,age_range,ba_plus_age,essentials_present,ba_plus_essentials_present,ba_plus_age_present,fill_in_score
0,3,3,2016,missing_years,ST,natural_gas,2,NaN,2016_ST_natural_gas,2016_ST_natural_gas_2,NaN,2016_ST_natural_gas_2_nan,1,1,0,2
14,3,A1CT2,2008,missing_years,CC,natural_gas,2,NaN,2008_CC_natural_gas,2008_CC_natural_gas_2,NaN,2008_CC_natural_gas_2_nan,1,1,0,2
28,8,10,2019,missing_years,ST,coal,2,NaN,2019_ST_coal,2019_ST_coal_2,NaN,2019_ST_coal_2_nan,1,1,0,2
46,8,6,2016,missing_years,ST,coal,2,NaN,2016_ST_coal,2016_ST_coal_2,NaN,2016_ST_coal_2_nan,1,1,0,2
60,8,7,2016,missing_years,ST,coal,2,NaN,2016_ST_coal,2016_ST_coal_2,NaN,2016_ST_coal_2_nan,1,1,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2392,55505,BR2,2016,fuel_switch,GT,petroleum,529,19.586585,2016_GT_petroleum,2016_GT_petroleum_529,2,2016_GT_petroleum_529_2,1,1,1,3
2393,55505,BR2,2017,fuel_switch,GT,petroleum,529,19.586585,2017_GT_petroleum,2017_GT_petroleum_529,2,2017_GT_petroleum_529_2,1,1,1,3
2394,55505,BR2,2018,fuel_switch,GT,petroleum,529,19.586585,2018_GT_petroleum,2018_GT_petroleum_529,2,2018_GT_petroleum_529_2,1,1,1,3
2395,55505,BR2,2019,fuel_switch,GT,petroleum,529,19.586585,2019_GT_petroleum,2019_GT_petroleum_529,2,2019_GT_petroleum_529_2,1,1,1,3
2396,55505,BR2,2020,fuel_switch,GT,petroleum,529,19.586585,2020_GT_petroleum,2020_GT_petroleum_529,2,2020_GT_petroleum_529_2,1,1,1,3

In [114]:
k = self.find_missing_data()

/opt/anaconda3/envs/gencost/lib/python3.11/site-packages/etoolbox/utils/pudl_helpers.py:146: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[date_mask, date_col] = pd.to_datetime(
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:258: UserWarning: This crosswalk is not safe, it may have `pf_subplants with multiple primes. Use `safe_xwalk` instead.
  return self._xwalk.grand_crosswalk
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:199: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  np.repeat(df[old_cols].sum(axis=1)[:, np.newaxis], len(old_cols), 1) != 0.0,
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:204: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  df[old_cols].isna().sum(axis=1)[:, np.newaxis], len(old_cols), 1
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:213: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  df[to_allocate][:, np.newaxis],
/opt/anaconda3/envs/gencost/lib/python3.11/site-packages/etoolbox/utils/pudl_helpers.py:146: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[date_mask, date_col] = pd.to_datetime(
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:258: UserWarning: This crosswalk is not safe, it may have `pf_subplants with multiple primes. Use `safe_xwalk` instead.
  return self._xwalk.grand_crosswalk
/opt/anaconda3/envs/gencost/lib/python3.11/site-packages/etoolbox/utils/pudl_helpers.py:146: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[date_mask, date_col] = pd.to_datetime(
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:2375: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  split = pd.DataFrame([pd.Series(x) for x in missing_years.years_to_fill_in])

In [117]:
k.query('fuss == "zeroes"')

,plant_id_eia,generator_id,year,fuss,prime_mover,fuel_group,final_ba_code,age_in_current_year
0,1,1,2020,zeroes,IC,petroleum,Alaska,20.999316
1,1,2,2020,zeroes,IC,petroleum,Alaska,20.999316
2,1,3,2020,zeroes,IC,petroleum,Alaska,11.000684
3,1,5,2020,zeroes,IC,petroleum,Alaska,20.999316
4,3,A1ST,2006,zeroes,CC,natural_gas,2,21.585216
...,...,...,...,...,...,...,...,...
42123,64816,GEN1,2020,zeroes,IC,natural_gas,ERCO,1.248460
42124,64816,GEN2,2020,zeroes,IC,natural_gas,ERCO,1.248460
42125,64816,GEN3,2020,zeroes,IC,natural_gas,ERCO,1.248460
42126,64836,CATAL,2020,zeroes,PV,renew,CAISO,0.999316
42127,64837,MARIN,2020,zeroes,PV,renew,CAISO,0.999316

In [166]:
m = self.fill_in_ep_data()

/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:258: UserWarning: This crosswalk is not safe, it may have `pf_subplants with multiple primes. Use `safe_xwalk` instead.
  return self._xwalk.grand_crosswalk
/opt/anaconda3/envs/gencost/lib/python3.11/site-packages/etoolbox/utils/pudl_helpers.py:146: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[date_mask, date_col] = pd.to_datetime(
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:258: UserWarning: This crosswalk is not safe, it may have `pf_subplants with multiple primes. Use `safe_xwalk` instead.
  return self._xwalk.grand_crosswalk
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:199: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  np.repeat(df[old_cols].sum(axis=1)[:, np.newaxis], len(old_cols), 1) != 0.0,
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:204: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  df[old_cols].isna().sum(axis=1)[:, np.newaxis], len(old_cols), 1
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:213: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  df[to_allocate][:, np.newaxis],
/opt/anaconda3/envs/gencost/lib/python3.11/site-packages/etoolbox/utils/pudl_helpers.py:146: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[date_mask, date_col] = pd.to_datetime(
/opt/anaconda3/envs/gencost/lib/python3.11/site-packages/etoolbox/utils/pudl_helpers.py:146: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[date_mask, date_col] = pd.to_datetime(
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:258: UserWarning: This crosswalk is not safe, it may have `pf_subplants with multiple primes. Use `safe_xwalk` instead.
  return self._xwalk.grand_crosswalk
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:199: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  np.repeat(df[old_cols].sum(axis=1)[:, np.newaxis], len(old_cols), 1) != 0.0,
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:204: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  df[old_cols].isna().sum(axis=1)[:, np.newaxis], len(old_cols), 1
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:213: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  df[to_allocate][:, np.newaxis],
/opt/anaconda3/envs/gencost/lib/python3.11/site-packages/etoolbox/utils/pudl_helpers.py:146: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[date_mask, date_col] = pd.to_datetime(
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:258: UserWarning: This crosswalk is not safe, it may have `pf_subplants with multiple primes. Use `safe_xwalk` instead.
  return self._xwalk.grand_crosswalk
/opt/anaconda3/envs/gencost/lib/python3.11/site-packages/etoolbox/utils/pudl_helpers.py:146: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[date_mask, date_col] = pd.to_datetime(
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:2375: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  split = pd.DataFrame([pd.Series(x) for x in missing_years.years_to_fill_in])

In [165]:
pd.to_datetime(m['year'],format="%Y")

785664    2020-01-01
785667    2020-01-01
785670    2020-01-01
785673    2020-01-01
335705    2006-01-01
             ...
3996801   2020-01-01
3996804   2020-01-01
3996807   2020-01-01
3996810   2020-01-01
3996813   2020-01-01
Name: year, Length: 45634, dtype: datetime64[ns]

In [169]:
missing_data['fill_in_match'] = np.where(missing_data['fill_in_score'] == 3,'essentials_ba_age_group',(np.where(missing_data['fill_in_score']==2,'essentials_ba','essentials')))

In [171]:
missing_data.query('fill_in_score == 1')

,plant_id_eia,generator_id,year,fuss,prime_mover,fuel_group,final_ba_code,age_in_current_year,essentials,ba_plus_essentials,age_range,ba_plus_age,essentials_present,ba_plus_essentials_present,ba_plus_age_present,fill_in_score,fill_in_match
110,9,1,2006,missing_years,GT,natural_gas,EPE,NaN,2006_GT_natural_gas,2006_GT_natural_gas_EPE,NaN,2006_GT_natural_gas_EPE_nan,1,0,0,1,essentials
922,310,2,2016,missing_years,ST,petroleum,None,NaN,2016_ST_petroleum,<NA>,NaN,<NA>,1,0,0,1,essentials
932,310,3,2016,missing_years,ST,natural_gas,None,NaN,2016_ST_natural_gas,<NA>,NaN,<NA>,1,0,0,1,essentials
940,310,4,2016,missing_years,ST,natural_gas,None,NaN,2016_ST_natural_gas,<NA>,NaN,<NA>,1,0,0,1,essentials
1961,603,15,2016,missing_years,ST,petroleum,None,NaN,2016_ST_petroleum,<NA>,NaN,<NA>,1,0,0,1,essentials
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140623,2864,1,2015,missing_years,ST,coal,NaN,NaN,2015_ST_coal,<NA>,NaN,<NA>,1,0,0,1,essentials
140626,2864,2,2015,missing_years,ST,coal,NaN,NaN,2015_ST_coal,<NA>,NaN,<NA>,1,0,0,1,essentials
140667,7945,1,2015,missing_years,GT,natural_gas,None,NaN,2015_GT_natural_gas,<NA>,NaN,<NA>,1,0,0,1,essentials
140726,55858,UNT1,2015,missing_years,GT,natural_gas,None,NaN,2015_GT_natural_gas,<NA>,NaN,<NA>,1,0,0,1,essentials
140732,55858,UNT2,2015,missing_years,GT,natural_gas,None,NaN,2015_GT_natural_gas,<NA>,NaN,<NA>,1,0,0,1,essentials

In [167]:
m

,plant_id_eia,generator_id,fuss,final_ba_code,age_in_current_year,report_date,biofuel_mmbtu,coal_mmbtu,natural_gas_mmbtu,nuclear_mmbtu,other_mmbtu,other_gas_mmbtu,petroleum_mmbtu,petroleum_coke_mmbtu,renew_mmbtu,biofuel_net_mwh,coal_net_mwh,natural_gas_net_mwh,nuclear_net_mwh,other_net_mwh,other_gas_net_mwh,petroleum_net_mwh,petroleum_coke_net_mwh,renew_net_mwh,generator_starts,fuel_starts,gross_generation_mwh,biofuel_gross_mwh,coal_gross_mwh,natural_gas_gross_mwh,other_gross_mwh,other_gas_gross_mwh,petroleum_gross_mwh,petroleum_coke_gross_mwh,renew_gross_mwh,utility_id_eia,balancing_authority_code_eia,state,capacity_mw,associated_combined_heat_power,duct_burners,bypass_heat_recovery,solid_fuel_gasification,carbon_capture,fluidized_bed_tech,pulverized_coal_tech,stoker_tech,other_combustion_tech,subcritical_tech,supercritical_tech,ultrasupercritical_tech,age_in_report_year,age_of_observation,age_relative_to_prime_avg,pollution_control_costs_per_kw,respondent_id,respondent_id_purchaser,final_respondent_id,wage_scale,age_of_observation_secular_adj
785664,1,1,zeroes,Alaska,20.999316,2020-01-01,NaN,NaN,NaN,NaN,NaN,NaN,343.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,138.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,20847,MISO,WI,2.7,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,50.836413,1.916496,28.969892,106.666667,193,<NA>,193,0.959081,26.618848
785667,1,2,zeroes,Alaska,20.999316,2020-01-01,NaN,NaN,NaN,NaN,NaN,NaN,343.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,138.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,20847,MISO,WI,2.7,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,50.836413,1.916496,28.969892,106.666667,193,<NA>,193,0.959081,26.618848
785670,1,3,zeroes,Alaska,11.000684,2020-01-01,NaN,NaN,NaN,NaN,NaN,NaN,343.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,138.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,20847,MISO,WI,2.7,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,50.836413,1.916496,28.969892,106.666667,193,<NA>,193,0.959081,26.618848
785673,1,5,zeroes,Alaska,20.999316,2020-01-01,NaN,NaN,NaN,NaN,NaN,NaN,343.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,138.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,20847,MISO,WI,2.7,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,50.836413,1.916496,28.969892,106.666667,193,<NA>,193,0.959081,26.618848
335705,3,1,fuel_switch,2,67.830253,2006-01-01,NaN,1.008871e+07,29511.495021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,964082.899927,4120.479810,NaN,NaN,NaN,NaN,NaN,NaN,7.0,7.0,1123980.0,NaN,1.120702e+06,3278.277774,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,153.1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,51.915127,15.915127,13.739177,2.927320,2,<NA>,2,1.050357,13.40423
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3996801,64815,GEN2,zeroes,ERCO,2.420260,2020-01-01,NaN,NaN,124809.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13447.611111,NaN,NaN,NaN,NaN,NaN,NaN,147.0,149.0,323384.0,NaN,NaN,323384.000000,NaN,NaN,NaN,NaN,NaN,7349,SWPP,TX,9.3,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,8.585900,1.916496,-13.280621,NaN,58,<NA>,58,1.013692,27.335436
3996804,64815,GEN3,zeroes,ERCO,2.420260,2020-01-01,NaN,NaN,124809.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13447.611111,NaN,NaN,NaN,NaN,NaN,NaN,147.0,149.0,323384.0,NaN,NaN,323384.000000,NaN,NaN,NaN,NaN,NaN,7349,SWPP,TX,9.3,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,8.585900,1.916496,-13.280621,NaN,58,<NA>,58,1.013692,27.335436
3996807,64816,GEN1,zeroes,ERCO,1.248460,2020-01-01,NaN,NaN,124809.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13447.611111,NaN,NaN,NaN,NaN,NaN,NaN,147.0,149.0,323384.0,NaN,NaN,323384.000000,NaN,NaN,NaN,NaN,NaN,7349,SWPP,TX,9.3,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,8.585900,1.916496,-13.280621,NaN,58,<NA>,58,1.013692,27.335436
3996810,64816,GEN2,zeroes,ERCO,1.248460,2020-01-01,NaN,NaN,124809.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13447.611111,NaN,NaN,NaN,NaN,NaN,NaN,147.0,149.0,323384.0,NaN,NaN,323384.000000,NaN,NaN,NaN,NaN,NaN,7349,SWPP,TX,9.3,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,8.585900,1.916496,-13.280621,NaN,58,<NA>,58,1.013692,27.335436
3996813,64816,GEN3,zeroes,ERCO,1.248460,2020-01-01,NaN,NaN,124809.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13447.611111,NaN,NaN,NaN,NaN,NaN,NaN,147.0,149.0,323384.0,NaN,NaN,323384.000000,NaN,NaN,NaN,NaN,NaN,7349,SWPP,TX,9.3,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,8.585900,1.916496,-13.280621,NaN,58,<NA>,58,1.013692,27.335436

In [123]:
m.query('fill_in_score == 1')

,plant_id_eia,generator_id,year,fuss,prime_mover,fuel_group,final_ba_code,age_in_current_year,essentials,ba_plus_essentials,age_range,ba_plus_age,essentials_present,ba_plus_essentials_present,ba_plus_age_present,fill_in_score,report_date,biofuel_mmbtu,coal_mmbtu,natural_gas_mmbtu,nuclear_mmbtu,other_mmbtu,other_gas_mmbtu,petroleum_mmbtu,petroleum_coke_mmbtu,renew_mmbtu,biofuel_net_mwh,coal_net_mwh,natural_gas_net_mwh,nuclear_net_mwh,other_net_mwh,other_gas_net_mwh,petroleum_net_mwh,petroleum_coke_net_mwh,renew_net_mwh,generator_starts,fuel_starts,gross_generation_mwh,biofuel_gross_mwh,coal_gross_mwh,natural_gas_gross_mwh,other_gross_mwh,other_gas_gross_mwh,petroleum_gross_mwh,petroleum_coke_gross_mwh,renew_gross_mwh,utility_id_eia,balancing_authority_code_eia,state,capacity_mw,associated_combined_heat_power,duct_burners,bypass_heat_recovery,solid_fuel_gasification,carbon_capture,fluidized_bed_tech,pulverized_coal_tech,stoker_tech,other_combustion_tech,subcritical_tech,supercritical_tech,ultrasupercritical_tech,age_in_report_year,age_of_observation,age_relative_to_prime_avg,pollution_control_costs_per_kw,respondent_id,respondent_id_purchaser,final_respondent_id,wage_scale,age_of_observation_secular_adj,_merge
0,9,1,2006,missing_years,GT,natural_gas,EPE,NaN,2006_GT_natural_gas,2006_GT_natural_gas_EPE,NaN,2006_GT_natural_gas_EPE_nan,1,0,0,1,2006-01-01,NaN,NaN,261284.189244,NaN,NaN,NaN,3703.0,NaN,NaN,NaN,NaN,27853.222222,NaN,NaN,NaN,240.222222,NaN,NaN,85.0,88.0,25411.0,NaN,NaN,25055.900068,NaN,NaN,355.099932,NaN,NaN,195,SOCO,AL,80.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,9.670089,15.915127,-12.342141,107.300831,2,<NA>,2,1.050357,13.40423,both
1184,310,2,2016,missing_years,ST,petroleum,None,NaN,2016_ST_petroleum,<NA>,NaN,<NA>,1,0,0,1,2016-01-01,NaN,373995.386529,771038.177507,NaN,NaN,NaN,0.0,NaN,NaN,NaN,75819.390226,17604.609865,NaN,NaN,NaN,0.000000,NaN,NaN,9.0,9.0,109697.0,NaN,35829.667535,73867.332465,NaN,NaN,0.000000,NaN,NaN,195,SOCO,AL,272.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,55.668720,5.916496,17.492771,0.582288,2,<NA>,2,1.011758,23.20239,both
1990,310,3,2016,missing_years,ST,natural_gas,None,NaN,2016_ST_natural_gas,<NA>,NaN,<NA>,1,0,0,1,2016-01-01,NaN,NaN,161892.503123,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,233.870694,NaN,NaN,NaN,NaN,NaN,NaN,10.0,10.0,11890.0,NaN,NaN,11890.000000,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,153.1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,61.913758,5.916496,23.737808,2.927320,2,<NA>,2,1.011758,23.20239,both
2840,310,4,2016,missing_years,ST,natural_gas,None,NaN,2016_ST_natural_gas,<NA>,NaN,<NA>,1,0,0,1,2016-01-01,NaN,NaN,161892.503123,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,233.870694,NaN,NaN,NaN,NaN,NaN,NaN,10.0,10.0,11890.0,NaN,NaN,11890.000000,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,153.1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,61.913758,5.916496,23.737808,2.927320,2,<NA>,2,1.011758,23.20239,both
3690,603,15,2016,missing_years,ST,petroleum,None,NaN,2016_ST_petroleum,<NA>,NaN,<NA>,1,0,0,1,2016-01-01,NaN,373995.386529,771038.177507,NaN,NaN,NaN,0.0,NaN,NaN,NaN,75819.390226,17604.609865,NaN,NaN,NaN,0.000000,NaN,NaN,9.0,9.0,109697.0,NaN,35829.667535,73867.332465,NaN,NaN,0.000000,NaN,NaN,195,SOCO,AL,272.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,55.668720,5.916496,17.492771,0.582288,2,<NA>,2,1.011758,23.20239,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3996801,64815,GEN2,2020,zeroes,IC,natural_gas,ERCO,2.42026,2020_IC_natural_gas,2020_IC_natural_gas_ERCO,1,2020_IC_natural_gas_ERCO_1,1,0,0,1,2020-01-01,NaN,NaN,124809.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13447.611111,NaN,NaN,NaN,NaN,NaN,NaN,147.0,149.0,323384.0,NaN,NaN,323384.000000,NaN,NaN,NaN,NaN,NaN,7349,SWPP,TX,9.3,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,8.585900,1.916496,-13.280621,NaN,58,<NA>,58,1.013692,27.335436,both
3996804,64815,GEN3,2020,zeroes,IC,natural_gas,ERCO,2.42026,2020_IC_natural_gas,2020_IC_natural_gas_ERCO,1,2020_IC_natural_gas_ERCO_1,1,0,0,1,2020-01-01,NaN,NaN,124809.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13447.611111,NaN,NaN,NaN,NaN,NaN,NaN,147.0,149.0,323384.0,NaN,NaN,323384.000000,NaN,NaN,NaN,NaN,NaN,7349,SWPP,TX,9.3,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,8.585900,1.916496,-13.280621,NaN,58,<NA>,58,1.013692,27.335436,both
3996807,64816,GEN1,2020,zeroes,IC,natural_gas,ERCO,1.24846,2020_IC_natural_gas,2020_IC_natural_gas_ERCO,1,2020_IC_natural_gas_ERCO_1,1,0,0,1,2020-01-01,NaN,NaN,124809.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13447.611111,NaN,NaN,NaN,NaN,NaN,NaN,147.0,149.0,323384.0,NaN,NaN,323384.000000,NaN,NaN,NaN,NaN,NaN,7349,SWPP,TX,9.3,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,8.585900,1.916496,-13.280621,NaN,58,<NA>,58,1.013692,27.335436,both
3996810,64816,GEN2,2020,zeroes,IC,natural_gas,ERCO,1.24846,2020_IC_natural_gas,2020_IC_natural_gas_ERCO,1,2020_IC_natural_gas_ERCO_1,1,0,0,1,2020-01-01,NaN,NaN,124809.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13447.611111,NaN,NaN,NaN,NaN,NaN,NaN,147.0,149.0,323384.0,NaN,NaN,323384.000000,NaN,NaN,NaN,NaN,NaN,7349,SWPP,TX,9.3,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,8.585900,1.916496,-13.280621,NaN,58,<NA>,58,1.013692,27.335436,both
3996813,64816,GEN3,2020,zeroes,IC,natural_gas,ERCO,1.24846,2020_IC_natural_gas,2020_IC_natural_gas_ERCO,1,2020_IC_natural_gas_ERCO_1,1,0,0,1,2020-01-01,NaN,NaN,124809.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13447.611111,NaN,NaN,NaN,NaN,NaN,NaN,147.0,149.0,323384.0,NaN,NaN,323384.000000,NaN,NaN,NaN,NaN,NaN,7349,SWPP,TX,9.3,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,8.585900,1.916496,-13.280621,NaN,58,<NA>,58,1.013692,27.335436,both

In [124]:
m.query('fill_in_score == 2')

,plant_id_eia,generator_id,year,fuss,prime_mover,fuel_group,final_ba_code,age_in_current_year,essentials,ba_plus_essentials,age_range,ba_plus_age,essentials_present,ba_plus_essentials_present,ba_plus_age_present,fill_in_score,report_date,biofuel_mmbtu,coal_mmbtu,natural_gas_mmbtu,nuclear_mmbtu,other_mmbtu,other_gas_mmbtu,petroleum_mmbtu,petroleum_coke_mmbtu,renew_mmbtu,biofuel_net_mwh,coal_net_mwh,natural_gas_net_mwh,nuclear_net_mwh,other_net_mwh,other_gas_net_mwh,petroleum_net_mwh,petroleum_coke_net_mwh,renew_net_mwh,generator_starts,fuel_starts,gross_generation_mwh,biofuel_gross_mwh,coal_gross_mwh,natural_gas_gross_mwh,other_gross_mwh,other_gas_gross_mwh,petroleum_gross_mwh,petroleum_coke_gross_mwh,renew_gross_mwh,utility_id_eia,balancing_authority_code_eia,state,capacity_mw,associated_combined_heat_power,duct_burners,bypass_heat_recovery,solid_fuel_gasification,carbon_capture,fluidized_bed_tech,pulverized_coal_tech,stoker_tech,other_combustion_tech,subcritical_tech,supercritical_tech,ultrasupercritical_tech,age_in_report_year,age_of_observation,age_relative_to_prime_avg,pollution_control_costs_per_kw,respondent_id,respondent_id_purchaser,final_respondent_id,wage_scale,age_of_observation_secular_adj,_merge
0,3,3,2016,missing_years,ST,natural_gas,2,NaN,2016_ST_natural_gas,2016_ST_natural_gas_2,NaN,2016_ST_natural_gas_2_nan,1,1,0,2,2016-01-01,NaN,NaN,1.618925e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,233.870694,NaN,NaN,NaN,NaN,NaN,NaN,10.0,10.0,1.189000e+04,NaN,NaN,1.189000e+04,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,153.1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,61.913758,5.916496,23.737808,2.927320,2,<NA>,2,1.011758,23.20239,both
13,3,A1CT2,2008,missing_years,CC,natural_gas,2,NaN,2008_CC_natural_gas,2008_CC_natural_gas_2,NaN,2008_CC_natural_gas_2_nan,1,1,0,2,2008-01-01,NaN,NaN,6.091393e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,958225.064706,NaN,NaN,NaN,NaN,NaN,NaN,886.0,886.0,4.820953e+06,NaN,NaN,4.820953e+06,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,170.1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,7.668720,13.916496,-7.184464,2.927320,2,<NA>,2,0.99812,15.459785,both
28,8,10,2019,missing_years,ST,coal,2,NaN,2019_ST_coal,2019_ST_coal_2,NaN,2019_ST_coal_2_nan,1,1,0,2,2019-01-01,NaN,NaN,4.135949e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1952.538969,NaN,NaN,NaN,NaN,NaN,NaN,6.0,5.0,2.945400e+04,NaN,NaN,2.945400e+04,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,153.1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,64.914442,2.915811,26.738493,2.927320,2,<NA>,2,1.078991,26.305583,both
45,8,6,2016,missing_years,ST,coal,2,NaN,2016_ST_coal,2016_ST_coal_2,NaN,2016_ST_coal_2_nan,1,1,0,2,2016-01-01,NaN,NaN,1.618925e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,233.870694,NaN,NaN,NaN,NaN,NaN,NaN,10.0,10.0,1.189000e+04,NaN,NaN,1.189000e+04,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,153.1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,61.913758,5.916496,23.737808,2.927320,2,<NA>,2,1.011758,23.20239,both
65,8,7,2016,missing_years,ST,coal,2,NaN,2016_ST_coal,2016_ST_coal_2,NaN,2016_ST_coal_2_nan,1,1,0,2,2016-01-01,NaN,NaN,1.618925e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,233.870694,NaN,NaN,NaN,NaN,NaN,NaN,10.0,10.0,1.189000e+04,NaN,NaN,1.189000e+04,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,153.1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,61.913758,5.916496,23.737808,2.927320,2,<NA>,2,1.011758,23.20239,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
967277,63919,1,2019,zeroes,ST,natural_gas,MISO,3.167693,2019_ST_natural_gas,2019_ST_natural_gas_MISO,1,2019_ST_natural_gas_MISO_1,1,1,0,2,2019-01-01,NaN,8.779109e+06,8.995000e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,787574.221749,8160.783309,NaN,NaN,NaN,NaN,NaN,NaN,10.0,10.0,8.711970e+05,NaN,862361.320108,8.835680e+03,NaN,NaN,NaN,NaN,NaN,5748,GLHB,IL,183.3,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,65.418207,2.915811,27.242257,1.996825,50,<NA>,50,1.244645,32.626277,both
967453,63920,1,2019,zeroes,ST,natural_gas,PJM,4.167009,2019_ST_natural_gas,2019_ST_natural_gas_PJM,1,2019_ST_natural_gas_PJM_1,1,1,0,2,2019-01-01,NaN,NaN,7.626205e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,737505.000000,NaN,NaN,NaN,NaN,NaN,NaN,42.0,42.0,7.615760e+05,NaN,NaN,7.615760e+05,NaN,NaN,NaN,NaN,NaN,12384,PJM,IL,660.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,53.752225,2.915811,15.576275,23.455668,<NA>,<NA>,<NA>,1.244645,32.626277,both
967595,63922,G-745,2019,zeroes,ST,natural_gas,PJM,4.752909,2019_ST_natural_gas,2019_ST_natural_gas_PJM,1,2019_ST_natural_gas_PJM_1,1,1,0,2,2019-01-01,NaN,NaN,7.626205e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,737505.000000,NaN,NaN,NaN,NaN,NaN,NaN,42.0,42.0,7.615760e+05,NaN,NaN,7.615760e+05,NaN,NaN,NaN,NaN,NaN,12384,PJM,IL,660.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,53.752225,2.915811,15.576275,23.455668,<NA>,<NA>,<NA>,1.244645,32.626277,both
967737,63923,1,2019,zeroes,ST,natural_gas,MISO,3.082820,2019_ST_natural_gas,2019_ST_natural_gas_MISO,1,2019_ST_natural_gas_MISO_1,1,1,0,2,2019-01-01,NaN,8.779109e+06,8.995000e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,787574.221749,8160.783309,NaN,NaN,NaN,NaN,NaN,NaN,10.0,10.0,8.711970e+05,NaN,862361.320108,8.835680e+03,NaN,NaN,NaN,NaN,NaN,5748,GLHB,IL,183.3,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,65.418207,2.915811,27.242257,1.996825,50,<NA>,50,1.244645,32.626277,both
967913,63927,1,2019,zeroes,ST,natural_gas,PJM,4.418891,2019_ST_natural_gas,2019_ST_natural_gas_PJM,1,2019_ST_natural_gas_PJM_1,1,1,0,2,2019-01-01,NaN,NaN,7.626205e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,737505.000000,NaN,NaN,NaN,NaN,NaN,NaN,42.0,42.0,7.615760e+05,NaN,NaN,7.615760e+05,NaN,NaN,NaN,NaN,NaN,12384,PJM,IL,660.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,53.752225,2.915811,15.576275,23.455668,<NA>,<NA>,<NA>,1.244645,32.626277,both

In [125]:
m.query('fill_in_score == 1')

,plant_id_eia,generator_id,year,fuss,prime_mover,fuel_group,final_ba_code,age_in_current_year,essentials,ba_plus_essentials,age_range,ba_plus_age,essentials_present,ba_plus_essentials_present,ba_plus_age_present,fill_in_score,report_date,biofuel_mmbtu,coal_mmbtu,natural_gas_mmbtu,nuclear_mmbtu,other_mmbtu,other_gas_mmbtu,petroleum_mmbtu,petroleum_coke_mmbtu,renew_mmbtu,biofuel_net_mwh,coal_net_mwh,natural_gas_net_mwh,nuclear_net_mwh,other_net_mwh,other_gas_net_mwh,petroleum_net_mwh,petroleum_coke_net_mwh,renew_net_mwh,generator_starts,fuel_starts,gross_generation_mwh,biofuel_gross_mwh,coal_gross_mwh,natural_gas_gross_mwh,other_gross_mwh,other_gas_gross_mwh,petroleum_gross_mwh,petroleum_coke_gross_mwh,renew_gross_mwh,utility_id_eia,balancing_authority_code_eia,state,capacity_mw,associated_combined_heat_power,duct_burners,bypass_heat_recovery,solid_fuel_gasification,carbon_capture,fluidized_bed_tech,pulverized_coal_tech,stoker_tech,other_combustion_tech,subcritical_tech,supercritical_tech,ultrasupercritical_tech,age_in_report_year,age_of_observation,age_relative_to_prime_avg,pollution_control_costs_per_kw,respondent_id,respondent_id_purchaser,final_respondent_id,wage_scale,age_of_observation_secular_adj,_merge
0,9,1,2006,missing_years,GT,natural_gas,EPE,NaN,2006_GT_natural_gas,2006_GT_natural_gas_EPE,NaN,2006_GT_natural_gas_EPE_nan,1,0,0,1,2006-01-01,NaN,NaN,261284.189244,NaN,NaN,NaN,3703.0,NaN,NaN,NaN,NaN,27853.222222,NaN,NaN,NaN,240.222222,NaN,NaN,85.0,88.0,25411.0,NaN,NaN,25055.900068,NaN,NaN,355.099932,NaN,NaN,195,SOCO,AL,80.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,9.670089,15.915127,-12.342141,107.300831,2,<NA>,2,1.050357,13.40423,both
1184,310,2,2016,missing_years,ST,petroleum,None,NaN,2016_ST_petroleum,<NA>,NaN,<NA>,1,0,0,1,2016-01-01,NaN,373995.386529,771038.177507,NaN,NaN,NaN,0.0,NaN,NaN,NaN,75819.390226,17604.609865,NaN,NaN,NaN,0.000000,NaN,NaN,9.0,9.0,109697.0,NaN,35829.667535,73867.332465,NaN,NaN,0.000000,NaN,NaN,195,SOCO,AL,272.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,55.668720,5.916496,17.492771,0.582288,2,<NA>,2,1.011758,23.20239,both
1990,310,3,2016,missing_years,ST,natural_gas,None,NaN,2016_ST_natural_gas,<NA>,NaN,<NA>,1,0,0,1,2016-01-01,NaN,NaN,161892.503123,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,233.870694,NaN,NaN,NaN,NaN,NaN,NaN,10.0,10.0,11890.0,NaN,NaN,11890.000000,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,153.1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,61.913758,5.916496,23.737808,2.927320,2,<NA>,2,1.011758,23.20239,both
2840,310,4,2016,missing_years,ST,natural_gas,None,NaN,2016_ST_natural_gas,<NA>,NaN,<NA>,1,0,0,1,2016-01-01,NaN,NaN,161892.503123,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,233.870694,NaN,NaN,NaN,NaN,NaN,NaN,10.0,10.0,11890.0,NaN,NaN,11890.000000,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,153.1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,61.913758,5.916496,23.737808,2.927320,2,<NA>,2,1.011758,23.20239,both
3690,603,15,2016,missing_years,ST,petroleum,None,NaN,2016_ST_petroleum,<NA>,NaN,<NA>,1,0,0,1,2016-01-01,NaN,373995.386529,771038.177507,NaN,NaN,NaN,0.0,NaN,NaN,NaN,75819.390226,17604.609865,NaN,NaN,NaN,0.000000,NaN,NaN,9.0,9.0,109697.0,NaN,35829.667535,73867.332465,NaN,NaN,0.000000,NaN,NaN,195,SOCO,AL,272.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,55.668720,5.916496,17.492771,0.582288,2,<NA>,2,1.011758,23.20239,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3996801,64815,GEN2,2020,zeroes,IC,natural_gas,ERCO,2.42026,2020_IC_natural_gas,2020_IC_natural_gas_ERCO,1,2020_IC_natural_gas_ERCO_1,1,0,0,1,2020-01-01,NaN,NaN,124809.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13447.611111,NaN,NaN,NaN,NaN,NaN,NaN,147.0,149.0,323384.0,NaN,NaN,323384.000000,NaN,NaN,NaN,NaN,NaN,7349,SWPP,TX,9.3,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,8.585900,1.916496,-13.280621,NaN,58,<NA>,58,1.013692,27.335436,both
3996804,64815,GEN3,2020,zeroes,IC,natural_gas,ERCO,2.42026,2020_IC_natural_gas,2020_IC_natural_gas_ERCO,1,2020_IC_natural_gas_ERCO_1,1,0,0,1,2020-01-01,NaN,NaN,124809.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13447.611111,NaN,NaN,NaN,NaN,NaN,NaN,147.0,149.0,323384.0,NaN,NaN,323384.000000,NaN,NaN,NaN,NaN,NaN,7349,SWPP,TX,9.3,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,8.585900,1.916496,-13.280621,NaN,58,<NA>,58,1.013692,27.335436,both
3996807,64816,GEN1,2020,zeroes,IC,natural_gas,ERCO,1.24846,2020_IC_natural_gas,2020_IC_natural_gas_ERCO,1,2020_IC_natural_gas_ERCO_1,1,0,0,1,2020-01-01,NaN,NaN,124809.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13447.611111,NaN,NaN,NaN,NaN,NaN,NaN,147.0,149.0,323384.0,NaN,NaN,323384.000000,NaN,NaN,NaN,NaN,NaN,7349,SWPP,TX,9.3,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,8.585900,1.916496,-13.280621,NaN,58,<NA>,58,1.013692,27.335436,both
3996810,64816,GEN2,2020,zeroes,IC,natural_gas,ERCO,1.24846,2020_IC_natural_gas,2020_IC_natural_gas_ERCO,1,2020_IC_natural_gas_ERCO_1,1,0,0,1,2020-01-01,NaN,NaN,124809.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13447.611111,NaN,NaN,NaN,NaN,NaN,NaN,147.0,149.0,323384.0,NaN,NaN,323384.000000,NaN,NaN,NaN,NaN,NaN,7349,SWPP,TX,9.3,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,8.585900,1.916496,-13.280621,NaN,58,<NA>,58,1.013692,27.335436,both
3996813,64816,GEN3,2020,zeroes,IC,natural_gas,ERCO,1.24846,2020_IC_natural_gas,2020_IC_natural_gas_ERCO,1,2020_IC_natural_gas_ERCO_1,1,0,0,1,2020-01-01,NaN,NaN,124809.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13447.611111,NaN,NaN,NaN,NaN,NaN,NaN,147.0,149.0,323384.0,NaN,NaN,323384.000000,NaN,NaN,NaN,NaN,NaN,7349,SWPP,TX,9.3,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,8.585900,1.916496,-13.280621,NaN,58,<NA>,58,1.013692,27.335436,both

In [128]:
m = m.sort_values(by=['plant_id_eia','generator_id','year'],ascending=True)

In [133]:
m.query('plant_id_eia == 1',engine='python')

,plant_id_eia,generator_id,year,fuss,prime_mover,fuel_group,final_ba_code,age_in_current_year,essentials,ba_plus_essentials,age_range,ba_plus_age,essentials_present,ba_plus_essentials_present,ba_plus_age_present,fill_in_score,report_date,biofuel_mmbtu,coal_mmbtu,natural_gas_mmbtu,nuclear_mmbtu,other_mmbtu,other_gas_mmbtu,petroleum_mmbtu,petroleum_coke_mmbtu,renew_mmbtu,biofuel_net_mwh,coal_net_mwh,natural_gas_net_mwh,nuclear_net_mwh,other_net_mwh,other_gas_net_mwh,petroleum_net_mwh,petroleum_coke_net_mwh,renew_net_mwh,generator_starts,fuel_starts,gross_generation_mwh,biofuel_gross_mwh,coal_gross_mwh,natural_gas_gross_mwh,other_gross_mwh,other_gas_gross_mwh,petroleum_gross_mwh,petroleum_coke_gross_mwh,renew_gross_mwh,utility_id_eia,balancing_authority_code_eia,state,capacity_mw,associated_combined_heat_power,duct_burners,bypass_heat_recovery,solid_fuel_gasification,carbon_capture,fluidized_bed_tech,pulverized_coal_tech,stoker_tech,other_combustion_tech,subcritical_tech,supercritical_tech,ultrasupercritical_tech,age_in_report_year,age_of_observation,age_relative_to_prime_avg,pollution_control_costs_per_kw,respondent_id,respondent_id_purchaser,final_respondent_id,wage_scale,age_of_observation_secular_adj,_merge
785664,1,1,2020,zeroes,IC,petroleum,Alaska,20.999316,2020_IC_petroleum,2020_IC_petroleum_Alaska,3,2020_IC_petroleum_Alaska_3,1,0,0,1,2020-01-01,NaN,NaN,NaN,NaN,NaN,NaN,343.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,138.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,20847,MISO,WI,2.7,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,50.836413,1.916496,28.969892,106.666667,193,<NA>,193,0.959081,26.618848,both
785667,1,2,2020,zeroes,IC,petroleum,Alaska,20.999316,2020_IC_petroleum,2020_IC_petroleum_Alaska,3,2020_IC_petroleum_Alaska_3,1,0,0,1,2020-01-01,NaN,NaN,NaN,NaN,NaN,NaN,343.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,138.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,20847,MISO,WI,2.7,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,50.836413,1.916496,28.969892,106.666667,193,<NA>,193,0.959081,26.618848,both
785670,1,3,2020,zeroes,IC,petroleum,Alaska,11.000684,2020_IC_petroleum,2020_IC_petroleum_Alaska,2,2020_IC_petroleum_Alaska_2,1,0,0,1,2020-01-01,NaN,NaN,NaN,NaN,NaN,NaN,343.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,138.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,20847,MISO,WI,2.7,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,50.836413,1.916496,28.969892,106.666667,193,<NA>,193,0.959081,26.618848,both
785673,1,5,2020,zeroes,IC,petroleum,Alaska,20.999316,2020_IC_petroleum,2020_IC_petroleum_Alaska,3,2020_IC_petroleum_Alaska_3,1,0,0,1,2020-01-01,NaN,NaN,NaN,NaN,NaN,NaN,343.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,138.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,20847,MISO,WI,2.7,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,50.836413,1.916496,28.969892,106.666667,193,<NA>,193,0.959081,26.618848,both

In [131]:
m.query('fill_in_score == 1')

,plant_id_eia,generator_id,year,fuss,prime_mover,fuel_group,final_ba_code,age_in_current_year,essentials,ba_plus_essentials,age_range,ba_plus_age,essentials_present,ba_plus_essentials_present,ba_plus_age_present,fill_in_score,report_date,biofuel_mmbtu,coal_mmbtu,natural_gas_mmbtu,nuclear_mmbtu,other_mmbtu,other_gas_mmbtu,petroleum_mmbtu,petroleum_coke_mmbtu,renew_mmbtu,biofuel_net_mwh,coal_net_mwh,natural_gas_net_mwh,nuclear_net_mwh,other_net_mwh,other_gas_net_mwh,petroleum_net_mwh,petroleum_coke_net_mwh,renew_net_mwh,generator_starts,fuel_starts,gross_generation_mwh,biofuel_gross_mwh,coal_gross_mwh,natural_gas_gross_mwh,other_gross_mwh,other_gas_gross_mwh,petroleum_gross_mwh,petroleum_coke_gross_mwh,renew_gross_mwh,utility_id_eia,balancing_authority_code_eia,state,capacity_mw,associated_combined_heat_power,duct_burners,bypass_heat_recovery,solid_fuel_gasification,carbon_capture,fluidized_bed_tech,pulverized_coal_tech,stoker_tech,other_combustion_tech,subcritical_tech,supercritical_tech,ultrasupercritical_tech,age_in_report_year,age_of_observation,age_relative_to_prime_avg,pollution_control_costs_per_kw,respondent_id,respondent_id_purchaser,final_respondent_id,wage_scale,age_of_observation_secular_adj,_merge
785664,1,1,2020,zeroes,IC,petroleum,Alaska,20.999316,2020_IC_petroleum,2020_IC_petroleum_Alaska,3,2020_IC_petroleum_Alaska_3,1,0,0,1,2020-01-01,NaN,NaN,NaN,NaN,NaN,NaN,343.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,0.0,138.0,0.0,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,20847,MISO,WI,2.7,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,50.836413,1.916496,28.969892,106.666667,193,<NA>,193,0.959081,26.618848,both
785667,1,2,2020,zeroes,IC,petroleum,Alaska,20.999316,2020_IC_petroleum,2020_IC_petroleum_Alaska,3,2020_IC_petroleum_Alaska_3,1,0,0,1,2020-01-01,NaN,NaN,NaN,NaN,NaN,NaN,343.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,0.0,138.0,0.0,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,20847,MISO,WI,2.7,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,50.836413,1.916496,28.969892,106.666667,193,<NA>,193,0.959081,26.618848,both
785670,1,3,2020,zeroes,IC,petroleum,Alaska,11.000684,2020_IC_petroleum,2020_IC_petroleum_Alaska,2,2020_IC_petroleum_Alaska_2,1,0,0,1,2020-01-01,NaN,NaN,NaN,NaN,NaN,NaN,343.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,0.0,138.0,0.0,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,20847,MISO,WI,2.7,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,50.836413,1.916496,28.969892,106.666667,193,<NA>,193,0.959081,26.618848,both
785673,1,5,2020,zeroes,IC,petroleum,Alaska,20.999316,2020_IC_petroleum,2020_IC_petroleum_Alaska,3,2020_IC_petroleum_Alaska_3,1,0,0,1,2020-01-01,NaN,NaN,NaN,NaN,NaN,NaN,343.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,0.0,138.0,0.0,NaN,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,20847,MISO,WI,2.7,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,50.836413,1.916496,28.969892,106.666667,193,<NA>,193,0.959081,26.618848,both
0,9,1,2006,missing_years,GT,natural_gas,EPE,NaN,2006_GT_natural_gas,2006_GT_natural_gas_EPE,NaN,2006_GT_natural_gas_EPE_nan,1,0,0,1,2006-01-01,NaN,NaN,261284.189244,NaN,NaN,NaN,3703.0,NaN,NaN,NaN,NaN,27853.222222,NaN,NaN,NaN,240.222222,NaN,NaN,85.0,88.0,25411.0,NaN,NaN,25055.900068,NaN,NaN,355.099932,NaN,NaN,195,SOCO,AL,80.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,9.670089,15.915127,-12.342141,107.300831,2,<NA>,2,1.050357,13.40423,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3996801,64815,GEN2,2020,zeroes,IC,natural_gas,ERCO,2.420260,2020_IC_natural_gas,2020_IC_natural_gas_ERCO,1,2020_IC_natural_gas_ERCO_1,1,0,0,1,2020-01-01,NaN,NaN,124809.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13447.611111,NaN,NaN,NaN,NaN,NaN,NaN,147.0,149.0,323384.0,NaN,NaN,323384.000000,NaN,NaN,NaN,NaN,NaN,7349,SWPP,TX,9.3,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,8.585900,1.916496,-13.280621,NaN,58,<NA>,58,1.013692,27.335436,both
3996804,64815,GEN3,2020,zeroes,IC,natural_gas,ERCO,2.420260,2020_IC_natural_gas,2020_IC_natural_gas_ERCO,1,2020_IC_natural_gas_ERCO_1,1,0,0,1,2020-01-01,NaN,NaN,124809.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13447.611111,NaN,NaN,NaN,NaN,NaN,NaN,147.0,149.0,323384.0,NaN,NaN,323384.000000,NaN,NaN,NaN,NaN,NaN,7349,SWPP,TX,9.3,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,8.585900,1.916496,-13.280621,NaN,58,<NA>,58,1.013692,27.335436,both
3996807,64816,GEN1,2020,zeroes,IC,natural_gas,ERCO,1.248460,2020_IC_natural_gas,2020_IC_natural_gas_ERCO,1,2020_IC_natural_gas_ERCO_1,1,0,0,1,2020-01-01,NaN,NaN,124809.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13447.611111,NaN,NaN,NaN,NaN,NaN,NaN,147.0,149.0,323384.0,NaN,NaN,323384.000000,NaN,NaN,NaN,NaN,NaN,7349,SWPP,TX,9.3,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,8.585900,1.916496,-13.280621,NaN,58,<NA>,58,1.013692,27.335436,both
3996810,64816,GEN2,2020,zeroes,IC,natural_gas,ERCO,1.248460,2020_IC_natural_gas,2020_IC_natural_gas_ERCO,1,2020_IC_natural_gas_ERCO_1,1,0,0,1,2020-01-01,NaN,NaN,124809.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13447.611111,NaN,NaN,NaN,NaN,NaN,NaN,147.0,149.0,323384.0,NaN,NaN,323384.000000,NaN,NaN,NaN,NaN,NaN,7349,SWPP,TX,9.3,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,8.585900,1.916496,-13.280621,NaN,58,<NA>,58,1.013692,27.335436,both
3996813,64816,GEN3,2020,zeroes,IC,natural_gas,ERCO,1.248460,2020_IC_natural_gas,2020_IC_natural_gas_ERCO,1,2020_IC_natural_gas_ERCO_1,1,0,0,1,2020-01-01,NaN,NaN,124809.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13447.611111,NaN,NaN,NaN,NaN,NaN,NaN,147.0,149.0,323384.0,NaN,NaN,323384.000000,NaN,NaN,NaN,NaN,NaN,7349,SWPP,TX,9.3,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,8.585900,1.916496,-13.280621,NaN,58,<NA>,58,1.013692,27.335436,both

In [132]:
m.query('fill_in_score == 3')

,plant_id_eia,generator_id,year,fuss,prime_mover,fuel_group,final_ba_code,age_in_current_year,essentials,ba_plus_essentials,age_range,ba_plus_age,essentials_present,ba_plus_essentials_present,ba_plus_age_present,fill_in_score,report_date,biofuel_mmbtu,coal_mmbtu,natural_gas_mmbtu,nuclear_mmbtu,other_mmbtu,other_gas_mmbtu,petroleum_mmbtu,petroleum_coke_mmbtu,renew_mmbtu,biofuel_net_mwh,coal_net_mwh,natural_gas_net_mwh,nuclear_net_mwh,other_net_mwh,other_gas_net_mwh,petroleum_net_mwh,petroleum_coke_net_mwh,renew_net_mwh,generator_starts,fuel_starts,gross_generation_mwh,biofuel_gross_mwh,coal_gross_mwh,natural_gas_gross_mwh,other_gross_mwh,other_gas_gross_mwh,petroleum_gross_mwh,petroleum_coke_gross_mwh,renew_gross_mwh,utility_id_eia,balancing_authority_code_eia,state,capacity_mw,associated_combined_heat_power,duct_burners,bypass_heat_recovery,solid_fuel_gasification,carbon_capture,fluidized_bed_tech,pulverized_coal_tech,stoker_tech,other_combustion_tech,subcritical_tech,supercritical_tech,ultrasupercritical_tech,age_in_report_year,age_of_observation,age_relative_to_prime_avg,pollution_control_costs_per_kw,respondent_id,respondent_id_purchaser,final_respondent_id,wage_scale,age_of_observation_secular_adj,_merge
335705,3,1,2006,fuel_switch,ST,natural_gas,2,67.830253,2006_ST_natural_gas,2006_ST_natural_gas_2,7,2006_ST_natural_gas_2_7,1,1,1,3,2006-01-01,NaN,1.008871e+07,29511.495021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,964082.899927,4120.479810,NaN,NaN,NaN,NaN,NaN,NaN,7.0,7.0,1123980.0,NaN,1.120702e+06,3278.277774,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,153.1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,51.915127,15.915127,13.739177,2.927320,2,<NA>,2,1.050357,13.40423,both
335711,3,1,2007,fuel_switch,ST,natural_gas,2,67.830253,2007_ST_natural_gas,2007_ST_natural_gas_2,7,2007_ST_natural_gas_2_7,1,1,1,3,2007-01-01,NaN,9.807031e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,954656.813326,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,13.0,1028301.0,NaN,1.028301e+06,NaN,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,153.1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,52.914442,14.915811,14.738493,2.927320,2,<NA>,2,1.057435,14.461664,both
335717,3,1,2008,fuel_switch,ST,natural_gas,2,67.830253,2008_ST_natural_gas,2008_ST_natural_gas_2,7,2008_ST_natural_gas_2_7,1,1,1,3,2008-01-01,NaN,8.176078e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,865288.470536,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.0,15.0,928095.0,NaN,9.280950e+05,NaN,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,153.1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,53.913758,13.916496,15.737808,2.927320,2,<NA>,2,0.99812,15.459785,both
335723,3,1,2009,fuel_switch,ST,natural_gas,2,67.830253,2009_ST_natural_gas,2009_ST_natural_gas_2,7,2009_ST_natural_gas_2_7,1,1,1,3,2009-01-01,NaN,2.274497e+06,7626.184443,NaN,NaN,NaN,NaN,NaN,NaN,NaN,216274.279645,5633.720355,NaN,NaN,NaN,NaN,NaN,NaN,44.0,44.0,243753.0,NaN,2.429384e+05,814.550756,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,153.1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,54.915811,12.914442,16.739862,2.927320,2,<NA>,2,0.97293,16.432715,both
335729,3,1,2010,fuel_switch,ST,natural_gas,2,67.830253,2010_ST_natural_gas,2010_ST_natural_gas_2,7,2010_ST_natural_gas_2_7,1,1,1,3,2010-01-01,NaN,4.481317e+06,42982.723242,NaN,NaN,NaN,NaN,NaN,NaN,NaN,428843.516663,6490.483337,NaN,NaN,NaN,NaN,NaN,NaN,14.0,14.0,469201.0,NaN,4.647434e+05,4457.603912,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,153.1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,55.915127,11.915127,17.739177,2.927320,2,<NA>,2,0.941299,17.374014,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
334978,63478,CT-1,2020,zeroes,GT,natural_gas,PJM,5.166324,2020_GT_natural_gas,2020_GT_natural_gas_PJM,1,2020_GT_natural_gas_PJM_1,1,1,1,3,2020-01-01,NaN,NaN,798932.675676,NaN,NaN,NaN,77674.302255,NaN,NaN,NaN,NaN,71619.989676,NaN,NaN,NaN,6988.971030,NaN,NaN,295.0,305.0,112076.0,NaN,NaN,102145.181151,NaN,NaN,9930.818849,NaN,NaN,4161,PJM,MD,141.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,4.585900,1.916496,-17.426330,35.158767,<NA>,<NA>,<NA>,1.151084,31.796804,both
334992,63483,T60-1,2019,zeroes,GT,petroleum,PJM,9.916496,2019_GT_petroleum,2019_GT_petroleum_PJM,1,2019_GT_petroleum_PJM_1,1,1,1,3,2019-01-01,NaN,NaN,821712.855856,NaN,NaN,NaN,43952.303473,NaN,NaN,NaN,NaN,79957.671964,NaN,NaN,NaN,4085.876977,NaN,NaN,437.0,442.0,155248.0,NaN,NaN,147365.613680,NaN,NaN,7882.386320,NaN,NaN,4161,PJM,MD,141.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,3.586585,2.915811,-18.425645,35.158767,<NA>,<NA>,<NA>,1.21606,30.64572,both
334998,63501,CTG-1,2019,zeroes,GT,natural_gas,PJM,8.249144,2019_GT_natural_gas,2019_GT_natural_gas_PJM,1,2019_GT_natural_gas_PJM_1,1,1,1,3,2019-01-01,NaN,NaN,821712.855856,NaN,NaN,NaN,43952.303473,NaN,NaN,NaN,NaN,79957.671964,NaN,NaN,NaN,4085.876977,NaN,NaN,437.0,442.0,155248.0,NaN,NaN,147365.613680,NaN,NaN,7882.386320,NaN,NaN,4161,PJM,MD,141.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,3.586585,2.915811,-18.425645,35.158767,<NA>,<NA>,<NA>,1.21606,30.64572,both
335018,63501,CTG-1,2020,zeroes,GT,natural_gas,PJM,8.249144,2020_GT_natural_gas,2020_GT_natural_gas_PJM,1,2020_GT_natural_gas_PJM_1,1,1,1,3,2020-01-01,NaN,NaN,798932.675676,NaN,NaN,NaN,77674.302255,NaN,NaN,NaN,NaN,71619.989676,NaN,NaN,NaN,6988.971030,NaN,NaN,295.0,305.0,112076.0,NaN,NaN,102145.181151,NaN,NaN,9930.818849,NaN,NaN,4161,PJM,MD,141.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,4.585900,1.916496,-17.426330,35.158767,<NA>,<NA>,<NA>,1.151084,31.796804,both
335038,63924,1,2019,zeroes,ST,natural_gas,PJM,13.667351,2019_ST_natural_gas,2019_ST_natural_gas_PJM,2,2019_ST_natural_gas_PJM_2,1,1,1,3,2019-01-01,NaN,NaN,403526.984385,NaN,NaN,1.750215e+06,0.000000,NaN,NaN,NaN,NaN,9961.137399,NaN,NaN,54443.508592,0.000000,NaN,NaN,0.0,15.0,0.0,NaN,NaN,0.000000,NaN,0.0,0.000000,NaN,NaN,9454,PJM,OH,22.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,8.914442,2.915811,-29.261507,NaN,<NA>,<NA>,<NA>,0.956126,25.06535,both

In [ ]:
    .merge(
                df_860.assign(year=lambda x: x["report_date"].dt.year)[
                    [
                        "plant_id_eia",
                        "generator_id",
                        "year",
                        "final_ba_code",
                        "age_in_current_year",
                    ]
                ],
                on=["plant_id_eia", "generator_id", "year"],
                how="left",
                # indicator=True,
            )
        )[
            [
                "plant_id_eia",
                "generator_id",
                "year",
                "fuss",
                "prime_mover",
                "fuel_group",
                "final_ba_code",
                "age_in_current_year",
            ]
        ]

In [105]:
from gencost.constants import FOSSIL_PRIME_MOVER_MAP, FUEL_GROUP_MAP, GET_860_GEN_COLS

In [111]:
single_fuel_switch = (
            hist_data.pipe(self.filter_to_single_fuel_generators)
            .assign(
                n_fuels=lambda x: x.groupby(["plant_id_eia", "generator_id"])[
                    "mmbtu"
                ].transform("nunique")
            )
            .query("n_fuels > 1")
            .assign(
                fuss=lambda x: "fuel_switch",
                year=lambda x: x["report_date"].dt.year,
                fuel=lambda x: x.groupby(["plant_id_eia", "generator_id"])[
                    "mmbtu"
                ].transform("last"),
                fuel_reported_is_latest_fuel=lambda x: np.where(
                    x["mmbtu"] == x["fuel"], True, False
                ),
            )
            .query("fuel_reported_is_latest_fuel == False")
            .assign(fuel_group=lambda x: x["fuel"].str.replace("_mmbtu", ""))
            .merge(xwalk, on=["plant_id_eia", "generator_id", "fuel_group"], how="left")
        )

zero_reported = (
    self.get_gf923_by_generator(counterfactuals=True)
    .groupby(
        [
            "plant_id_eia",
            "generator_id",
            pd.Grouper(key="report_date", freq="YS"),
            'prime_mover_code','fuel_group'
        ]
    )
    .agg({"net_mwh": "sum", "mmbtu": "sum"})
    .reset_index()
    .query(
        'net_mwh == 0 & mmbtu == 0 & report_date >= "2006-01-01" & report_date <= "2020-01-01"'
    )
    .assign(
        prime_mover=lambda x: x.prime_mover_code.replace(FOSSIL_PRIME_MOVER_MAP),
        year=lambda x: x["report_date"].dt.year,
        fuss = 'zeroes'

    )
)

In [112]:
zero_and_fuel_switch = (pd.concat([zero_reported,single_fuel_switch])
    .merge(
                df_860.assign(year=lambda x: x["report_date"].dt.year)[
                    [
                        "plant_id_eia",
                        "generator_id",
                        "year",
                        "final_ba_code",
                        "age_in_current_year",
                    ]
                ],
                on=["plant_id_eia", "generator_id", "year"],
                how="left",
                # indicator=True,
            )
        )[
            [
                "plant_id_eia",
                "generator_id",
                "year",
                "fuss",
                "prime_mover",
                "fuel_group",
                "final_ba_code",
                "age_in_current_year",
            ]
        ]

In [113]:
zero_and_fuel_switch

,plant_id_eia,generator_id,year,fuss,prime_mover,fuel_group,final_ba_code,age_in_current_year
0,1,1,2020,zeroes,IC,petroleum,Alaska,20.999316
1,1,2,2020,zeroes,IC,petroleum,Alaska,20.999316
2,1,3,2020,zeroes,IC,petroleum,Alaska,11.000684
3,1,5,2020,zeroes,IC,petroleum,Alaska,20.999316
4,3,A1ST,2006,zeroes,CC,natural_gas,2,21.585216
...,...,...,...,...,...,...,...,...
42170,55088,ST1,2011,fuel_switch,ST,other_gas,MISO,20.334018
42171,55088,ST1,2011,fuel_switch,ST,other_gas,MISO,20.334018
42172,55088,ST1,2011,fuel_switch,ST,other_gas,MISO,20.334018
42173,55088,ST1,2011,fuel_switch,ST,other_gas,MISO,20.334018
42174,55088,ST1,2011,fuel_switch,ST,other_gas,MISO,20.334018

In [145]:
m.columns

Index(['plant_id_eia', 'generator_id', 'year', 'fuss', 'prime_mover',
       'fuel_group', 'final_ba_code', 'age_in_current_year', 'essentials',
       'ba_plus_essentials', 'age_range', 'ba_plus_age', 'essentials_present',
       'ba_plus_essentials_present', 'ba_plus_age_present', 'fill_in_score',
       'report_date', 'biofuel_mmbtu', 'coal_mmbtu', 'natural_gas_mmbtu',
       'nuclear_mmbtu', 'other_mmbtu', 'other_gas_mmbtu', 'petroleum_mmbtu',
       'petroleum_coke_mmbtu', 'renew_mmbtu', 'biofuel_net_mwh',
       'coal_net_mwh', 'natural_gas_net_mwh', 'nuclear_net_mwh',
       'other_net_mwh', 'other_gas_net_mwh', 'petroleum_net_mwh',
       'petroleum_coke_net_mwh', 'renew_net_mwh', 'generator_starts',
       'fuel_starts', 'gross_generation_mwh', 'biofuel_gross_mwh',
       'coal_gross_mwh', 'natural_gas_gross_mwh', 'other_gross_mwh',
       'other_gas_gross_mwh', 'petroleum_gross_mwh',
       'petroleum_coke_gross_mwh', 'renew_gross_mwh', 'utility_id_eia',
       'balancing_authority_code_eia', 'state', 'capacity_mw',
       'associated_combined_heat_power', 'duct_burners',
       'bypass_heat_recovery', 'solid_fuel_gasification', 'carbon_capture',
       'fluidized_bed_tech', 'pulverized_coal_tech', 'stoker_tech',
       'other_combustion_tech', 'subcritical_tech', 'supercritical_tech',
       'ultrasupercritical_tech', 'age_in_report_year', 'age_of_observation',
       'age_relative_to_prime_avg', 'pollution_control_costs_per_kw',
       'respondent_id', 'respondent_id_purchaser', 'final_respondent_id',
       'wage_scale', 'age_of_observation_secular_adj', '_merge'],
      dtype='object')

In [135]:
m.head(40)

,plant_id_eia,generator_id,year,fuss,prime_mover,fuel_group,final_ba_code,age_in_current_year,essentials,ba_plus_essentials,age_range,ba_plus_age,essentials_present,ba_plus_essentials_present,ba_plus_age_present,fill_in_score,report_date,biofuel_mmbtu,coal_mmbtu,natural_gas_mmbtu,nuclear_mmbtu,other_mmbtu,other_gas_mmbtu,petroleum_mmbtu,petroleum_coke_mmbtu,renew_mmbtu,biofuel_net_mwh,coal_net_mwh,natural_gas_net_mwh,nuclear_net_mwh,other_net_mwh,other_gas_net_mwh,petroleum_net_mwh,petroleum_coke_net_mwh,renew_net_mwh,generator_starts,fuel_starts,gross_generation_mwh,biofuel_gross_mwh,coal_gross_mwh,natural_gas_gross_mwh,other_gross_mwh,other_gas_gross_mwh,petroleum_gross_mwh,petroleum_coke_gross_mwh,renew_gross_mwh,utility_id_eia,balancing_authority_code_eia,state,capacity_mw,associated_combined_heat_power,duct_burners,bypass_heat_recovery,solid_fuel_gasification,carbon_capture,fluidized_bed_tech,pulverized_coal_tech,stoker_tech,other_combustion_tech,subcritical_tech,supercritical_tech,ultrasupercritical_tech,age_in_report_year,age_of_observation,age_relative_to_prime_avg,pollution_control_costs_per_kw,respondent_id,respondent_id_purchaser,final_respondent_id,wage_scale,age_of_observation_secular_adj,_merge
785664,1,1,2020,zeroes,IC,petroleum,Alaska,20.999316,2020_IC_petroleum,2020_IC_petroleum_Alaska,3,2020_IC_petroleum_Alaska_3,1,0,0,1,2020-01-01,NaN,NaN,NaN,NaN,NaN,NaN,343.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,138.0,0.000000e+00,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,20847,MISO,WI,2.7,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,50.836413,1.916496,28.969892,106.666667,193,<NA>,193,0.959081,26.618848,both
785667,1,2,2020,zeroes,IC,petroleum,Alaska,20.999316,2020_IC_petroleum,2020_IC_petroleum_Alaska,3,2020_IC_petroleum_Alaska_3,1,0,0,1,2020-01-01,NaN,NaN,NaN,NaN,NaN,NaN,343.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,138.0,0.000000e+00,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,20847,MISO,WI,2.7,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,50.836413,1.916496,28.969892,106.666667,193,<NA>,193,0.959081,26.618848,both
785670,1,3,2020,zeroes,IC,petroleum,Alaska,11.000684,2020_IC_petroleum,2020_IC_petroleum_Alaska,2,2020_IC_petroleum_Alaska_2,1,0,0,1,2020-01-01,NaN,NaN,NaN,NaN,NaN,NaN,343.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,138.0,0.000000e+00,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,20847,MISO,WI,2.7,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,50.836413,1.916496,28.969892,106.666667,193,<NA>,193,0.959081,26.618848,both
785673,1,5,2020,zeroes,IC,petroleum,Alaska,20.999316,2020_IC_petroleum,2020_IC_petroleum_Alaska,3,2020_IC_petroleum_Alaska_3,1,0,0,1,2020-01-01,NaN,NaN,NaN,NaN,NaN,NaN,343.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,138.0,0.000000e+00,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,20847,MISO,WI,2.7,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,50.836413,1.916496,28.969892,106.666667,193,<NA>,193,0.959081,26.618848,both
335705,3,1,2006,fuel_switch,ST,natural_gas,2,67.830253,2006_ST_natural_gas,2006_ST_natural_gas_2,7,2006_ST_natural_gas_2_7,1,1,1,3,2006-01-01,NaN,1.008871e+07,2.951150e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,964082.899927,4.120480e+03,NaN,NaN,NaN,NaN,NaN,NaN,7.0,7.0,1.123980e+06,NaN,1.120702e+06,3.278278e+03,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,153.1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,51.915127,15.915127,13.739177,2.927320,2,<NA>,2,1.050357,13.40423,both
335711,3,1,2007,fuel_switch,ST,natural_gas,2,67.830253,2007_ST_natural_gas,2007_ST_natural_gas_2,7,2007_ST_natural_gas_2_7,1,1,1,3,2007-01-01,NaN,9.807031e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,954656.813326,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,13.0,1.028301e+06,NaN,1.028301e+06,NaN,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,153.1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,52.914442,14.915811,14.738493,2.927320,2,<NA>,2,1.057435,14.461664,both
335717,3,1,2008,fuel_switch,ST,natural_gas,2,67.830253,2008_ST_natural_gas,2008_ST_natural_gas_2,7,2008_ST_natural_gas_2_7,1,1,1,3,2008-01-01,NaN,8.176078e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,865288.470536,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.0,15.0,9.280950e+05,NaN,9.280950e+05,NaN,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,153.1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,53.913758,13.916496,15.737808,2.927320,2,<NA>,2,0.99812,15.459785,both
335723,3,1,2009,fuel_switch,ST,natural_gas,2,67.830253,2009_ST_natural_gas,2009_ST_natural_gas_2,7,2009_ST_natural_gas_2_7,1,1,1,3,2009-01-01,NaN,2.274497e+06,7.626184e+03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,216274.279645,5.633720e+03,NaN,NaN,NaN,NaN,NaN,NaN,44.0,44.0,2.437530e+05,NaN,2.429384e+05,8.145508e+02,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,153.1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,54.915811,12.914442,16.739862,2.927320,2,<NA>,2,0.97293,16.432715,both
335729,3,1,2010,fuel_switch,ST,natural_gas,2,67.830253,2010_ST_natural_gas,2010_ST_natural_gas_2,7,2010_ST_natural_gas_2_7,1,1,1,3,2010-01-01,NaN,4.481317e+06,4.298272e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,428843.516663,6.490483e+03,NaN,NaN,NaN,NaN,NaN,NaN,14.0,14.0,4.692010e+05,NaN,4.647434e+05,4.457604e+03,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,153.1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,55.915127,11.915127,17.739177,2.927320,2,<NA>,2,0.941299,17.374014,both
335735,3,1,2013,fuel_switch,ST,natural_gas,2,67.830253,2013_ST_natural_gas,2013_ST_natural_gas_2,7,2013_ST_natural_gas_2_7,1,1,1,3,2013-01-01,NaN,3.448870e+05,3.609989e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30367.124070,2.598759e+02,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,3.714500e+04,NaN,3.362538e+04,3.519624e+03,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,153.1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,58.915811,8.914442,20.739862,2.927320,2,<NA>,2,0.951011,20.281903,both
335741,3,2,2006,fuel_switch,ST,natural_gas,2,67.419576,2006_ST_natural_gas,2006_ST_natural_gas_2,7,2006_ST_natural_gas_2_7,1,1,1,3,2006-01-01,NaN,1.008871e+07,2.951150e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,964082.899927,4.120480e+03,NaN,NaN,NaN,NaN,NaN,NaN,7.0,7.0,1.123980e+06,NaN,1.120702e+06,3.278278e+03,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,153.1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,51.915127,15.915127,13.739177,2.927320,2,<NA>,2,1.050357,13.40423,both
335747,3,2,2007,fuel_switch,ST,natural_gas,2,67.419576,2007_ST_natural_gas,2007_ST_natural_gas_2,7,2007_ST_natural_gas_2_7,1,1,1,3,2007-01-01,NaN,9.807031e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,954656.813326,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13.0,13.0,1.028301e+06,NaN,1.028301e+06,NaN,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,153.1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,52.914442,14.915811,14.738493,2.927320,2,<NA>,2,1.057435,14.461664,both
335753,3,2,2008,fuel_switch,ST,natural_gas,2,67.419576,2008_ST_natural_gas,2008_ST_natural_gas_2,7,2008_ST_natural_gas_2_7,1,1,1,3,2008-01-01,NaN,8.176078e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,865288.470536,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.0,15.0,9.280950e+05,NaN,9.280950e+05,NaN,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,153.1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,53.913758,13.916496,15.737808,2.927320,2,<NA>,2,0.99812,15.459785,both
335759,3,2,2009,fuel_switch,ST,natural_gas,2,67.419576,2009_ST_natural_gas,2009_ST_natural_gas_2,7,2009_ST_natural_gas_2_7,1,1,1,3,2009-01-01,NaN,2.274497e+06,7.626184e+03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,216274.279645,5.633720e+03,NaN,NaN,NaN,NaN,NaN,NaN,44.0,44.0,2.437530e+05,NaN,2.429384e+05,8.145508e+02,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,153.1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,54.915811,12.914442,16.739862,2.927320,2,<NA>,2,0.97293,16.432715,both
335765,3,2,2010,fuel_switch,ST,natural_gas,2,67.419576,2010_ST_natural_gas,2010_ST_natural_gas_2,7,2010_ST_natural_gas_2_7,1,1,1,3,2010-01-01,NaN,4.481317e+06,4.298272e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,428843.516663,6.490483e+03,NaN,NaN,NaN,NaN,NaN,NaN,14.0,14.0,4.692010e+05,NaN,4.647434e+05,4.457604e+03,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,153.1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,55.915127,11.915127,17.739177,2.927320,2,<NA>,2,0.941299,17.374014,both
335771,3,2,2011,fuel_switch,ST,natural_gas,2,67.419576,2011_ST_natural_gas,2011_ST_natural_gas_2,7,2011_ST_natural_gas_2_7,1,1,1,3,2011-01-01,NaN,3.154614e+06,4.107054e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,300067.984077,1.206202e+04,NaN,NaN,NaN,NaN,NaN,NaN,9.0,9.0,3.446310e+05,NaN,3.049314e+05,3.969962e+04,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,153.1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,56.914442,10.915811,18.738493,2.927320,2,<NA>,2,0.973222,18.347236,both
335777,3,2,2014,fuel_switch,ST,natural_gas,2,67.419576,2014_ST_natural_gas,2014_ST_natural_gas_2,7,2014_ST_natural_gas_2_7,1,1,1,3,2014-01-01,NaN,2.479372e+05,3.080142e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18975.754113,6.382459e+02,NaN,NaN,NaN,NaN,NaN,NaN,3.0,3.0,2.694900e+04,NaN,2.397106e+04,2.977943e+03,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,153.1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,59.915127,7.915127,21.739177,2.927320,2,<NA>,2,0.935684,21.217587,both
496821,3,3,2015,missing_years,ST,natural_gas,2,NaN,2015_ST_natural_gas,2015_ST_natural_gas_2,NaN,2015_ST_natural_gas_2_nan,1,1,0,2,2015-01-01,NaN,NaN,5.947680e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.199438e+01,NaN,NaN,NaN,NaN,NaN,NaN,6.0,6.0,4.936000e+03,NaN,NaN,4.936000e+03,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,153.1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,60.914442,6.915811,22.738493,2.927320,2,<NA>,2,0.973045,22.190632,both
0,3,3,2016,missing_years,ST,natural_gas,2,NaN,2016_ST_natural_gas,2016_ST_natural_gas_2,NaN,2016_ST_natural_gas_2_nan,1,1,0,2,2016-01-01,NaN,NaN,1.618925e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.338707e+02,NaN,NaN,NaN,NaN,NaN,NaN,10.0,10.0,1.189000e+04,NaN,NaN,1.189000e+04,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,153.1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,61.913758,5.916496,23.737808,2.927320,2,<NA>,2,1.011758,23.20239,both
145400,3,3,2017,missing_years,ST,natural_gas,2,NaN,2017_ST_natural_gas,2017_ST_natural_gas_2,NaN,2017_ST_natural_gas_2_nan,1,1,0,2,2017-01-01,NaN,NaN,1.966532e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.150019e+03,NaN,NaN,NaN,NaN,NaN,NaN,5.0,5.0,1.293100e+04,NaN,NaN,1.293100e+04,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,153.1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,62.915811,4.914442,24.739862,2.927320,2,<NA>,2,1.003936,24.206326,both
279039,3,3,2018,missing_years,ST,natural_gas,2,NaN,2018_ST_natural_gas,2018_ST_natural_gas_2,NaN,2018_ST_natural_gas_2_nan,1,1,0,2,2018-01-01,NaN,NaN,3.908812e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.312719e+03,NaN,NaN,NaN,NaN,NaN,NaN,4.0,4.0,3.146900e+04,NaN,NaN,3.146900e+04,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,153.1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,63.915127,3.915127,25.739177,2.927320,2,<NA>,2,1.020267,25.226593,both
393873,3,3,2019,missing_years,ST,natural_gas,2,NaN,2019_ST_natural_gas,2019_ST_natural_gas_2,NaN,2019_ST_natural_gas_2_nan,1,1,0,2,2019-01-01,NaN,NaN,4.135949e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.952539e+03,NaN,NaN,NaN,NaN,NaN,NaN,6.0,5.0,2.945400e+04,NaN,NaN,2.945400e+04,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,153.1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,64.914442,2.915811,26.738493,2.927320,2,<NA>,2,1.078991,26.305583,both
145413,3,A1CT2,2006,missing_years,CC,natural_gas,2,NaN,2006_CC_natural_gas,2006_CC_natural_gas_2,NaN,2006_CC_natural_gas_2_nan,1,1,0,2,2006-01-01,NaN,NaN,1.593753e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.147195e+06,NaN,NaN,NaN,NaN,NaN,NaN,610.0,610.0,3.372844e+06,NaN,NaN,3.372844e+06,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,170.1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,5.670089,15.915127,-9.183096,2.927320,2,<NA>,2,1.050357,13.40423,both
279052,3,A1CT2,2007,missing_years,CC,natural_gas,2,NaN,2007_CC_natural_gas,2007_CC_natural_gas_2,NaN,2007_CC_natural_gas_2_nan,1,1,0,2,2007-01-01,NaN,NaN,5.696749e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.362440e+06,NaN,NaN,NaN,NaN,NaN,NaN,814.0,814.0,4.516821e+06,NaN,NaN,4.516821e+06,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,170.1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,6.669405,14.915811,-8.183780,2.927320,2,<NA>,2,1.057435,14.461664,both
13,3,A1CT2,2008,missing_years,CC,natural_gas,2,NaN,2008_CC_natural_gas,2008_CC_natural_gas_2,NaN,2008_CC_natural_gas_2_nan,1,1,0,2,2008-01-01,NaN,NaN,6.091393e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.582251e+05,NaN,NaN,NaN,NaN,NaN,NaN,886.0,886.0,4.820953e+06,NaN,NaN,4.820953e+06,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,170.1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,7.668720,13.916496,-7.184464,2.927320,2,<NA>,2,0.99812,15.459785,both
0,3,A1ST,2006,zeroes,CC,natural_gas,2,21.585216,2006_CC_natural_gas,2006_CC_natural_gas_2,3,2006_CC_natural_gas_2_3,1,1,1,3,2006-01-01,NaN,NaN,1.593753e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.147195e+06,NaN,NaN,NaN,NaN,NaN,NaN,610.0,610.0,3.372844e+06,NaN,NaN,3.372844e+06,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,170.1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,5.670089,15.915127,-9.183096,2.927320,2,<NA>,2,1.050357,13.40423,both
15,3,A2ST,2006,zeroes,CC,natural_gas,2,21.585216,2006_CC_natural_gas,2006_CC_natural_gas_2,3,2006_CC_natural_gas_2_3,1,1,1,3,2006-01-01,NaN,NaN,1.593753e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.147195e+06,NaN,NaN,NaN,NaN,NaN,NaN,610.0,610.0,3.372844e+06,NaN,NaN,3.372844e+06,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,170.1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,5.670089,15.915127,-9.183096,2.927320,2,<NA>,2,1.050357,13.40423,both
335783,7,1,2006,fuel_switch,ST,natural_gas,2,72.668036,2006_ST_natural_gas,2006_ST_natural_gas_2,8,2006_ST_natural_gas_2_8,1,1,1,3,2006-01-01,NaN,2.783880e+06,5.545650e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,188158.000000,3.666000e+03,NaN,NaN,NaN,NaN,NaN,NaN,0.0,13.0,0.000000e+00,NaN,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,69.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,56.752909,15.915127,18.576960,7.271187,2,<NA>,2,1.050357,13.40423,both
335785,7,1,2007,fuel_switch,ST,natural_gas,2,72.668036,2007_ST_natural_gas,2007_ST_natural_gas_2,8,2007_ST_natural_gas_2_8,1,1,1,3,2007-01-01,NaN,3.478842e+06,5.729100e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,253226.242000,4.129722e+03,NaN,NaN,NaN,NaN,NaN,NaN,0.0,7.0,0.000000e+00,NaN,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,69.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,57.752225,14.915811,19.576275,7.271187,2,<NA>,2,1.057435,14.461664,both
335787,7,1,2008,fuel_switch,ST,natural_gas,2,72.668036,2008_ST_natural_gas,2008_ST_natural_gas_2,8,2008_ST_natural_gas_2_8,1,1,1,3,2008-01-01,NaN,3.695503e+06,3.241644e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,275626.650993,2.385085e+03,NaN,NaN,NaN,NaN,NaN,NaN,0.0,25.0,0.000000e+00,NaN,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,69.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,58.751540,13.916496,20.575591,7.271187,2,<NA>,2,0.99812,15.459785,both
335789,7,1,2010,fuel_switch,ST,natural_gas,2,72.668036,2010_ST_natural_gas,2010_ST_natural_gas_2,8,2010_ST_natural_gas_2_8,1,1,1,3,2010-01-01,NaN,2.079278e+06,1.494763e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,125705.311732,7.223908e+03,NaN,NaN,NaN,NaN,NaN,NaN,0.0,10.0,0.000000e+00,NaN,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,69.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,60.752909,11.915127,22.576960,7.271187,2,<NA>,2,0.941299,17.374014,both
335791,7,1,2011,fuel_switch,ST,natural_gas,2,72.668036,2011_ST_natural_gas,2011_ST_natural_gas_2,8,2011_ST_natural_gas_2_8,1,1,1,3,2011-01-01,NaN,2.692109e+06,2.675087e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,167566.149163,1.609162e+04,NaN,NaN,NaN,NaN,NaN,NaN,0.0,5.0,0.000000e+00,NaN,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,69.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,61.752225,10.915811,23.576275,7.271187,2,<NA>,2,0.973222,18.347236,both
30,7,1,2015,zeroes,ST,biofuel,2,72.668036,2015_ST_biofuel,2015_ST_biofuel_2,8,2015_ST_biofuel_2_8,1,1,1,3,2015-01-01,0.0,2.072460e+05,1.749893e+06,NaN,NaN,NaN,NaN,NaN,NaN,0.0,8532.732940,1.384473e+05,NaN,NaN,NaN,NaN,NaN,NaN,0.0,6.0,0.000000e+00,0.0,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,69.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,65.752225,6.915811,27.576275,7.271187,2,<NA>,2,0.973045,22.190632,both
32,7,1,2016,zeroes,ST,biofuel,2,72.668036,2016_ST_biofuel,2016_ST_biofuel_2,8,2016_ST_biofuel_2_8,1,1,1,3,2016-01-01,0.0,0.000000e+00,1.988157e+06,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.000000,1.481480e+05,NaN,NaN,NaN,NaN,NaN,NaN,0.0,9.0,0.000000e+00,0.0,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,69.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,66.751540,5.916496,28.575591,7.271187,2,<NA>,2,1.011758,23.20239,both
335793,7,2,2006,fuel_switch,ST,natural_gas,2,72.418891,2006_ST_natural_gas,2006_ST_natural_gas_2,8,2006_ST_natural_gas_2_8,1,1,1,3,2006-01-01,NaN,2.783880e+06,5.545650e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,188158.000000,3.666000e+03,NaN,NaN,NaN,NaN,NaN,NaN,0.0,13.0,0.000000e+00,NaN,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,69.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,56.752909,15.915127,18.576960,7.271187,2,<NA>,2,1.050357,13.40423,both
335795,7,2,2007,fuel_switch,ST,natural_gas,2,72.418891,2007_ST_natural_gas,2007_ST_natural_gas_2,8,2007_ST_natural_gas_2_8,1,1,1,3,2007-01-01,NaN,3.478842e+06,5.729100e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,253226.242000,4.129722e+03,NaN,NaN,NaN,NaN,NaN,NaN,0.0,7.0,0.000000e+00,NaN,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,69.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,57.752225,14.915811,19.576275,7.271187,2,<NA>,2,1.057435,14.461664,both
335797,7,2,2008,fuel_switch,ST,natural_gas,2,72.418891,2008_ST_natural_gas,2008_ST_natural_gas_2,8,2008_ST_natural_gas_2_8,1,1,1,3,2008-01-01,NaN,3.695503e+06,3.241644e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,275626.650993,2.385085e+03,NaN,NaN,NaN,NaN,NaN,NaN,0.0,25.0,0.000000e+00,NaN,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,69.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,58.751540,13.916496,20.575591,7.271187,2,<NA>,2,0.99812,15.459785,both
335799,7,2,2010,fuel_switch,ST,natural_gas,2,72.418891,2010_ST_natural_gas,2010_ST_natural_gas_2,8,2010_ST_natural_gas_2_8,1,1,1,3,2010-01-01,NaN,2.079278e+06,1.494763e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,125705.311732,7.223908e+03,NaN,NaN,NaN,NaN,NaN,NaN,0.0,10.0,0.000000e+00,NaN,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,69.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,60.752909,11.915127,22.576960,7.271187,2,<NA>,2,0.941299,17.374014,both
36,7,2,2015,zeroes,ST,biofuel,2,72.418891,2015_ST_biofuel,2015_ST_biofuel_2,8,2015_ST_biofuel_2_8,1,1,1,3,2015-01-01,0.0,2.072460e+05,1.749893e+06,NaN,NaN,NaN,NaN,NaN,NaN,0.0,8532.732940,1.384473e+05,NaN,NaN,NaN,NaN,NaN,NaN,0.0,6.0,0.000000e+00,0.0,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,69.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,65.752225,6.915811,27.576275,7.271187,2,<NA>,2,0.973045,22.190632,both
38,7,2,2016,zeroes,ST,biofuel,2,72.418891,2016_ST_biofuel,2016_ST_biofuel_2,8,2016_ST_biofuel_2_8,1,1,1,3,2016-01-01,0.0,0.000000e+00,1.988157e+06,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.000000,1.481480e+05,NaN,NaN,NaN,NaN,NaN,NaN,0.0,9.0,0.000000e+00,0.0,0.000000e+00,0.000000e+00,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,69.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,66.751540,5.916496,28.575591,7.271187,2,<NA>,2,1.011758,23.20239,both

In [137]:
m['fill_in_score'].value_counts(normalize=True)

3    0.386181
2    0.310098
1    0.303721
Name: fill_in_score, dtype: float64

In [144]:
m['fill_in_score'].value_counts()

3    17623
2    14151
1    13860
Name: fill_in_score, dtype: int64

In [140]:
m.query('fill_in_score == 3')['final_ba_code'].unique()

array(['2', 'EPE', 'TVA', '22', 'SWPP', 'APS', 'TEPC', 'SC', 'SEC', 'SRP',
       'WALC', 'ETR', 'MISO', 'JEA', 'CAISO', 'ERCO', 'LDWP', 'PJM',
       'PSCO', 'WACM', '529', 'AEC', 'ISNE', 'FMPP', 'FPL', 'FPC', 'TEC',
       '57', '177', 'DUKE', 'LNT', '210', 'EVRG', 'LGEE', '556', '41',
       '44', '193', '120', '99', '552', 'AECI', '658', 'NEVP', 'PNM',
       'NYIS', '130', 'SCEG', '166', 'PAC', 'AEP', '186', 'PNW', '195',
       '531', 'SOCO', '560', '569'], dtype=object)

In [141]:
m.query('fill_in_score == 3')['age_in_current_year'].unique()

array([67.83025325, 67.41957563, 21.58521561, 72.66803559, 72.41889117,
       41.41820671, 56.50102669, 55.41957563, 61.58521561, 61.41820671,
       60.50102669, 59.50171116, 49.24845996, 35.66872005, 39.00068446,
       59.58658453, 43.50171116, 41.58521561, 40.50102669, 61.50034223,
       61.7522245 , 20.50102669, 66.50239562, 62.66940452, 54.4202601 ,
       63.00068446, 61.16632444, 26.58726899, 37.58521561, 14.91581109,
       13.16632444, 37.83162218, 63.91512663, 64.66803559, 60.66803559,
       69.41820671, 67.50171116, 19.16769336, 42.91581109, 36.1670089 ,
       70.58726899, 53.7522245 , 58.58726899, 19.00068446, 49.58521561,
       34.66940452, 33.41820671, 19.41957563, 36.        , 35.00068446,
       65.41820671, 63.33470226, 48.08213552, 43.08281999, 67.08281999,
       57.33333333, 56.66803559, 67.16769336, 64.41889117, 54.83093771,
       68.        , 62.25051335, 57.08145106, 55.75359343, 69.33333333,
       28.50102669, 64.08213552, 53.33333333, 27.91512663, 19.91512663,
       59.24982888, 16.91444216,  8.50102669, 58.66940452, 55.33470226,
       54.75427789, 62.4202601 , 47.16769336,  6.16837782,  6.08350445,
        6.33538672,  6.25051335, 17.41820671,  4.99931554, 66.25051335,
       62.91581109, 53.50034223, 47.41957563, 49.33333333, 20.82956879,
       12.58590007, 30.91581109, 67.00068446, 62.33538672, 24.99931554,
       25.41820671, 64.91444216, 34.4202601 , 25.50034223, 11.83025325,
       60.3340178 , 37.50034223, 58.50239562, 55.66872005, 48.3340178 ,
       59.91512663, 59.75359343, 46.58726899,  8.66803559, 66.4202601 ,
       20.99931554, 20.66803559, 20.58590007, 18.50239562, 63.08281999,
       52.41889117, 28.58590007, 64.1670089 , 63.66872005, 58.75427789,
       62.58726899, 18.91581109, 47.58658453, 19.58658453, 14.58726899,
       52.75290897, 52.66803559, 51.00068446, 50.91581109, 12.50102669,
       68.08213552, 65.16632444, 19.66872005, 12.3340178 , 51.16769336,
       48.66803559, 45.58521561, 36.82956879, 68.91444216, 57.91649555,
       25.91649555, 21.50034223, 44.50102669, 38.83093771, 38.08350445,
       44.99931554, 54.08350445, 43.75359343, 65.66735113, 29.41820671,
       39.24982888, 48.58590007, 50.83093771, 45.50034223, 50.58726899,
       44.1670089 , 51.83025325, 16.24914442, 16.08213552, 55.50171116,
       21.41820671, 58.00136893, 57.58521561, 60.08213552, 50.25051335,
       45.33333333, 28.99931554,  9.66735113, 10.00136893, 47.66872005,
       51.24982888, 51.33470226, 49.7522245 , 52.50102669, 70.75427789,
       62.50239562, 53.41820671, 68.3340178 , 68.24914442, 67.58658453,
       67.33470226, 66.33538672, 51.41957563, 48.75290897, 54.33538672,
       54.16837782, 19.50171116, 16.50102669, 16.1670089 , 49.50034223,
       56.        , 51.08281999,  9.58521561, 73.91649555, 61.91649555,
       58.33538672, 58.25051335, 43.16769336, 18.58726899, 63.50171116,
       60.58590007, 48.41889117, 96.91444216, 83.41957563, 53.08145106,
       51.58658453, 64.99931554, 71.00068446, 71.24982888, 40.58590007,
       57.50034223, 45.41820671, 44.41889117, 66.91581109, 56.91444216,
       62.83093771, 72.50102669, 69.91649555, 55.91512663, 51.91512663,
       54.91581109, 91.08281999, 79.50171116, 76.75290897, 71.16769336,
       43.41957563, 63.16769336, 54.66940452, 66.58726899, 60.91444216,
       53.58521561, 22.4202601 , 53.91649555, 21.24845996, 48.50102669,
       17.58521561, 61.66735113, 32.99931554, 33.08145106, 71.50171116,
       54.50239562, 69.58521561, 65.50034223, 56.58590007, 50.00136893,
       55.00068446, 68.75290897, 58.91581109, 57.66735113, 47.75359343,
       52.24914442, 45.7522245 , 56.82956879, 52.1670089 , 70.16837782,
       67.24982888, 22.91581109, 71.91512663, 71.08281999, 68.58590007,
       48.91444216, 45.91649555, 50.75427789, 60.75290897, 68.41889117,
       66.08350445,  7.00068446, 47.24982888, 71.66872005, 54.25051335,
       64.58590007, 58.83093771, 64.50102669, 51.50171116, 44.91444216,
       26.50239562, 70.25051335, 51.66872005, 30.50239562, 50.50239562,
       46.50239562, 47.00068446, 69.24845996, 52.91444216, 44.66803559,
       12.41889117, 45.16632444, 52.99931554, 41.24845996, 68.99931554,
       70.33538672, 78.66940452, 74.83093771, 46.66940452, 63.58658453,
       18.75427789, 70.66940452, 49.91649555, 35.41957563, 49.41820671,
       68.50102669, 63.41957563, 70.50239562, 63.75359343, 72.1670089 ,
       72.08213552, 81.50034223, 86.50239562, 75.50171116, 50.66940452,
       36.3340178 , 25.83162218, 24.58590007, 39.66872005, 73.33333333,
       59.08281999, 52.        , 29.33333333, 50.33538672, 50.16837782,
       70.83093771, 73.41820671, 25.16632444, 60.1670089 , 56.1670089 ,
       75.16769336, 73.83162218, 69.50034223, 66.66940452, 76.50102669,
       53.66735113, 24.50102669, 44.58590007, 71.41957563, 32.58590007,
       60.41889117, 47.50171116, 35.50171116, 56.3340178 , 73.50034223,
       64.3340178 , 61.83162218, 32.66803559, 29.50034223, 61.08145106,
       42.50239562, 83.91512663, 18.08350445, 49.83162218, 64.        ,
       27.58658453, 38.4202601 , 53.24845996, 27.41957563, 52.3340178 ,
       69.16632444, 59.16769336, 48.1670089 , 47.91512663, 31.41957563,
       56.99931554, 20.3340178 , 15.66872005, 60.99931554, 72.99931554,
       73.08145106, 70.4202601 , 56.08213552,  9.50034223, 42.00136893,
       62.75427789, 70.00136893, 62.16837782, 16.66803559, 70.08350445,
       18.00136893, 65.08145106, 58.16837782, 16.41889117, 61.33333333,
       66.75427789,  2.00136893, 98.00136893, 97.16632444, 53.83162218,
       52.58590007, 10.08350445,  8.99931554, 58.08350445,  7.33470226,
       56.24914442, 72.91444216, 23.00068446, 72.75290897, 69.08145106,
       71.75359343, 20.41889117, 20.75290897, 58.4202601 , 51.75359343,
       67.91512663, 29.24845996, 67.75359343, 46.16837782, 57.41820671,
       35.08281999, 31.83025325, 34.00136893, 81.91649555, 74.91581109,
       70.91581109, 22.00136893, 73.66735113, 65.58521561, 44.        ,
       46.4202601 , 45.24845996, 69.66735113, 54.00136893, 62.00136893,
       72.24914442, 10.4202601 , 52.08213552, 26.08350445, 26.25051335,
       22.50239562, 79.75359343, 79.83025325, 78.83093771, 76.66803559,
       74.58726899, 72.58590007, 76.        , 65.83162218, 60.        ,
       46.33538672, 48.        , 47.33470226, 33.33333333, 33.58521561,
       48.99931554, 68.66803559, 50.4202601 , 43.91512663, 33.24845996,
       49.66735113, 11.00068446, 60.24914442, 18.16837782, 56.41889117,
       63.24982888, 31.50171116, 29.58521561, 59.66872005, 18.4202601 ,
       19.33470226, 31.91512663, 32.        , 72.82956879, 83.16769336,
       13.58521561, 75.91512663, 61.24845996, 71.58658453, 15.16769336,
       44.3340178 , 17.08145106, 42.66940452, 40.99931554, 57.24845996,
       44.75290897, 46.08350445, 34.58726899, 30.75427789, 16.75290897,
       12.66803559, 27.83025325, 27.66872005, 40.41889117, 39.41957563,
       38.66940452, 31.00068446, 10.83093771, 40.08213552, 37.33333333,
       34.16837782, 42.83093771, 26.66940452, 27.50171116, 41.50034223,
       38.50239562, 36.41889117, 33.66735113, 43.33470226, 18.66940452,
       43.24982888, 43.66872005, 37.41820671, 14.16837782, 40.91444216,
       37.24845996, 31.24982888, 30.16837782, 23.50171116, 32.50102669,
       32.41889117, 30.58726899, 28.41889117, 27.33470226, 26.16837782,
       25.7522245 , 27.08281999, 25.24845996, 14.75427789, 14.66940452,
       28.08213552, 26.75427789, 31.58658453, 32.91444216, 22.66940452,
       14.00136893, 42.4202601 , 15.00068446, 24.24914442, 25.66735113,
       23.16769336, 55.16769336, 22.83093771, 24.3340178 , 21.91649555,
       20.91444216, 22.33538672, 20.24914442, 19.75359343, 17.24845996,
       20.1670089 , 16.82956879, 28.75290897, 28.66803559, 17.33333333,
       17.66735113, 18.33538672, 19.83025325, 21.33333333, 43.58658453,
       47.08281999, 46.91581109, 47.83025325, 31.75359343, 41.66735113,
       34.33538672,  6.66940452, 65.91649555, 36.58590007, 37.16632444,
       29.7522245 , 33.83162218, 41.91649555, 32.75290897, 26.83093771,
       35.75359343, 33.91649555, 29.83162218, 41.83162218, 39.91512663,
       34.83093771, 38.33538672, 30.08350445, 30.25051335, 55.24982888,
       28.3340178 , 15.58658453, 33.50034223, 32.24914442, 34.25051335,
       31.16769336, 21.16632444, 40.3340178 , 36.99931554, 93.33333333,
       26.33538672, 35.16769336, 34.50239562, 31.08281999, 34.75427789,
       28.24914442, 27.16769336, 35.91512663, 39.83025325, 37.08145106,
       34.08350445, 29.66735113, 28.82956879, 20.        , 82.91581109,
       28.1670089 , 33.7522245 , 66.16837782, 12.82956879, 30.66940452,
       21.08145106, 27.24982888, 24.66803559, 87.91512663, 36.91444216,
       39.58658453, 39.50171116, 39.33470226,  8.82956879, 38.25051335,
       36.75290897,  7.66872005, 30.33538672, 32.08213552, 26.4202601 ,
        9.08145106, 30.4202601 , 37.66735113, 92.91444216, 91.91512663,
       85.91649555, 32.3340178 , 42.16837782, 72.3340178 , 36.08213552,
       15.75359343, 33.16632444, 38.00136893, 24.91444216, 35.58658453,
       27.00068446, 78.50239562, 78.58726899, 74.25051335, 52.82956879,
       44.24914442, 78.91581109, 21.83162218, 17.91649555, 43.83025325,
       16.99931554, 44.08213552, 30.00136893, 32.1670089 , 36.50102669,
       35.83025325, 28.91444216, 24.82956879, 35.33470226, 19.24982888,
       40.1670089 , 29.91649555, 12.24914442, 79.91512663, 77.91649555,
       93.50034223, 39.16769336, 37.7522245 , 93.91649555, 35.24982888,
       24.08213552, 84.08213552, 10.75427789, 40.        , 91.83025325,
       26.91581109, 29.08145106, 16.58590007, 87.16769336, 81.7522245 ,
       14.08350445, 15.91512663, 29.16632444, 57.83162218, 40.75290897,
       28.        , 25.08145106, 66.00136893, 53.16632444, 26.00136893,
       39.08281999, 81.08145106, 17.50034223, 59.33470226, 18.25051335,
       24.1670089 , 55.08281999, 37.91649555, 25.33333333, 27.75359343,
       34.91581109,  4.08213552, 22.16837782, 22.08350445, 21.66735113,
       23.83025325, 24.        , 22.25051335, 17.83162218, 11.91512663,
        6.58726899, 23.08281999, 15.83025325, 15.08281999, 14.33538672,
        9.83162218, 17.7522245 , 23.33470226, 20.08213552, 18.83093771,
       15.50171116, 10.91581109, 15.41957563, 16.        , 13.66735113,
       11.24982888,  8.41889117, 12.08213552, 13.24845996, 12.91444216,
       10.50239562, 11.50171116,  8.58590007,  9.7522245 , 10.58726899,
       12.99931554,  3.58658453, 11.58658453, 11.41957563,  8.        ,
       14.4202601 , 12.1670089 , 12.        ,  6.50239562, 36.66803559,
       11.08281999, 42.08350445, 73.16632444, 14.83093771, 23.91512663,
       13.50034223, 22.75427789,  2.58726899,  7.83025325,  5.66735113,
        5.50034223,  6.75427789,  5.58521561,  5.24845996,  8.24914442,
        8.08213552,  7.16769336,  6.4202601 , 23.24982888,  3.00068446,
        6.00136893,  7.75359343,  3.33470226,  5.16632444,  9.91649555])

In [175]:
m = self.fill_in_ep_data()

/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:258: UserWarning: This crosswalk is not safe, it may have `pf_subplants with multiple primes. Use `safe_xwalk` instead.
  return self._xwalk.grand_crosswalk
/opt/anaconda3/envs/gencost/lib/python3.11/site-packages/etoolbox/utils/pudl_helpers.py:146: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[date_mask, date_col] = pd.to_datetime(
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:258: UserWarning: This crosswalk is not safe, it may have `pf_subplants with multiple primes. Use `safe_xwalk` instead.
  return self._xwalk.grand_crosswalk
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:199: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  np.repeat(df[old_cols].sum(axis=1)[:, np.newaxis], len(old_cols), 1) != 0.0,
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:204: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  df[old_cols].isna().sum(axis=1)[:, np.newaxis], len(old_cols), 1
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:213: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  df[to_allocate][:, np.newaxis],
/opt/anaconda3/envs/gencost/lib/python3.11/site-packages/etoolbox/utils/pudl_helpers.py:146: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[date_mask, date_col] = pd.to_datetime(
/opt/anaconda3/envs/gencost/lib/python3.11/site-packages/etoolbox/utils/pudl_helpers.py:146: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[date_mask, date_col] = pd.to_datetime(
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:258: UserWarning: This crosswalk is not safe, it may have `pf_subplants with multiple primes. Use `safe_xwalk` instead.
  return self._xwalk.grand_crosswalk
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:199: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  np.repeat(df[old_cols].sum(axis=1)[:, np.newaxis], len(old_cols), 1) != 0.0,
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:204: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  df[old_cols].isna().sum(axis=1)[:, np.newaxis], len(old_cols), 1
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:213: FutureWarning: Support for multi-dimensional indexing (e.g. `obj[:, None]`) is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
  df[to_allocate][:, np.newaxis],
/opt/anaconda3/envs/gencost/lib/python3.11/site-packages/etoolbox/utils/pudl_helpers.py:146: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[date_mask, date_col] = pd.to_datetime(
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:258: UserWarning: This crosswalk is not safe, it may have `pf_subplants with multiple primes. Use `safe_xwalk` instead.
  return self._xwalk.grand_crosswalk
/opt/anaconda3/envs/gencost/lib/python3.11/site-packages/etoolbox/utils/pudl_helpers.py:146: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df.loc[date_mask, date_col] = pd.to_datetime(
/Users/mcastillo/Library/CloudStorage/OneDrive-RMI/Documents/GitHub/gencost/src/gencost/waterfall.py:2375: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  split = pd.DataFrame([pd.Series(x) for x in missing_years.years_to_fill_in])

In [173]:
m

,plant_id_eia,generator_id,fuss,final_ba_code,age_in_current_year,report_date,biofuel_mmbtu,coal_mmbtu,natural_gas_mmbtu,nuclear_mmbtu,other_mmbtu,other_gas_mmbtu,petroleum_mmbtu,petroleum_coke_mmbtu,renew_mmbtu,biofuel_net_mwh,coal_net_mwh,natural_gas_net_mwh,nuclear_net_mwh,other_net_mwh,other_gas_net_mwh,petroleum_net_mwh,petroleum_coke_net_mwh,renew_net_mwh,generator_starts,fuel_starts,gross_generation_mwh,biofuel_gross_mwh,coal_gross_mwh,natural_gas_gross_mwh,other_gross_mwh,other_gas_gross_mwh,petroleum_gross_mwh,petroleum_coke_gross_mwh,renew_gross_mwh,utility_id_eia,balancing_authority_code_eia,state,capacity_mw,associated_combined_heat_power,duct_burners,bypass_heat_recovery,solid_fuel_gasification,carbon_capture,fluidized_bed_tech,pulverized_coal_tech,stoker_tech,other_combustion_tech,subcritical_tech,supercritical_tech,ultrasupercritical_tech,age_in_report_year,age_of_observation,age_relative_to_prime_avg,pollution_control_costs_per_kw,respondent_id,respondent_id_purchaser,final_respondent_id,wage_scale,age_of_observation_secular_adj,fill_in_match
785664,1,1,zeroes,Alaska,20.999316,2020-01-01,NaN,NaN,NaN,NaN,NaN,NaN,343.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,138.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,20847,MISO,WI,2.7,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,50.836413,1.916496,28.969892,106.666667,193,<NA>,193,0.959081,26.618848,essentials
785667,1,2,zeroes,Alaska,20.999316,2020-01-01,NaN,NaN,NaN,NaN,NaN,NaN,343.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,138.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,20847,MISO,WI,2.7,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,50.836413,1.916496,28.969892,106.666667,193,<NA>,193,0.959081,26.618848,essentials
785670,1,3,zeroes,Alaska,11.000684,2020-01-01,NaN,NaN,NaN,NaN,NaN,NaN,343.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,138.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,20847,MISO,WI,2.7,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,50.836413,1.916496,28.969892,106.666667,193,<NA>,193,0.959081,26.618848,essentials
785673,1,5,zeroes,Alaska,20.999316,2020-01-01,NaN,NaN,NaN,NaN,NaN,NaN,343.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,138.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,20847,MISO,WI,2.7,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,50.836413,1.916496,28.969892,106.666667,193,<NA>,193,0.959081,26.618848,essentials
335705,3,1,fuel_switch,2,67.830253,2006-01-01,NaN,1.008871e+07,29511.495021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,964082.899927,4120.479810,NaN,NaN,NaN,NaN,NaN,NaN,7.0,7.0,1123980.0,NaN,1.120702e+06,3278.277774,NaN,NaN,NaN,NaN,NaN,195,SOCO,AL,153.1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,51.915127,15.915127,13.739177,2.927320,2,<NA>,2,1.050357,13.40423,essentials_ba_age_group
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3996801,64815,GEN2,zeroes,ERCO,2.420260,2020-01-01,NaN,NaN,124809.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13447.611111,NaN,NaN,NaN,NaN,NaN,NaN,147.0,149.0,323384.0,NaN,NaN,323384.000000,NaN,NaN,NaN,NaN,NaN,7349,SWPP,TX,9.3,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,8.585900,1.916496,-13.280621,NaN,58,<NA>,58,1.013692,27.335436,essentials
3996804,64815,GEN3,zeroes,ERCO,2.420260,2020-01-01,NaN,NaN,124809.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13447.611111,NaN,NaN,NaN,NaN,NaN,NaN,147.0,149.0,323384.0,NaN,NaN,323384.000000,NaN,NaN,NaN,NaN,NaN,7349,SWPP,TX,9.3,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,8.585900,1.916496,-13.280621,NaN,58,<NA>,58,1.013692,27.335436,essentials
3996807,64816,GEN1,zeroes,ERCO,1.248460,2020-01-01,NaN,NaN,124809.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13447.611111,NaN,NaN,NaN,NaN,NaN,NaN,147.0,149.0,323384.0,NaN,NaN,323384.000000,NaN,NaN,NaN,NaN,NaN,7349,SWPP,TX,9.3,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,8.585900,1.916496,-13.280621,NaN,58,<NA>,58,1.013692,27.335436,essentials
3996810,64816,GEN2,zeroes,ERCO,1.248460,2020-01-01,NaN,NaN,124809.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13447.611111,NaN,NaN,NaN,NaN,NaN,NaN,147.0,149.0,323384.0,NaN,NaN,323384.000000,NaN,NaN,NaN,NaN,NaN,7349,SWPP,TX,9.3,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,8.585900,1.916496,-13.280621,NaN,58,<NA>,58,1.013692,27.335436,essentials
3996813,64816,GEN3,zeroes,ERCO,1.248460,2020-01-01,NaN,NaN,124809.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13447.611111,NaN,NaN,NaN,NaN,NaN,NaN,147.0,149.0,323384.0,NaN,NaN,323384.000000,NaN,NaN,NaN,NaN,NaN,7349,SWPP,TX,9.3,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,8.585900,1.916496,-13.280621,NaN,58,<NA>,58,1.013692,27.335436,essentials